export const GENERATED_TYPESCRIPT_MARKER = "// Code generated by intercall-ts; DO NOT EDIT.\n";

export interface GeneratedMetadata {
    readonly bodyChunks: readonly string[];
    readonly interfaceIDHex: string;
    readonly machineTypes: readonly { readonly wireName: string; readonly nativeName: string }[];
}

export function hasGeneratedTypeScriptMarker(source: string): boolean {
    return source.startsWith(GENERATED_TYPESCRIPT_MARKER);
}

export function readGeneratedMetadata(source: string): GeneratedMetadata {
    if (!hasGeneratedTypeScriptMarker(source)) throw new Error("generated metadata marker is missing");
    const chunks = readConstant(source, "interfaceBodyChunks");
    const interfaceIDHex = readConstant(source, "interfaceIDHex");
    const machineTypes = readConstant(source, "machineTypes");
    if (!Array.isArray(chunks) || !chunks.every((chunk): chunk is string => typeof chunk === "string" && chunk.length <= 4096)) throw new Error("invalid interface body chunks");
    if (typeof interfaceIDHex !== "string" || !/^[0-9a-f]{64}$/u.test(interfaceIDHex)) throw new Error("invalid interface ID metadata");
    if (!Array.isArray(machineTypes) || machineTypes.some((row) => typeof row !== "object" || row === null || typeof row.wireName !== "string" || typeof row.nativeName !== "string")) throw new Error("invalid machine type metadata");
    const keys = new Set<string>();
    for (const row of machineTypes) {
        if (keys.has(row.wireName)) throw new Error(`duplicate machine type row ${row.wireName}`);
        keys.add(row.wireName);
    }
    return { bodyChunks: chunks, interfaceIDHex, machineTypes };
}

function readConstant(source: string, name: string): unknown {
    const match = new RegExp(`export const ${name} = (.+);`, "u").exec(source);
    if (match === null) throw new Error(`missing generated metadata constant ${name}`);
    try {
        const expression = match[1]!.replace(/^Object\.freeze\((.*)\)$/u, "$1");
        return JSON.parse(expression);
    } catch { throw new Error(`invalid generated metadata constant ${name}`); }
}
