import { attachDocumentation, formatInterface, parseInterface, validateInterface, type InterfaceFile } from "../syntax/index.js";
import { interfaceID, interfaceIDHex } from "./interface-id.js";
import { isCanonicalWireName, isValidTypeScriptIdentifier } from "./name.js";

export const GENERATED_TYPESCRIPT_MARKER = "// Code generated by intercall-ts; DO NOT EDIT.\n";

export interface GeneratedMetadata {
    readonly bodyChunks: readonly string[];
    readonly interfaceIDHex: string;
    readonly machineTypes: readonly { readonly wireName: string; readonly nativeName: string }[];
}

export function hasGeneratedTypeScriptMarker(source: string): boolean {
    return source.startsWith(GENERATED_TYPESCRIPT_MARKER);
}

export function semanticDocumentation(file: InterfaceFile): ReadonlyMap<string, string> {
    const documentation = new Map<string, string>();
    for (const declaration of file.declarations) {
        if (declaration.kind === "type-decl" || declaration.kind === "exception-decl" || declaration.kind === "procedure-decl") documentation.set(declaration.name.name, declaration.doc);
    }
    return documentation;
}

export function validateMetadataRows(file: InterfaceFile, rows: readonly { readonly wireName: string; readonly nativeName: string }[]): void {
    const types = new Set(file.declarations.filter((declaration) => declaration.kind === "type-decl").map((declaration) => declaration.name.name));
    const seen = new Set<string>();
    for (const row of rows) {
        if (!isCanonicalWireName(row.wireName) || !isValidTypeScriptIdentifier(row.nativeName)) throw new Error(`invalid machine type row ${row.wireName}`);
        if (!types.has(row.wireName) || seen.has(row.wireName)) throw new Error(`machine type row bijection failure ${row.wireName}`);
        seen.add(row.wireName);
    }
    if (seen.size !== types.size) throw new Error("machine type row is missing");
}

export function decodeGeneratedInterface(metadata: GeneratedMetadata): InterfaceFile {
    let bytes: Uint8Array;
    try { bytes = new Uint8Array(Buffer.from(metadata.bodyChunks.join(""), "base64url")); } catch { throw new Error("invalid metadata base64url"); }
    let text: string;
    try { text = new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { throw new Error("invalid metadata UTF-8"); }
    const file = parseInterface("generated-metadata.intercall", bytes);
    validateInterface(file);
    attachDocumentation(file);
    if (formatInterface(file) !== text) throw new Error("metadata interface is not canonical");
    if (interfaceIDHex(interfaceID(text)) !== metadata.interfaceIDHex) throw new Error("metadata interface ID does not match");
    return file;
}

export function readGeneratedMetadata(source: string): GeneratedMetadata {
    if (!hasGeneratedTypeScriptMarker(source)) throw new Error("generated metadata marker is missing");
    const chunks = readConstant(source, "interfaceBodyChunks");
    const interfaceIDHex = readConstant(source, "interfaceIDHex");
    const machineTypes = readConstant(source, "machineTypes");
    if (!Array.isArray(chunks) || !chunks.every((chunk): chunk is string => typeof chunk === "string" && chunk.length <= 4096)) throw new Error("invalid interface body chunks");
    if (typeof interfaceIDHex !== "string" || !/^[0-9a-f]{64}$/u.test(interfaceIDHex)) throw new Error("invalid interface ID metadata");
    if (!Array.isArray(machineTypes) || machineTypes.some((row) => typeof row !== "object" || row === null || typeof row.wireName !== "string" || typeof row.nativeName !== "string")) throw new Error("invalid machine type metadata");
    const keys = new Set<string>();
    for (const row of machineTypes) {
        if (keys.has(row.wireName)) throw new Error(`duplicate machine type row ${row.wireName}`);
        keys.add(row.wireName);
    }
    return { bodyChunks: chunks, interfaceIDHex, machineTypes };
}

function readConstant(source: string, name: string): unknown {
    const match = new RegExp(`export const ${name} = (.+);`, "u").exec(source);
    if (match === null) throw new Error(`missing generated metadata constant ${name}`);
    try {
        const expression = match[1]!.replace(/^Object\.freeze\((.*)\)$/u, "$1");
        return JSON.parse(expression);
    } catch { throw new Error(`invalid generated metadata constant ${name}`); }
}
