export const GENERATED_TYPESCRIPT_MARKER = "// Code generated by intercall-ts; DO NOT EDIT.\n";

export function hasGeneratedTypeScriptMarker(source: string): boolean {
    return source.startsWith(GENERATED_TYPESCRIPT_MARKER);
}
