package tool

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// This file tests the deterministic repeated invocation of the exact
// command pipeline of SPEC.md "Commands" and "One-file ownership and
// safe replacement": identical semantic inputs and Go build
// configuration produce identical generated binding and interface
// bytes, and a repeated invocation over the same targets replaces
// nothing. Unlike TestArtifactDeterminism, which stages canned bytes,
// these tests run the complete pipeline the command performs —
// discovery in a temporary module, the export model, generation,
// package-name resolution, and the artifact write, and the import
// generation and write — so the generated bytes themselves are the
// determinism subject. Every test operates only in temporary
// directories.

// runExportCommand runs the complete export pipeline exactly as the
// command runs it: discovery in the fixture module, the export model
// with the resolved output package path, package-name resolution,
// the emitter, and the artifact write of the binding and its owned
// interface file. It returns the written bytes of both targets. The
// output directory is fresh on the first run — the pipeline accepts
// it and the write creates it — so the runs exercise the SPEC-correct
// first-run export flow.
func runExportCommand(t *testing.T, root, out, intf string) (binding, interfaceFile []byte) {
	t.Helper()
	res, err := discover(t, root, []string{"./prov"}, nil, nil, out)
	if err != nil {
		t.Fatalf("discover: %v", err)
	}
	model, err := MapExport(res, res.OutPath)
	if err != nil {
		t.Fatalf("MapExport: %v", err)
	}
	// The explicit package keeps the generated bytes identical across
	// the two output directories, whose base names differ.
	pkg, err := ResolvePackageName(ExportMode, out, "gen")
	if err != nil {
		t.Fatalf("ResolvePackageName: %v", err)
	}
	goFile, body, err := GenerateExport(model, pkg)
	if err != nil {
		t.Fatalf("GenerateExport: %v", err)
	}
	if err := WriteArtifacts(WriteConfig{
		Mode:          ExportMode,
		OutDir:        out,
		Package:       pkg,
		InterfacePath: intf,
		GoFile:        goFile,
		InterfaceBody: body,
		CheckGo:       NewExportGoChecker(res),
	}); err != nil {
		t.Fatalf("WriteArtifacts: %v", err)
	}
	binding, err = os.ReadFile(filepath.Join(out, bindingFile))
	if err != nil {
		t.Fatal(err)
	}
	interfaceFile, err = os.ReadFile(intf)
	if err != nil {
		t.Fatal(err)
	}
	return binding, interfaceFile
}

// runImportCommand runs the complete import pipeline exactly as the
// command runs it: generation from the exact interface bytes,
// package-name resolution, and the artifact write, and returns the
// written binding bytes.
func runImportCommand(t *testing.T, out, pkg string, src []byte) []byte {
	t.Helper()
	goFile, body, err := GenerateImport("det.intercall", src, nil, pkg)
	if err != nil {
		t.Fatalf("GenerateImport: %v", err)
	}
	if _, err := ResolvePackageName(ImportMode, out, pkg); err != nil {
		t.Fatalf("ResolvePackageName: %v", err)
	}
	if err := WriteArtifacts(WriteConfig{
		Mode:          ImportMode,
		OutDir:        out,
		Package:       pkg,
		GoFile:        goFile,
		InterfaceBody: body,
		CheckGo:       NewImportGoChecker(),
	}); err != nil {
		t.Fatalf("WriteArtifacts: %v", err)
	}
	binding, err := os.ReadFile(filepath.Join(out, bindingFile))
	if err != nil {
		t.Fatal(err)
	}
	return binding
}

// TestCommandDeterminism tests deterministic repeated invocation of
// the command pipelines.
func TestCommandDeterminism(t *testing.T) {
	t.Run("ExportPipelineIsDeterministic", func(t *testing.T) {
		root := writeFixture(t, map[string]string{
			"go.mod": "module example.com/det\n\ngo 1.26.5\n",
			"prov/prov.go": `// Package prov is the determinism fixture provider.
package prov

import "context"

// Greet greets a user.
// @intercall procedure greet
// @intercall param name user
// @param name the user to greet
// @return the greeting
func Greet(ctx context.Context, name string) (string, error) {
	return "hi " + name, nil
}

// Ping checks liveness.
// @intercall procedure ping
func Ping(ctx context.Context) error { return nil }
`,
		})
		out1 := filepath.Join(root, "out1")
		out2 := filepath.Join(root, "out2")
		intfDir1 := filepath.Join(root, "intf1")
		intfDir2 := filepath.Join(root, "intf2")
		for _, d := range []string{intfDir1, intfDir2} {
			if err := os.MkdirAll(d, 0o777); err != nil {
				t.Fatal(err)
			}
		}
		intf1 := filepath.Join(intfDir1, "api.intercall")
		intf2 := filepath.Join(intfDir2, "api.intercall")

		// Identical semantic inputs and build configuration produce
		// identical binding and interface bytes in different output
		// directories. Both output directories are fresh on the first
		// run: discovery accepts them and the write creates them
		// (SPEC.md "One-file ownership and safe replacement": "It
		// creates --out if necessary").
		b1, i1 := runExportCommand(t, root, out1, intf1)
		b2, i2 := runExportCommand(t, root, out2, intf2)
		if !bytes.Equal(b1, b2) {
			t.Error("export binding bytes differ between identical runs")
		}
		if !bytes.Equal(i1, i2) {
			t.Error("export interface bytes differ between identical runs")
		}
		// No generated bytes carry an absolute or temporary path.
		for _, b := range [][]byte{b1, i1} {
			if bytes.Contains(b, []byte(root)) || bytes.Contains(b, []byte(".tmp-")) {
				t.Errorf("generated bytes contain an absolute or staging path: %q", b)
			}
		}

		// A repeated invocation over the same targets replaces nothing.
		bindingPath := filepath.Join(out2, bindingFile)
		bindingBefore, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		intfBefore, err := os.Stat(intf2)
		if err != nil {
			t.Fatal(err)
		}
		b3, i3 := runExportCommand(t, root, out2, intf2)
		if !bytes.Equal(b3, b2) || !bytes.Equal(i3, i2) {
			t.Error("repeated invocation changed the artifact bytes")
		}
		bindingAfter, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		intfAfter, err := os.Stat(intf2)
		if err != nil {
			t.Fatal(err)
		}
		if !os.SameFile(bindingBefore, bindingAfter) || !os.SameFile(intfBefore, intfAfter) {
			t.Error("repeated invocation replaced an unchanged target")
		}
		if !bindingBefore.ModTime().Equal(bindingAfter.ModTime()) || !intfBefore.ModTime().Equal(intfAfter.ModTime()) {
			t.Error("repeated invocation rewrote an unchanged target")
		}
	})

	t.Run("ImportPipelineIsDeterministic", func(t *testing.T) {
		src := []byte("/* docs */\nprocedure echo {\n    value string;\n} string;\n")
		out1 := filepath.Join(t.TempDir(), "gen1")
		out2 := filepath.Join(t.TempDir(), "gen2")

		// Identical semantic inputs produce identical binding bytes in
		// different output directories.
		b1 := runImportCommand(t, out1, "gen", src)
		b2 := runImportCommand(t, out2, "gen", src)
		if !bytes.Equal(b1, b2) {
			t.Error("import binding bytes differ between identical runs")
		}

		// A repeated invocation over the same target replaces nothing.
		bindingPath := filepath.Join(out2, bindingFile)
		before, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		b3 := runImportCommand(t, out2, "gen", src)
		if !bytes.Equal(b3, b2) {
			t.Error("repeated invocation changed the binding bytes")
		}
		after, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		if !os.SameFile(before, after) {
			t.Error("repeated invocation replaced the unchanged binding")
		}
		if !before.ModTime().Equal(after.ModTime()) {
			t.Error("repeated invocation rewrote the unchanged binding")
		}
	})
}
