package tool

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"runtime/debug"
	"strconv"
	"strings"
	"testing"

	"github.com/cerasos/intercall/go/internal/syntax"
)

// This file tests the strict Go projection boundary of SPEC.md "Strict
// Go projection depth" through subprocesses that lower the maximum Go
// stack: complete import and export generation succeed at the exact
// 4,096-occurrence ceiling, and every shape one occurrence deeper is
// rejected by the preflight before any recursive processing or Go
// formatting or parsing, with a stable physical source diagnostic.
//
// The shared codec layer registers one codec pair per anonymous type
// occurrence, so a pure list or record chain emits output quadratic in
// the chain length by design and is exercised at the boundary through
// model construction, while the named-interleaved chains — whose
// emission is linear — run the complete generation pipeline at the
// boundary.

// deepMaxStackBytes and deepSubprocessTimeout calibrate the RM-11 and
// RM-13 low-stack boundary subprocesses. The normal build values live in
// depth_budget_test.go; the race build overrides them in
// depth_budget_race_test.go, because the race detector inflates every
// stack frame and slows CPU-bound work, and the boundary subprocesses
// must stay valid under `go test -race`.

// deepSubprocess re-executes the test binary with one environment
// variable set, running only the named test as a subprocess role.
func deepSubprocess(t *testing.T, envVar, testName string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), deepSubprocessTimeout)
	defer cancel()
	cmd := exec.CommandContext(ctx, os.Args[0], "-test.run=^"+testName+"$")
	cmd.Env = append(os.Environ(), envVar+"=1")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("%s subprocess failed: %v\n%s", testName, err, out)
	}
}

// deepMustGenerate fails the subprocess unless the complete import
// generation over src succeeds and returns the generated bytes.
func deepMustGenerate(t *testing.T, src string) (goFile, body []byte) {
	t.Helper()
	goFile, body, err := GenerateImport("deep.intercall", []byte(src), nil, "imp")
	if err != nil {
		t.Fatalf("GenerateImport at the boundary: %v", err)
	}
	return goFile, body
}

// deepMustParseGo fails the subprocess unless the generated bytes parse
// as Go.
func deepMustParseGo(t *testing.T, goFile []byte) {
	t.Helper()
	if _, err := parser.ParseFile(token.NewFileSet(), "binding_gen.go", goFile, parser.AllErrors); err != nil {
		t.Fatalf("generated binding does not parse: %v", err)
	}
}

const deepImportSubprocessEnv = "INTERCALL_RM11_DEEP_IMPORT"

// TestDeepImportProjectionBoundary proves the complete import pipeline
// at the strict Go projection boundary under a lowered stack: pure
// list and record chains at exactly 4,096 occurrences run through
// model construction, the named-interleaved list/record chain at
// exactly 4,096 runs through complete generation and is
// byte-deterministic, the pure shapes at 4,097 are rejected before any
// emission with the stable physical diagnostic, and malformed deep
// input returns an ordinary error.
func TestDeepImportProjectionBoundary(t *testing.T) {
	if os.Getenv(deepImportSubprocessEnv) == "1" {
		runDeepImportBoundarySubprocess(t)
		return
	}
	deepSubprocess(t, deepImportSubprocessEnv, "TestDeepImportProjectionBoundary")
}

func runDeepImportBoundarySubprocess(t *testing.T) {
	debug.SetMaxStack(deepMaxStackBytes)

	// Pure list chain at exactly 4,096: 4,095 lists with the primitive
	// at depth 4,096. Parse, validate, attach, format, and MapImport —
	// override resolution, naming, and codec facts — run under the
	// lowered stack, and the deepest occurrence's Go projection
	// renders 4,095 slice levels.
	listSrc := importListSource(maxProjectionDepth - 1)
	f := mustParseValidate(t, listSrc)
	if _, err := MapImport(f, nil); err != nil {
		t.Fatalf("depth-4096 list model: %v", err)
	}
	m, err := MapImport(mustParseValidate(t, listSrc), nil)
	if err != nil {
		t.Fatalf("depth-4096 list model (second pass): %v", err)
	}
	gt := goTypeOf(f.Decls[0].(*syntax.TypeDecl).Type, m.names, m.types)
	if strings.Count(gt, "[]") != maxProjectionDepth-1 {
		t.Fatalf("deepest Go type renders %d slice levels, want %d", strings.Count(gt, "[]"), maxProjectionDepth-1)
	}

	// Pure record chain at exactly 4,096 through model construction.
	recSrc := importRecordSource(maxProjectionDepth - 1)
	if _, err := MapImport(mustParseValidate(t, recSrc), nil); err != nil {
		t.Fatalf("depth-4096 record model: %v", err)
	}

	// The pure list chain one occurrence deeper is rejected by the
	// preflight before any emission, with the stable physical
	// diagnostic at the exact position of the first over-limit
	// occurrence.
	badList := importListSource(maxProjectionDepth)
	_, _, err = GenerateImport("deep.intercall", []byte(badList), nil, "imp")
	e := depthErrorOf(t, err)
	wantSyntaxDepthPosition(t, e, badList, "uint8", 1)

	// The pure record chain at 4,097 is rejected the same way through
	// the complete pipeline, before any Go formatting of generated
	// content.
	_, _, err = GenerateImport("deep.intercall", []byte(importRecordSource(maxProjectionDepth)), nil, "imp")
	depthErrorOf(t, err)

	// The named-interleaved list/record chain at exactly 4,096 runs the
	// complete generation: 2,048 declarations put the deepest
	// occurrence at 4,096, the shared codec layer emits one linear
	// pair per declaration, and the output is byte-deterministic and
	// parses as Go.
	hybrid := importHybridSource(maxProjectionDepth / 2)
	goFile, body := deepMustGenerate(t, hybrid)
	deepMustParseGo(t, goFile)
	goFile2, body2 := deepMustGenerate(t, hybrid)
	if !bytes.Equal(goFile, goFile2) || !bytes.Equal(body, body2) {
		t.Fatal("boundary generation is not deterministic")
	}

	// Malformed deep input returns an ordinary validation error, never
	// a panic or a depth diagnostic.
	bad := "type t " + strings.Repeat("list ", maxProjectionDepth) + "missing;\n"
	_, _, err = GenerateImport("deep.intercall", []byte(bad), nil, "imp")
	wantErr(t, err, `unresolved type reference "missing"`)
}

const deepImportNamedSubprocessEnv = "INTERCALL_RM11_DEEP_IMPORT_NAMED"

// TestDeepImportNamedChainBoundary proves complete import generation of
// a named-type chain at exactly 4,096 occurrences under a lowered
// stack: 4,096 chained declarations generate byte-deterministically,
// and 4,097 are rejected before any emission with the stable physical
// diagnostic at the deepest primitive's exact position.
func TestDeepImportNamedChainBoundary(t *testing.T) {
	if os.Getenv(deepImportNamedSubprocessEnv) == "1" {
		runDeepImportNamedSubprocess(t)
		return
	}
	deepSubprocess(t, deepImportNamedSubprocessEnv, "TestDeepImportNamedChainBoundary")
}

func runDeepImportNamedSubprocess(t *testing.T) {
	debug.SetMaxStack(deepMaxStackBytes)

	src := importNamedChainSource(maxProjectionDepth)
	goFile, body := deepMustGenerate(t, src)
	deepMustParseGo(t, goFile)
	if got := strings.Count(string(body), "type t"); got != maxProjectionDepth {
		t.Fatalf("canonical body has %d type declarations, want %d", got, maxProjectionDepth)
	}
	goFile2, body2 := deepMustGenerate(t, src)
	if !bytes.Equal(goFile, goFile2) || !bytes.Equal(body, body2) {
		t.Fatal("named-chain generation at the boundary is not deterministic")
	}

	badSrc := importNamedChainSource(maxProjectionDepth + 1)
	_, _, err := GenerateImport("deep.intercall", []byte(badSrc), nil, "imp")
	e := depthErrorOf(t, err)
	if !strings.Contains(e.Msg, `type t4096 exceeds`) {
		t.Fatalf("message %q does not name the deepest declaration", e.Msg)
	}
	wantSyntaxDepthPosition(t, e, badSrc, "uint8", 1)
}

const deepExportSubprocessEnv = "INTERCALL_RM11_DEEP_EXPORT"

// TestDeepExportProjectionBoundary proves complete export generation
// of defined-type chains at the strict Go projection boundary under a
// lowered stack: slice-defined and alternating struct/slice chains
// with the deepest occurrence at exactly 4,096 generate
// byte-deterministically, and shapes beyond the ceiling are rejected
// before any recursive mapping or emission with the stable physical
// diagnostic, while recursive graphs keep their recursive-type
// diagnostic and non-recursed shapes keep their ordinary errors.
func TestDeepExportProjectionBoundary(t *testing.T) {
	if os.Getenv(deepExportSubprocessEnv) == "1" {
		runDeepExportBoundarySubprocess(t)
		return
	}
	deepSubprocess(t, deepExportSubprocessEnv, "TestDeepExportProjectionBoundary")
}

func runDeepExportBoundarySubprocess(t *testing.T) {
	debug.SetMaxStack(deepMaxStackBytes)

	// The defined-type chain at exactly 4,096: 2,048 slice
	// declarations with the parameter root put the deepest occurrence
	// at 4,096. The complete export generation — mapping, model,
	// codec, dispatch, and signature emission — runs under the lowered
	// stack and is byte-deterministic.
	model := exportOne(t, "example.com/synth", exportChainPackage(maxProjectionDepth/2))
	goFile, body, err := GenerateExport(model, "exp")
	if err != nil {
		t.Fatalf("depth-4096 defined chain generation: %v", err)
	}
	deepMustParseGo(t, goFile)
	goFile2, body2, err := GenerateExport(model, "exp")
	if err != nil {
		t.Fatalf("depth-4096 defined chain generation (second pass): %v", err)
	}
	if !bytes.Equal(goFile, goFile2) || !bytes.Equal(body, body2) {
		t.Fatal("defined-chain generation at the boundary is not deterministic")
	}

	// The alternating struct/slice chain at exactly 4,096.
	model = exportOne(t, "example.com/synth", exportHybridPackage(maxProjectionDepth/2))
	if _, _, err := GenerateExport(model, "exp"); err != nil {
		t.Fatalf("depth-4096 struct chain generation: %v", err)
	}

	// One more declaration exceeds the ceiling; the preflight rejects
	// the shape before any recursive mapping or emission.
	exportErr(t, "example.com/synth", exportChainPackage(maxProjectionDepth/2+1),
		"exceeds the strict Go projection depth limit of 4096 occurrences")

	// The pure slice parameter chain at exactly 4,097 is rejected the
	// same way.
	exportErr(t, "example.com/synth", exportSlicePackage(maxProjectionDepth),
		"exceeds the strict Go projection depth limit of 4096 occurrences")

	// A deep recursive ring keeps the existing recursive-type
	// diagnostic, and a chain through an unexported type keeps its
	// ordinary exportness error.
	var ring strings.Builder
	ring.WriteString("package synth\n\nimport \"context\"\n\n")
	for i := 0; i < 5000; i++ {
		fmt.Fprintf(&ring, "// @intercall type t%d\ntype T%d []T%d\n\n", i, i, (i+1)%5000)
	}
	ring.WriteString("// @intercall procedure p\nfunc P(ctx context.Context, x T0) error { return nil }\n")
	exportErr(t, "example.com/synth", ring.String(), "recursive type graph")

	var hidden strings.Builder
	hidden.WriteString("package synth\n\nimport \"context\"\n\n// @intercall type t0\ntype T0 t1\n\n")
	for i := 1; i < 5000; i++ {
		fmt.Fprintf(&hidden, "type t%d []t%d\n", i, i+1)
	}
	hidden.WriteString("type t5000 uint8\n")
	hidden.WriteString("// @intercall procedure p\nfunc P(ctx context.Context, x T0) error { return nil }\n")
	exportErr(t, "example.com/synth", hidden.String(), "must be exported")
}

const deepExportAliasSubprocessEnv = "INTERCALL_RM11_DEEP_EXPORT_ALIAS"

// TestDeepExportNamedAliasChainBoundary proves complete export
// generation of an alias chain at the strict Go projection boundary
// under a lowered stack: 4,095 aliases with the parameter root put the
// deepest occurrence at exactly 4,096 and generate
// byte-deterministically, and 4,096 aliases are rejected at 4,097
// before any emission.
func TestDeepExportNamedAliasChainBoundary(t *testing.T) {
	if os.Getenv(deepExportAliasSubprocessEnv) == "1" {
		runDeepExportAliasSubprocess(t)
		return
	}
	deepSubprocess(t, deepExportAliasSubprocessEnv, "TestDeepExportNamedAliasChainBoundary")
}

func runDeepExportAliasSubprocess(t *testing.T) {
	debug.SetMaxStack(deepMaxStackBytes)

	model := exportOne(t, "example.com/synth", exportAliasPackage(maxProjectionDepth-1))
	goFile, body, err := GenerateExport(model, "exp")
	if err != nil {
		t.Fatalf("depth-4096 alias chain generation: %v", err)
	}
	deepMustParseGo(t, goFile)
	goFile2, body2, err := GenerateExport(model, "exp")
	if err != nil {
		t.Fatalf("depth-4096 alias chain generation (second pass): %v", err)
	}
	if !bytes.Equal(goFile, goFile2) || !bytes.Equal(body, body2) {
		t.Fatal("alias-chain generation at the boundary is not deterministic")
	}

	exportErr(t, "example.com/synth", exportAliasPackage(maxProjectionDepth),
		"exceeds the strict Go projection depth limit of 4096 occurrences")
}

const deepMetadataSubprocessEnv = "INTERCALL_RM11_DEEP_METADATA"

// TestDeepMetadataNamedChainBoundary proves the trusted-metadata
// cross-row named chains of SPEC.md "Safe import and re-export
// metadata" at the strict Go projection boundary under a lowered
// stack: a reached cross-row chain at exactly 4,096 generates
// completely and byte-deterministically, a reached chain beyond the
// ceiling is rejected at its physical row position, and an unreached
// deep chain of a used generated file is rejected by the semantic
// preflight at the metadata constant's physical position before any
// row is projected.
func TestDeepMetadataNamedChainBoundary(t *testing.T) {
	if os.Getenv(deepMetadataSubprocessEnv) == "1" {
		runDeepMetadataSubprocess(t)
		return
	}
	deepSubprocess(t, deepMetadataSubprocessEnv, "TestDeepMetadataNamedChainBoundary")
}

// metadataBody renders the canonical decoded semantic body of the chain
// declarations, in the file order given.
func metadataBody(t *testing.T, decls []string) []byte {
	t.Helper()
	f, err := syntax.Parse("body.intercall", []byte(strings.Join(decls, "\n")+"\n"))
	if err != nil {
		t.Fatalf("parsing semantic body: %v", err)
	}
	syntax.AttachDocs(f)
	if err := syntax.Validate(f); err != nil {
		t.Fatalf("validating semantic body: %v", err)
	}
	return syntax.Format(f)
}

// metadataModuleFiles renders the two files of one synthetic module: a
// marked generated file whose rows form a cross-row chain of k
// declarations T0..T{k-1} (every row but the last a slice of the next,
// the last uint8, with exact machine lines) and a provider taking T0.
// The parameter root plus the chain puts the deepest physical
// occurrence at depth 2k.
func metadataModuleFiles(t *testing.T, k int) map[string]string {
	t.Helper()
	decls := []string{fmt.Sprintf("type t%d uint8;", k-1)}
	for i := k - 2; i >= 0; i-- {
		decls = append(decls, fmt.Sprintf("type t%d list t%d;", i, i+1))
	}
	body := metadataBody(t, decls)
	var goTypes strings.Builder
	for i := k - 1; i >= 0; i-- {
		if i == k-1 {
			fmt.Fprintf(&goTypes, "// @intercall type t%d\ntype T%d uint8\n\n", i, i)
		} else {
			fmt.Fprintf(&goTypes, "// @intercall type t%d\ntype T%d []T%d\n\n", i, i, i+1)
		}
	}
	genFile := intercallGeneratedMarker + "\n\npackage synth\n\n" + goTypes.String() +
		"const " + semanticConstantName + " = " + strconv.Quote(base64.RawURLEncoding.EncodeToString(body)) + "\n"
	provFile := "package synth\n\nimport \"context\"\n\n// @intercall procedure find\nfunc Find(ctx context.Context, x T0) error { return nil }\n"
	return map[string]string{"gen.go": genFile, "prov.go": provFile}
}

// metadataShallowModuleFiles renders a marked generated file whose
// shallow head row T0 is uint8 and whose remaining rows form a
// cross-row chain of k declarations T1..Tk: a one-field struct head
// followed by slices, with a final one-field struct. The provider
// takes T0, so the chain is not reached physically; the decoded
// semantic chain from t1 puts its deepest occurrence at depth 2k.
func metadataShallowModuleFiles(t *testing.T, k int) map[string]string {
	t.Helper()
	decls := []string{"type t0 uint8;"}
	decls = append(decls, fmt.Sprintf("type t%d record { f uint8; };", k))
	for i := k - 1; i >= 1; i-- {
		decls = append(decls, fmt.Sprintf("type t%d list t%d;", i, i+1))
	}
	body := metadataBody(t, decls)
	var goTypes strings.Builder
	goTypes.WriteString("// @intercall type t0\ntype T0 uint8\n\n")
	goTypes.WriteString("// @intercall type t" + strconv.Itoa(k) + "\ntype T" + strconv.Itoa(k) + " struct { F uint8 `intercall:\"f\"` }\n\n")
	for i := k - 1; i >= 1; i-- {
		fmt.Fprintf(&goTypes, "// @intercall type t%d\ntype T%d []T%d\n\n", i, i, i+1)
	}
	genFile := intercallGeneratedMarker + "\n\npackage synth\n\n" + goTypes.String() +
		"const " + semanticConstantName + " = " + strconv.Quote(base64.RawURLEncoding.EncodeToString(body)) + "\n"
	provFile := "package synth\n\nimport \"context\"\n\n// @intercall procedure find\nfunc Find(ctx context.Context, x T0) error { return nil }\n"
	return map[string]string{"gen.go": genFile, "prov.go": provFile}
}

// metadataModel runs the complete export model pass over one synthetic
// metadata module.
func metadataModel(t *testing.T, files map[string]string) (*ExportModel, error) {
	t.Helper()
	exp, providers := synthPkg(t, "example.com/synth", files)
	return MapExport(&DiscoverResult{Packages: []*ExplicitPackage{exp}, Providers: providers}, "")
}

func runDeepMetadataSubprocess(t *testing.T) {
	debug.SetMaxStack(deepMaxStackBytes)

	// The reached cross-row chain at exactly 4,096: 2,048 rows plus the
	// parameter root put the deepest physical occurrence at 4,096, and
	// the complete generation is byte-deterministic.
	model, err := metadataModel(t, metadataModuleFiles(t, maxProjectionDepth/2))
	if err != nil {
		t.Fatalf("depth-4096 metadata chain mapping: %v", err)
	}
	goFile, body, err := GenerateExport(model, "exp")
	if err != nil {
		t.Fatalf("depth-4096 metadata chain generation: %v", err)
	}
	deepMustParseGo(t, goFile)
	goFile2, body2, err := GenerateExport(model, "exp")
	if err != nil {
		t.Fatalf("depth-4096 metadata chain generation (second pass): %v", err)
	}
	if !bytes.Equal(goFile, goFile2) || !bytes.Equal(body, body2) {
		t.Fatal("metadata-chain generation at the boundary is not deterministic")
	}

	// One more row exceeds the ceiling; the preflight rejects the
	// reached shape before any recursive mapping or emission, with the
	// stable physical diagnostic.
	_, err = metadataModel(t, metadataModuleFiles(t, maxProjectionDepth/2+1))
	e := depthErrorOf(t, err)
	if !strings.Contains(e.Msg, `type "T2047" exceeds`) {
		t.Fatalf("message %q does not name the deepest row", e.Msg)
	}

	// An unreached cross-row chain of a used generated file sits at
	// exactly 4,096 semantically (2,048 chain rows) and recovers
	// completely.
	if _, err := metadataModel(t, metadataShallowModuleFiles(t, maxProjectionDepth/2)); err != nil {
		t.Fatalf("depth-4096 unreached semantic chain: %v", err)
	}

	// The same unreached chain one declaration deeper exceeds the
	// ceiling; the semantic preflight rejects it at the metadata
	// constant's physical position before any row is projected. The
	// first over-limit occurrence is the final record of the deepest
	// declaration's walk.
	_, err = metadataModel(t, metadataShallowModuleFiles(t, maxProjectionDepth/2+1))
	e = depthErrorOf(t, err)
	if !strings.Contains(e.Msg, "decoded _intercallSemantic: type t2049 exceeds") {
		t.Fatalf("message %q does not name the deepest semantic declaration", e.Msg)
	}
	if e.Filename == "" || e.Pos.Line == 0 {
		t.Fatalf("semantic depth diagnostic has no physical position: %+v", e)
	}
}
