package tool

import (
	_ "embed"
	"go/format"

	"github.com/cerasos/intercall/go/internal/syntax"
)

// codecFixtureSource is the exact interface of the compiled codec
// fixture. The fixture generation entry, determinism test, and fixture
// compile test all share these bytes, so the checked-in fixture file can
// never drift from the generator.
//
//go:embed testdata/fixture.intercall
var codecFixtureSource []byte

// fixturePackage is the package name of the compiled codec fixture.
const fixturePackage = "fixture"

// generateCodecFixture parses and validates the embedded fixture
// interface, builds the generation records, and renders the complete
// generated fixture file, formatted with go/format.
//
// The result is the byte-exact content of internal/tool/fixture/
// codec_gen.go. The fixture is tested as generated code: it must compile
// in its own package, and validation never rewrites the checked-in file.
func generateCodecFixture() ([]byte, error) {
	f, err := syntax.Parse("fixture.intercall", codecFixtureSource)
	if err != nil {
		return nil, err
	}
	if err := syntax.Validate(f); err != nil {
		return nil, err
	}
	m, err := BuildModel(f)
	if err != nil {
		return nil, err
	}
	return generateCodecFile(fixturePackage, m)
}

// generateCodecFile renders one complete generated codec file: the
// standard generated-file marker, package clause, the fixed standard
// library imports (the always-emitted primitive pairs use math and
// unicode/utf8), the codec support constants and sentinels, and the
// type declarations and codec pairs of the model.
func generateCodecFile(pkg string, m *Model) ([]byte, error) {
	var src source
	src.linef("// Code generated by intercall-go; DO NOT EDIT.")
	src.blank()
	src.linef("package %s", pkg)
	src.blank()
	src.linef("import (")
	src.open()
	src.linef(`"errors"`)
	src.linef(`"math"`)
	src.linef(`"unicode/utf8"`)
	src.close()
	src.linef(")")
	src.blank()
	emitCodecSupport(&src)
	e := newCodecEmitter(&src, m)
	e.emit()
	return format.Source(src.bytes())
}

// emitCodecSupport emits the shared codec constants and error sentinels:
// the native int maximum used by zero-width list decoding and the four
// distinct decoder failure values.
func emitCodecSupport(src *source) {
	src.linef("const %s = int(^uint(0) >> 1)", maxIntName)
	src.blank()
	src.linef("var (")
	src.open()
	src.linef(`%s = errors.New("intercall: wire length exceeds available bytes")`, errLongName)
	src.linef(`%s = errors.New("intercall: noncanonical NaN bit pattern")`, errNaNName)
	src.linef(`%s = errors.New("intercall: truncated wire value")`, errShortName)
	src.linef(`%s = errors.New("intercall: string is not valid UTF-8")`, errUTF8Name)
	src.close()
	src.linef(")")
	src.blank()
}
