package tool

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"go/parser"
	"go/token"
	"strconv"
	"strings"
	"testing"

	"github.com/cerasos/intercall/go/internal/syntax"
)

// This file tests the complete machine-table validation of SPEC.md
// "Safe import and re-export metadata": on first use of a table-backed
// type in a marked generated file, every machine directive and table
// row of the file is validated before any row is consumed. A row is a
// top-level type spec carrying exactly one valid type machine line,
// and the rows must be in bijection with the decoded semantic type
// declarations, while generated helper and exception types without a
// machine line are permitted. Every malformed, unknown, misplaced,
// duplicate, missing, extra, or structurally conflicting row —
// including an otherwise unreached row — fails at its exact physical
// position, directive-like text inside decoded documentation stays
// inert, and the scan terminates on adversarial tables without
// mutating the canonical metadata.
//
// The fixture bodies are rendered through the canonical interface
// formatter and the constants encode them byte-exact; every rejection
// variant mutates the Go side of the same fixture.

// tableGoTypes is the Go side of the table fixture: two rows with
// their machine lines, a helper type, and exception types — all
// without machine lines.
const tableGoTypes = "// Helper is a generated helper type without a machine line.\n" +
	"type Helper struct {\n" +
	"\tX string\n" +
	"}\n" +
	"\n" +
	"// @intercall type user_id\n" +
	"type UserID struct {\n" +
	"\tName string `intercall:\"name\"`\n" +
	"\tProfile struct {\n" +
	"\t\tBio []byte `intercall:\"bio\"`\n" +
	"\t} `intercall:\"profile\"`\n" +
	"}\n" +
	"\n" +
	"// @intercall type code\n" +
	"type Codes []uint8\n" +
	"\n" +
	"// Exc is a generated exception type without a machine line.\n" +
	"type Exc struct {\n" +
	"\tCode int32 `intercall:\"code\"`\n" +
	"}\n" +
	"\n" +
	"// ErrSentinel is a generated exception sentinel without a machine line.\n" +
	"var ErrSentinel error\n" +
	"\n"

// tableBody renders the canonical semantic body of the table fixture:
// the user_id record with a complete nested documentation tree, the
// code list type, and two exception declarations. The exception
// declarations are not type declarations and take no part in the
// row bijection.
func tableBody(t *testing.T) []byte {
	t.Helper()
	f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
    profile record {
        bio bytes;
    };
};
type code list uint8;
exception exc;
exception sentinel;
`))
	if err != nil {
		t.Fatalf("parsing body: %v", err)
	}
	userID := f.Decls[0].(*syntax.TypeDecl)
	userID.Doc = "the user type"
	rec := userID.Type.(*syntax.RecordType)
	rec.Fields[0].Doc = "the user identifier"
	rec.Fields[1].Doc = "nested profile"
	rec.Fields[1].Type.(*syntax.RecordType).Fields[0].Doc = "the bio"
	if err := syntax.Validate(f); err != nil {
		t.Fatalf("validating body: %v", err)
	}
	return syntax.Format(f)
}

// tableSource renders one marked table fixture from its Go type
// declarations and its canonical semantic body.
func tableSource(goTypes string, body []byte) []byte {
	return []byte("// Code generated by intercall-go; DO NOT EDIT.\n" +
		"\n" +
		"package imp\n" +
		"\n" +
		goTypes +
		"const _intercallSemantic = " + strconv.Quote(base64.RawURLEncoding.EncodeToString(body)) + "\n")
}

// wantRecoveryPosition fails unless RecoverSemantic rejects src with an
// *Error at the exact physical position of the nth occurrence of
// substr, with a message containing every listed substring.
//
// The document is built without the source-directive grammar (no
// Decls), so the rejection comes from the eager machine-table
// validation itself, exactly as it runs for unreached declarations of
// a dependency package's marked file.
func wantRecoveryPosition(t *testing.T, src []byte, substr string, nth int, contains ...string) {
	t.Helper()
	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, "imp.go", src, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parsing AST: %v", err)
	}
	doc := &Document{
		Name:               "imp.go",
		Size:               len(src),
		IntercallGenerated: true,
		src:                src,
		lines:              lineStarts(src),
		tok:                fset.File(af.Package),
	}
	_, err = RecoverSemantic(af, doc)
	te, ok := err.(*Error)
	if !ok {
		t.Fatalf("error = %T %v, want a *tool.Error", err, err)
	}
	want := positionN(t, src, substr, nth)
	if te.Filename != "imp.go" || te.Pos.Line != want.Line || te.Pos.Column != want.Column {
		t.Errorf("position = %s:%d:%d, want imp.go:%d:%d", te.Filename, te.Pos.Line, te.Pos.Column, want.Line, want.Column)
	}
	for _, s := range contains {
		if !strings.Contains(te.Msg, s) {
			t.Errorf("message = %q, want it to contain %q", te.Msg, s)
		}
	}
}

// positionN computes the one-based physical position of the nth
// occurrence of substr in src.
func positionN(t *testing.T, src []byte, substr string, nth int) Position {
	t.Helper()
	idx := -1
	for i := 0; i < nth; i++ {
		j := bytes.Index(src[idx+1:], []byte(substr))
		if j < 0 {
			t.Fatalf("occurrence %d of %q not found", i+1, substr)
		}
		idx += j + 1
	}
	line := 1 + bytes.Count(src[:idx], []byte("\n"))
	start := bytes.LastIndexByte(src[:idx], '\n') + 1
	return Position{Line: line, Column: idx - start + 1}
}

// TestSemanticMachineTableValidation covers the complete machine-table
// validation of a marked generated file: valid rows in bijection with
// the decoded semantic type declarations recover while helpers and
// exceptions without machine lines are permitted; every malformed,
// unknown, misplaced, duplicate, missing, extra, or structurally
// conflicting row fails at its exact physical position even when the
// mapper never reaches it; directive-like decoded documentation stays
// inert; and the scan terminates on adversarial tables while
// preserving the canonical metadata.
func TestSemanticMachineTableValidation(t *testing.T) {
	body := tableBody(t)

	t.Run("ValidTable", func(t *testing.T) {
		_, _, sem := recoverFixture(t, tableSource(tableGoTypes, body))
		if len(sem.table) != 2 || len(sem.reverse) != 2 {
			t.Fatalf("machine table = %v / %v, want 2 rows", sem.table, sem.reverse)
		}
		if sem.table["UserID"] != "user_id" || sem.table["Codes"] != "code" {
			t.Errorf("table = %v", sem.table)
		}
		if sem.specOf("user_id").Name.Name != "UserID" || sem.specOf("code").Name.Name != "Codes" {
			t.Errorf("reverse = %v", sem.reverse)
		}
		// Helpers, exception types, and sentinels without machine lines
		// are not rows and take no part in the bijection.
		if sem.specOf("exc") != nil || sem.specOf("sentinel") != nil {
			t.Errorf("exception declarations became rows: %v", sem.reverse)
		}
		for _, name := range []string{"Helper", "Exc", "ErrSentinel"} {
			if _, ok := sem.table[name]; ok {
				t.Errorf("%s is a helper without a machine line but became a row", name)
			}
		}
		// The recovered declaration carries the complete nested
		// documentation tree.
		td, err := sem.TypeDecl("user_id")
		if err != nil {
			t.Fatalf("TypeDecl: %v", err)
		}
		if td.Doc != "the user type" {
			t.Errorf("type doc = %q", td.Doc)
		}
		rec := td.Type.(*syntax.RecordType)
		if rec.Fields[0].Doc != "the user identifier" || rec.Fields[1].Doc != "nested profile" {
			t.Errorf("field docs = %q, %q", rec.Fields[0].Doc, rec.Fields[1].Doc)
		}
		// Validation never mutates the canonical metadata: the
		// recovered AST still renders byte-exact to the decoded body.
		if got := syntax.Format(sem.AST); !bytes.Equal(got, body) {
			t.Errorf("canonical metadata changed: %d bytes, want %d", len(got), len(body))
		}
	})

	t.Run("BareMachineLine", func(t *testing.T) {
		// The unreached code row carries a bare machine line: the
		// malformed line fails at its exact physical position.
		goTypes := strings.Replace(tableGoTypes, "// @intercall type code", "// @intercall type", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type\n", 1, "malformed machine line: expected the exact wire name")
	})

	t.Run("InvalidWireName", func(t *testing.T) {
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id", "// @intercall type bad-name", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type bad-name", 1, "malformed @intercall type directive: invalid wire name 'bad-name'")
	})

	t.Run("ReservedWireWord", func(t *testing.T) {
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id", "// @intercall type int8", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type int8", 1, "malformed @intercall type directive: invalid wire name 'int8'")
	})

	t.Run("TooManyOperands", func(t *testing.T) {
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id", "// @intercall type a b", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type a b", 1, "malformed @intercall type directive: expected at most one wire name")
	})

	t.Run("UnknownDirective", func(t *testing.T) {
		// An unknown @intercall directive on an unreached type is an
		// unknown machine line, not prose.
		goTypes := strings.Replace(tableGoTypes, "// @intercall type code", "// @intercall typo code", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall typo code", 1, "unknown @intercall directive '@intercall typo'")
	})

	t.Run("MisplacedOnFunction", func(t *testing.T) {
		// A type machine line on a function is misplaced even when the
		// function is never reached.
		extra := "// @intercall type hidden\nfunc helper() {}\n\n"
		src := tableSource(tableGoTypes+extra, body)
		wantRecoveryPosition(t, src, "@intercall type hidden", 1, "misplaced @intercall type directive: it applies only to a type declaration")
	})

	t.Run("MisplacedOnVariable", func(t *testing.T) {
		extra := "// @intercall type hidden\nvar V int\n\n"
		src := tableSource(tableGoTypes+extra, body)
		wantRecoveryPosition(t, src, "@intercall type hidden", 1, "misplaced @intercall type directive: it applies only to a type declaration")
	})

	t.Run("GroupContradiction", func(t *testing.T) {
		// A machine line in a multi-spec group doc applies to more than
		// one declared object and is contradictory.
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id\n"+
			"type UserID struct {\n"+
			"\tName string `intercall:\"name\"`\n"+
			"\tProfile struct {\n"+
			"\t\tBio []byte `intercall:\"bio\"`\n"+
			"\t} `intercall:\"profile\"`\n"+
			"}\n",
			"// @intercall type user_id\n"+
				"type (\n"+
				"\tUserID uint64\n"+
				"\tOtherID uint64\n"+
				")\n", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type user_id", 1, "contradictory @intercall type directive: a declaration group must contain exactly one specification")
	})

	t.Run("GroupContradictionOwnDocs", func(t *testing.T) {
		// A machine line in a multi-spec type group doc is
		// contradictory even when every spec has its own doc and no
		// spec inherits the group doc.
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id\n"+
			"type UserID struct {\n"+
			"\tName string `intercall:\"name\"`\n"+
			"\tProfile struct {\n"+
			"\t\tBio []byte `intercall:\"bio\"`\n"+
			"\t} `intercall:\"profile\"`\n"+
			"}\n",
			"// @intercall type user_id\n"+
				"type (\n"+
				"\t// Own doc of UserID.\n"+
				"\tUserID uint64\n"+
				"\t// Own doc of OtherID.\n"+
				"\tOtherID uint64\n"+
				")\n", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type user_id", 1, "contradictory @intercall type directive: a declaration group must contain exactly one specification")
	})

	t.Run("DuplicateMachineLine", func(t *testing.T) {
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id\n", "// @intercall type user_id\n// @intercall type user_id2\n", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type user_id2", 1, "duplicate @intercall type directive")
	})

	t.Run("DuplicateWireName", func(t *testing.T) {
		// A second row carrying the same wire name is a duplicate wire
		// name at the second row's machine line.
		extra := "// @intercall type user_id\n" +
			"type OtherID uint64\n\n"
		src := tableSource(tableGoTypes+extra, body)
		wantRecoveryPosition(t, src, "@intercall type user_id", 2,
			`generated types "UserID" and "OtherID" both carry machine line wire name "user_id"`)
	})

	t.Run("ExtraRow", func(t *testing.T) {
		// A valid machine line whose wire name has no decoded semantic
		// type declaration is an extra row.
		extra := "// @intercall type mystery\n" +
			"type Mystery uint64\n\n"
		src := tableSource(tableGoTypes+extra, body)
		wantRecoveryPosition(t, src, "@intercall type mystery", 1,
			`generated type "Mystery"`, `machine line names "mystery"`, `no type declaration named "mystery"`)
	})

	t.Run("MissingRow", func(t *testing.T) {
		// Removing the machine line of the code type leaves the decoded
		// semantic declaration without a row; the constant is the only
		// physical anchor of the missing row.
		goTypes := strings.Replace(tableGoTypes, "// @intercall type code\n", "", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "_intercallSemantic", 1, `semantic type declaration "code" has no machine line in the generated file`)
	})

	t.Run("UnreachedRowConflict", func(t *testing.T) {
		// The unreached extra row's Go type projects to a wire
		// structure that conflicts with its semantic declaration.
		f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
    profile record {
        bio bytes;
    };
};
type code list uint8;
type extra record {
    x string;
};
`))
		if err != nil {
			t.Fatalf("parsing body: %v", err)
		}
		if err := syntax.Validate(f); err != nil {
			t.Fatalf("validating body: %v", err)
		}
		body := syntax.Format(f)
		goTypes := tableGoTypes +
			"// @intercall type extra\n" +
			"type Extra struct {\n" +
			"\tX []byte `intercall:\"x\"`\n" +
			"}\n\n"
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "Extra struct", 1,
			`generated type "Extra"`, `conflicts with its semantic declaration "extra"`)
	})

	t.Run("UnreachedRowProjectionFailure", func(t *testing.T) {
		f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
    profile record {
        bio bytes;
    };
};
type code list uint8;
type extra record {
    x string;
};
`))
		if err != nil {
			t.Fatalf("parsing body: %v", err)
		}
		if err := syntax.Validate(f); err != nil {
			t.Fatalf("validating body: %v", err)
		}
		body := syntax.Format(f)
		goTypes := tableGoTypes +
			"// @intercall type extra\n" +
			"type Extra struct {\n" +
			"\tX string\n" +
			"}\n\n"
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "Extra struct", 1, `generated type "Extra"`, `field "X" has no intercall tag`)
	})

	t.Run("AliasRow", func(t *testing.T) {
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id\n"+
			"type UserID struct {\n"+
			"\tName string `intercall:\"name\"`\n"+
			"\tProfile struct {\n"+
			"\t\tBio []byte `intercall:\"bio\"`\n"+
			"\t} `intercall:\"profile\"`\n"+
			"}\n",
			"// @intercall type user_id\n"+
				"type UserID = uint64\n", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type user_id", 1,
			"contradictory @intercall type directive: a type alias is not an ordinary defined type")
	})

	t.Run("GenericRow", func(t *testing.T) {
		goTypes := strings.Replace(tableGoTypes, "// @intercall type user_id\n"+
			"type UserID struct {\n"+
			"\tName string `intercall:\"name\"`\n"+
			"\tProfile struct {\n"+
			"\t\tBio []byte `intercall:\"bio\"`\n"+
			"\t} `intercall:\"profile\"`\n"+
			"}\n",
			"// @intercall type user_id\n"+
				"type UserID[T any] uint64\n", 1)
		src := tableSource(goTypes, body)
		wantRecoveryPosition(t, src, "@intercall type user_id", 1,
			"contradictory @intercall type directive: a generic type is not an ordinary defined type")
	})

	t.Run("DecodedMachineLineTextIsInert", func(t *testing.T) {
		// Decoded documentation is assigned directly to AST slots:
		// text that is exactly shaped like a machine line survives
		// verbatim and never becomes a row.
		f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
    profile record {
        bio bytes;
    };
};
type code list uint8;
`))
		if err != nil {
			t.Fatalf("parsing body: %v", err)
		}
		f.Decls[0].(*syntax.TypeDecl).Doc = "@intercall type also_user_id"
		f.Decls[1].(*syntax.TypeDecl).Doc = "@intercall type code\n@intercall type also_code\nprose"
		if err := syntax.Validate(f); err != nil {
			t.Fatalf("validating body: %v", err)
		}
		docBody := syntax.Format(f)
		_, _, sem := recoverFixture(t, tableSource(tableGoTypes, docBody))
		if len(sem.table) != 2 {
			t.Fatalf("machine table = %v, want only the two real rows", sem.table)
		}
		if td, err := sem.TypeDecl("code"); err != nil {
			t.Fatalf("TypeDecl(code): %v", err)
		} else if td.Doc != "@intercall type code\n@intercall type also_code\nprose" {
			t.Errorf("code doc = %q", td.Doc)
		}
		if td, err := sem.TypeDecl("user_id"); err != nil {
			t.Fatalf("TypeDecl(user_id): %v", err)
		} else if td.Doc != "@intercall type also_user_id" {
			t.Errorf("user_id doc = %q", td.Doc)
		}
	})

	t.Run("UnreachedRowNamedReference", func(t *testing.T) {
		// An unreached row may reference another row by Go name: the
		// eager projection resolves the reference through the machine
		// table to its wire name and matches the semantic declaration.
		f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
    profile record {
        bio bytes;
    };
};
type code list uint8;
type extra record {
    user user_id;
};
`))
		if err != nil {
			t.Fatalf("parsing body: %v", err)
		}
		if err := syntax.Validate(f); err != nil {
			t.Fatalf("validating body: %v", err)
		}
		body := syntax.Format(f)
		goTypes := tableGoTypes +
			"// @intercall type extra\n" +
			"type Extra struct {\n" +
			"\tUser UserID `intercall:\"user\"`\n" +
			"}\n\n"
		_, _, sem := recoverFixture(t, tableSource(goTypes, body))
		if len(sem.table) != 3 {
			t.Fatalf("machine table has %d rows, want 3", len(sem.table))
		}
		if sem.table["Extra"] != "extra" {
			t.Errorf("table = %v", sem.table)
		}
	})

	t.Run("AdversarialTableTerminates", func(t *testing.T) {
		// A wide and deep table: 120 rows of 300-deep nested lists,
		// plus one malformed machine line at the very end. The scan
		// walks the complete table in source order, terminates with the
		// trailing malformed line's exact error, and never hangs.
		const rows, depth = 120, 300
		var bodyText strings.Builder
		var goTypes strings.Builder
		for i := 0; i < rows; i++ {
			fmt.Fprintf(&bodyText, "type t%d %suint8;\n", i, strings.Repeat("list ", depth))
			fmt.Fprintf(&goTypes, "// @intercall type t%d\n", i)
			fmt.Fprintf(&goTypes, "type T%d %suint8\n\n", i, strings.Repeat("[]", depth))
		}
		goTypes.WriteString("// @intercall type\n")
		goTypes.WriteString("type Broken uint64\n\n")
		f, err := syntax.Parse("body.intercall", []byte(bodyText.String()))
		if err != nil {
			t.Fatalf("parsing body: %v", err)
		}
		if err := syntax.Validate(f); err != nil {
			t.Fatalf("validating body: %v", err)
		}
		bigBody := syntax.Format(f)
		src := tableSource(goTypes.String(), bigBody)
		wantRecoveryPosition(t, src, "@intercall type\n", 1, "malformed machine line: expected the exact wire name")

		// The same table without the malformed tail recovers completely:
		// every row is in bijection and the canonical metadata is
		// preserved byte for byte.
		goTypes.Reset()
		for i := 0; i < rows; i++ {
			fmt.Fprintf(&goTypes, "// @intercall type t%d\n", i)
			fmt.Fprintf(&goTypes, "type T%d %suint8\n\n", i, strings.Repeat("[]", depth))
		}
		_, _, sem := recoverFixture(t, tableSource(goTypes.String(), bigBody))
		if len(sem.table) != rows {
			t.Fatalf("machine table has %d rows, want %d", len(sem.table), rows)
		}
		if got := syntax.Format(sem.AST); !bytes.Equal(got, bigBody) {
			t.Errorf("canonical metadata changed: %d bytes, want %d", len(got), len(bigBody))
		}
		if td, err := sem.TypeDecl(fmt.Sprintf("t%d", rows-1)); err != nil {
			t.Fatalf("TypeDecl of the last row: %v", err)
		} else if typeKeyOf(td.Type) == "" {
			t.Errorf("last row recovered with an empty structure")
		}
	})
}
