// Package provider is the shared provider fixture of the end-to-end
// integration tests: tagged providers, reachable ordinary types, and
// application exceptions for the generated export binding in the parent
// fixtures/e2eexport package. Both peers of every test connection run
// the same provider package: the generated dispatch is stateless and
// every provider is goroutine-safe, so the single export binding serves
// any number of connections concurrently, including both ends of one
// connection.
//
// binding_gen.go in fixtures/e2eexport and the owned interface in
// fixtures/interface are generated byte-for-byte from this package
// through the complete intercall-go pipeline; the integration tests
// regenerate both into temporary directories and verify the checked-in
// files never drift.
package provider

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/cerasos/intercall/go/internal/integration/fixtures/e2eimport"
)

// UserID is a user identifier.
// @intercall type user_id
type UserID uint64

// CustomerID is a user identifier one alias chain deep.
// @intercall type customer_id
type CustomerID UserID

// Name is a single name string.
// @intercall type name
type Name string

// Names is an ordered list of names.
// @intercall type names
type Names []string

// Point is a two-dimensional point.
// @intercall type point
type Point struct {
	// Horizontal coordinate.
	X float64
	// Vertical coordinate.
	Y float64
}

// Pixel is one image pixel.
// @intercall type pixel
type Pixel struct {
	// Red channel.
	Red uint8
	// Green channel.
	Green uint8
	// Blue channel.
	Blue uint8
}

// Matrix is a nested list of int32 rows.
// @intercall type matrix
type Matrix [][]int32

// Blob is a raw byte payload.
// @intercall type blob
type Blob []byte

// Empty is the zero-width empty record.
// @intercall type empty
type Empty struct{}

// ErrDenied is the denied sentinel exception.
// @intercall exception denied
var ErrDenied = errors.New("denied")

// Failed carries a failure code and message.
// @intercall exception failed
type Failed struct {
	// The failure code.
	Code int32
	// The failure message.
	Message string
}

// Error implements error for Failed.
func (f *Failed) Error() string { return "failed" }

// Blank is a zero-field payload exception.
// @intercall exception blank
type Blank struct{}

// Error implements error for Blank.
func (b *Blank) Error() string { return "blank" }

// PointFailed carries the point that failed validation.
// @intercall exception point_failed
type PointFailed struct {
	// The rejected point.
	Point Point
}

// Error implements error for PointFailed.
func (p *PointFailed) Error() string { return "point_failed" }

// Ping checks liveness.
// @intercall procedure ping
func Ping(ctx context.Context) error { return nil }

// Echo echoes its input, with mode values that exercise the generated
// exception mapping and failure fallbacks: "denied" returns the denied
// sentinel, "failed" a failed payload, "blank" a zero-field payload,
// "point_failed" a payload holding a named type, "panic" panics,
// "typed_nil" returns a typed-nil payload pointer, "wrapped" returns a
// wrapped error no direct comparison matches, and "bad_utf8" returns a
// success value the encoder rejects. Every mode except the declared
// exceptions selects internal_exception.
// @intercall procedure echo
// @param value The value to echo, or a mode selector.
// @return The unchanged input.
func Echo(ctx context.Context, value string) (string, error) {
	switch value {
	case "denied":
		return "", ErrDenied
	case "failed":
		return "", &Failed{Code: 7, Message: "boom"}
	case "blank":
		return "", &Blank{}
	case "point_failed":
		return "", &PointFailed{Point: Point{X: 1.5, Y: -2.5}}
	case "panic":
		panic("provider panic")
	case "typed_nil":
		var f *Failed
		return "", f
	case "wrapped":
		return "", fmt.Errorf("wrapped: %w", ErrDenied)
	case "bad_utf8":
		return "bad\xff", nil
	}
	return value, nil
}

// Add sums its eight integer arguments.
// @intercall procedure add
func Add(ctx context.Context, a int8, b int16, c int32, d int64, e uint8, f uint16, g uint32, h uint64) (int64, error) {
	return int64(a) + int64(b) + int64(c) + d + int64(e) + int64(f) + int64(g) + int64(h), nil
}

// Measure returns the sum of its float arguments.
// @intercall procedure measure
func Measure(ctx context.Context, x float32, y float64) (float64, error) {
	return float64(x) + y, nil
}

// Sample echoes its byte payload.
// @intercall procedure sample
func Sample(ctx context.Context, data []byte, channel uint8) ([]byte, error) {
	return append([]byte(nil), data...), nil
}

// Wave counts its samples.
// @intercall procedure wave
func Wave(ctx context.Context, samples []uint8) (uint32, error) {
	return uint32(len(samples)), nil
}

// Scale scales a point by a factor.
// @intercall procedure scale
func Scale(ctx context.Context, factor float64, point Point) (Point, error) {
	return Point{X: factor * point.X, Y: factor * point.Y}, nil
}

// Render echoes its pixel list.
// @intercall procedure render
func Render(ctx context.Context, pixels []Pixel, depth uint16) ([]Pixel, error) {
	out := make([]Pixel, len(pixels))
	copy(out, pixels)
	return out, nil
}

// Find returns the tags with the given prefix.
// @intercall procedure find
func Find(ctx context.Context, prefix string, tags []Name) (Names, error) {
	var out Names
	for _, n := range tags {
		if strings.HasPrefix(string(n), prefix) {
			out = append(out, string(n))
		}
	}
	return out, nil
}

// Account resolves one customer account id to its user id.
// @intercall procedure account
// @param id The customer account id.
// @return The user id.
func Account(ctx context.Context, id CustomerID) (UserID, error) {
	return UserID(id), nil
}

// Fetch returns the blob stored for one user.
// @intercall procedure fetch
// @param id The user id.
// @return The user's blob.
func Fetch(ctx context.Context, id UserID) (Blob, error) {
	return Blob(fmt.Sprintf("blob-%d", id)), nil
}

// Transform copies its matrix rows.
// @intercall procedure transform
func Transform(ctx context.Context, rows Matrix) (Matrix, error) {
	out := make(Matrix, len(rows))
	for i, r := range rows {
		out[i] = append([]int32(nil), r...)
	}
	return out, nil
}

// Paint composes a rectangle from an origin and a color.
// @intercall procedure paint
// @param origin The rectangle origin.
// @param color The rectangle color.
// @return The rectangle size.
func Paint(ctx context.Context, origin struct {
	X int32
	Y int32
}, color struct {
	Red   uint8
	Green uint8
	Blue  uint8
	Alpha uint8
}) (struct {
	Width  uint32
	Height uint32
}, error) {
	return struct {
		Width  uint32
		Height uint32
	}{
		Width:  uint32(origin.X + int32(color.Alpha)),
		Height: uint32(origin.Y + int32(color.Blue)),
	}, nil
}

// Locate finds a box and returns its corner and scaled area.
// @intercall procedure locate
// @param box The box to locate.
// @return The box corner and area.
func Locate(ctx context.Context, box struct {
	Corner struct {
		Inner struct {
			X int32
			Y int32
		}
		Label string
	}
	Tag uint16
}) (struct {
	Corner Point
	Area   uint64
}, error) {
	return struct {
		Corner Point
		Area   uint64
	}{
		Corner: Point{X: float64(box.Corner.Inner.X), Y: float64(box.Corner.Inner.Y)},
		Area:   uint64(box.Tag) * 10,
	}, nil
}

// Grid sums the values of its rows.
// @intercall procedure grid
// @param rows The rows to sum.
// @return The sum of the row values.
func Grid(ctx context.Context, rows []struct {
	Origin struct {
		X int16
		Y int16
	}
	Value int64
}) (uint64, error) {
	var sum int64
	for _, r := range rows {
		sum += r.Value
	}
	return uint64(sum), nil
}

// Blanks returns a list of count empty records.
// @intercall procedure blanks
// @param count The number of empty records.
// @return The empty records.
func Blanks(ctx context.Context, count uint64) ([]Empty, error) {
	return make([]Empty, count), nil
}

// Tiny returns a fixed marker.
// @intercall procedure tiny
// @param tag An empty marker parameter.
// @return The fixed marker value.
func Tiny(ctx context.Context, tag Empty) (uint32, error) { return 7, nil }

// Stamp returns an empty record.
// @intercall procedure stamp
// @return An empty record.
func Stamp(ctx context.Context) (Empty, error) { return Empty{}, nil }

// Notify records a message for the tests to observe.
// @intercall procedure notify
// @param message The message to record.
func Notify(ctx context.Context, message string) error {
	notifyMu.Lock()
	notifyMessages = append(notifyMessages, message)
	notifyMu.Unlock()
	return nil
}

// Outer performs one nested call into the peer per unit of depth:
// Outer(0) is 1 and Outer(n) is Inner(n-1) + 1, so the request hops
// from this peer to the opposing peer and back once per level.
// @intercall procedure outer
// @param n The nesting depth.
// @return The nested result.
func Outer(ctx context.Context, n uint64) (uint64, error) {
	if n == 0 {
		return 1, nil
	}
	v, err := e2eimport.Inner(ctx, n-1)
	if err != nil {
		return 0, err
	}
	return v + 1, nil
}

// Inner performs one nested call into the peer per unit of depth:
// Inner(0) is 1 and Inner(n) is Outer(n-1) + 1, so the request hops
// from this peer to the opposing peer and back once per level.
// @intercall procedure inner
// @param n The nesting depth.
// @return The nested result.
func Inner(ctx context.Context, n uint64) (uint64, error) {
	if n == 0 {
		return 1, nil
	}
	v, err := e2eimport.Outer(ctx, n-1)
	if err != nil {
		return 0, err
	}
	return v + 1, nil
}

// Wait blocks until the wait id is released or the handler context is
// canceled, then returns the id.
// @intercall procedure wait
// @param id The wait id.
// @return The released wait id.
func Wait(ctx context.Context, id uint32) (uint32, error) {
	waitMu.Lock()
	ch := waitChans[id]
	if ch == nil {
		ch = make(chan struct{})
		waitChans[id] = ch
	}
	waitMu.Unlock()
	select {
	case <-ch:
		return id, nil
	case <-ctx.Done():
		return 0, ctx.Err()
	}
}

// Test-side synchronization: the wait registry and the notification
// recorder. Both ends of every test connection share this package, so
// every registry and recorder is process-wide and lock-protected.

var (
	waitMu         sync.Mutex
	waitChans      = map[uint32]chan struct{}{}
	notifyMu       sync.Mutex
	notifyMessages []string
)

// ReleaseWait releases one blocked Wait, if any. A second release for
// the same id is a no-op.
func ReleaseWait(id uint32) {
	waitMu.Lock()
	ch := waitChans[id]
	delete(waitChans, id)
	waitMu.Unlock()
	if ch != nil {
		close(ch)
	}
}

// IsWaiting reports whether a Wait with the given id has registered its
// release channel, meaning its handler is blocked or about to block.
func IsWaiting(id uint32) bool {
	waitMu.Lock()
	defer waitMu.Unlock()
	_, ok := waitChans[id]
	return ok
}

// Messages returns a copy of the recorded notifications.
func Messages() []string {
	notifyMu.Lock()
	defer notifyMu.Unlock()
	return append([]string(nil), notifyMessages...)
}

// ResetMessages clears the recorded notifications.
func ResetMessages() {
	notifyMu.Lock()
	notifyMessages = nil
	notifyMu.Unlock()
}
