package main

import (
	"bytes"
	"encoding/base64"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/cerasos/intercall/go/internal/syntax"
	"github.com/cerasos/intercall/go/internal/tool"
)

// This file black-box tests the intercall-go command: the exact import
// and export grammar, the repeatable flags, the package defaults, the
// ordered validation and mutation phases, the artifact writer
// integration, and the safe replacement and repair rules of SPEC.md
// "Commands" and "One-file ownership and safe replacement". Every test
// operates only in temporary directories; export tests run against
// temporary module fixtures with a hermetic Go environment. Tests are
// sequential because the command uses the process working directory
// and environment.

// runCLI executes the command and returns its exit status, stdout, and
// stderr.
func runCLI(t *testing.T, args ...string) (int, string, string) {
	t.Helper()
	var stdout, stderr bytes.Buffer
	status := run(args, &stdout, &stderr)
	return status, stdout.String(), stderr.String()
}

// writeModule writes one map of relative paths to a fresh temporary
// directory and returns it.
func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("creating fixture directory: %v", err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("writing fixture file: %v", err)
		}
	}
	return dir
}

// cliEnv makes one export invocation hermetic: the explicit toolchain
// on PATH, ambient GOFLAGS and GOENV cleared, GOWORK off, and the
// process working directory set to the fixture module root.
func cliEnv(t *testing.T, dir string) {
	t.Helper()
	t.Setenv("GOFLAGS", "")
	t.Setenv("GOENV", "off")
	t.Setenv("GOWORK", "off")
	t.Setenv("PATH", "/usr/local/go/bin"+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Chdir(dir)
}

// canonicalBody parses, documents, validates, and formats one interface
// source to its byte-exact canonical body, mirroring the import and
// export pipeline.
func canonicalBody(t *testing.T, src []byte) []byte {
	t.Helper()
	f, err := syntax.Parse("body.intercall", src)
	if err != nil {
		t.Fatalf("parsing interface: %v", err)
	}
	syntax.AttachDocs(f)
	if err := syntax.Validate(f); err != nil {
		t.Fatalf("validating interface: %v", err)
	}
	return syntax.Format(f)
}

// bindingStamp returns the artifact stamp of one generated binding's
// ownership line, or "" when the line is absent.
func bindingStamp(t *testing.T, binding []byte) string {
	t.Helper()
	lines := strings.Split(string(binding), "\n")
	for _, line := range lines {
		if rest, ok := strings.CutPrefix(line, "// intercall-go binding: "); ok {
			_, stamp, ok := strings.Cut(rest, " sha256:")
			if !ok {
				t.Fatalf("binding ownership line has no stamp: %q", line)
			}
			return stamp
		}
	}
	t.Fatal("binding has no ownership line")
	return ""
}

// interfaceStamp returns the artifact stamp of one owned interface
// file's marker line.
func interfaceStamp(t *testing.T, src []byte) string {
	t.Helper()
	line, _, ok := strings.Cut(string(src), "\n")
	if !ok {
		t.Fatalf("interface file has no marker line: %q", src)
	}
	prefix := "/* Code generated by intercall-go; artifact sha256:"
	suffix := "; DO NOT EDIT. */"
	if !strings.HasPrefix(line, prefix) || !strings.HasSuffix(line, suffix) {
		t.Fatalf("interface file has no exact marker line: %q", line)
	}
	return line[len(prefix) : len(line)-len(suffix)]
}

// interfaceBody returns the canonical interface body of one owned
// interface file: the bytes after the marker line and its blank line.
func interfaceBody(t *testing.T, src []byte) []byte {
	t.Helper()
	_, rest, ok := strings.Cut(string(src), "\n")
	if !ok || !strings.HasPrefix(rest, "\n") {
		t.Fatalf("interface file has no blank line after the marker: %q", src)
	}
	return []byte(rest[1:])
}

// semanticBody extracts and decodes the _intercallSemantic constant of
// one generated import binding.
func semanticBody(t *testing.T, binding []byte) []byte {
	t.Helper()
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "binding_gen.go", binding, parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parsing generated binding: %v", err)
	}
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) != 1 || vs.Names[0].Name != "_intercallSemantic" || len(vs.Values) != 1 {
				continue
			}
			lit, ok := vs.Values[0].(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				t.Fatal("the semantic constant is not a string literal")
			}
			text, err := strconv.Unquote(lit.Value)
			if err != nil {
				t.Fatalf("unquoting the semantic constant: %v", err)
			}
			body, err := base64.RawURLEncoding.DecodeString(text)
			if err != nil {
				t.Fatalf("decoding the semantic constant: %v", err)
			}
			return body
		}
	}
	t.Fatal("generated binding has no _intercallSemantic constant")
	return nil
}

// importFixture writes one interface file and returns its path.
func importFixture(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

// exportFixture writes the export fixture module: a provider package
// with three tagged procedures and an existing interface-target
// directory. The output directory is left fresh: the command creates
// --out if necessary (SPEC.md "One-file ownership and safe
// replacement"), so the fixture exercises the first-run export flow.
// Tests that need an existing owned output package seed one with
// seedExportBinding, which also models regeneration over a checked-in
// output package.
func exportFixture(t *testing.T) string {
	t.Helper()
	root := writeModule(t, map[string]string{
		"go.mod": "module example.com/cli\n\ngo 1.26.5\n",
		"prov/prov.go": `// Package prov is the CLI export fixture provider.
package prov

import "context"

// Greet greets a user.
// @intercall procedure greet
// @intercall param name user
// @param name the user to greet
// @return the greeting
func Greet(ctx context.Context, name string) (string, error) {
	return "hi " + name, nil
}

// Ping checks liveness.
// @intercall procedure ping
func Ping(ctx context.Context) error { return nil }

// Status reports readiness.
// @intercall procedure status
func Status(ctx context.Context) error { return nil }
`,
	})
	if err := os.MkdirAll(filepath.Join(root, "interfaces"), 0o755); err != nil {
		t.Fatal(err)
	}
	return root
}

// seedExportBinding writes one owned export binding and its owned
// interface into a fresh output directory with package "gen", so the
// directory resolves to an importable package and the package default
// of an existing owned binding applies. It models regeneration over an
// already-owned output package, like a checked-in binding.
func seedExportBinding(t *testing.T, out, intf string) {
	t.Helper()
	if err := tool.WriteArtifacts(tool.WriteConfig{
		Mode:          tool.ExportMode,
		OutDir:        out,
		Package:       "gen",
		InterfacePath: intf,
		GoFile:        []byte("package gen\n\nconst seed = 1\n"),
		InterfaceBody: []byte("exception seed;\n"),
	}); err != nil {
		t.Fatalf("seeding the export output directory: %v", err)
	}
}

// readFile reads one fixture file or fails the test.
func readFile(t *testing.T, path string) []byte {
	t.Helper()
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return src
}

// TestCLI black-box tests the command surface: help and usage, exact
// operand counts, required and distinct targets, the repeatable
// include/exclude/go-name flags, package validation and defaults,
// validation failures that create nothing, ownership failures that
// create and replace nothing, success, interrupted export repair, and
// deterministic repeated invocation.
func TestCLI(t *testing.T) {
	t.Run("HelpAndUsage", func(t *testing.T) {
		status, stdout, stderr := runCLI(t, "--help")
		if status != 0 {
			t.Errorf("--help status = %d, want 0", status)
		}
		for _, want := range []string{"intercall-go export", "intercall-go import", "--go-name", "--include", "--exclude", "--package", "--interface", "--out"} {
			if !strings.Contains(stdout, want) {
				t.Errorf("--help output misses %q", want)
			}
		}
		if stderr != "" {
			t.Errorf("--help wrote to stderr: %q", stderr)
		}

		status, stdout, stderr = runCLI(t)
		if status != 1 {
			t.Errorf("bare status = %d, want 1", status)
		}
		if !strings.Contains(stderr, "Usage:") {
			t.Errorf("bare invocation does not print usage to stderr: %q", stderr)
		}
		if stdout != "" {
			t.Errorf("bare invocation wrote to stdout: %q", stdout)
		}
	})

	t.Run("UnknownCommand", func(t *testing.T) {
		status, _, stderr := runCLI(t, "frobnicate")
		if status != 1 {
			t.Errorf("status = %d, want 1", status)
		}
		want := "frobnicate:1:1: unknown command \"frobnicate\"; expected export or import"
		if !strings.Contains(stderr, want) {
			t.Errorf("stderr = %q, want it to contain %q", stderr, want)
		}
	})

	t.Run("ImportSuccess", func(t *testing.T) {
		root := t.TempDir()
		file := importFixture(t, root, "echo.intercall", "/* The echo interface. */\nprocedure echo {\n    value string;\n} string;\n")
		status, stdout, stderr := runCLI(t, "import", "--out", filepath.Join(root, "gen"), "--package", "gen", "--go-name", "procedure:echo=Echo", file)
		if status != 0 {
			t.Fatalf("import status = %d, stderr = %q", status, stderr)
		}
		if stdout != "" || stderr != "" {
			t.Errorf("successful import printed: stdout %q stderr %q", stdout, stderr)
		}
		binding := readFile(t, filepath.Join(root, "gen", "binding_gen.go"))
		lines := strings.Split(string(binding), "\n")
		if len(lines) < 2 || lines[0] != "// Code generated by intercall-go; DO NOT EDIT." {
			t.Errorf("binding first line = %q", lines[0])
		}
		stamp := bindingStamp(t, binding)
		if stamp != tool.ArtifactStamp(canonicalBody(t, readFile(t, file))) {
			t.Error("binding stamp is not the digest of the canonical interface body")
		}
		if !strings.HasPrefix(lines[1], "// intercall-go binding: import sha256:") {
			t.Errorf("binding ownership line = %q", lines[1])
		}
		if !strings.Contains(string(binding), "package gen") {
			t.Error("binding does not declare the resolved package gen")
		}
		// The --go-name override renamed the generated caller.
		if !strings.Contains(string(binding), "func Echo(") || !strings.Contains(string(binding), "value string) (string, error)") {
			t.Error("the generated caller does not use the --go-name override")
		}
		// The canonical body is embedded as the semantic metadata.
		if body := semanticBody(t, binding); !bytes.Equal(body, canonicalBody(t, readFile(t, file))) {
			t.Error("the _intercallSemantic constant is not the canonical body")
		}
	})

	t.Run("ImportExactInputBytes", func(t *testing.T) {
		// The command reads the exact input bytes: a CRLF fixture with
		// a trailing comment formats to the same canonical body as the
		// exact bytes it was parsed from, and the stamp and semantic
		// constant both derive from that body.
		root := t.TempDir()
		content := "/* docs */\r\nprocedure echo {\r\n    value string;\r\n} string;\r\n"
		file := importFixture(t, root, "crlf.intercall", content)
		status, _, stderr := runCLI(t, "import", "--out", filepath.Join(root, "gen"), file)
		if status != 0 {
			t.Fatalf("import status = %d, stderr = %q", status, stderr)
		}
		binding := readFile(t, filepath.Join(root, "gen", "binding_gen.go"))
		body := canonicalBody(t, []byte(content))
		if stamp := bindingStamp(t, binding); stamp != tool.ArtifactStamp(body) {
			t.Errorf("binding stamp = %q, want the digest of the canonical body %q", stamp, tool.ArtifactStamp(body))
		}
		if got := semanticBody(t, binding); !bytes.Equal(got, body) {
			t.Error("semantic constant differs from the canonical body")
		}
	})

	t.Run("ImportFreshOutDirPackageDefault", func(t *testing.T) {
		// A new output uses the output directory's base name.
		root := t.TempDir()
		file := importFixture(t, root, "echo.intercall", "procedure echo {};\n")
		status, _, stderr := runCLI(t, "import", "--out", filepath.Join(root, "newpkg"), file)
		if status != 0 {
			t.Fatalf("import status = %d, stderr = %q", status, stderr)
		}
		binding := readFile(t, filepath.Join(root, "newpkg", "binding_gen.go"))
		if !strings.Contains(string(binding), "package newpkg\n") {
			t.Errorf("binding does not declare package newpkg:\n%s", binding)
		}
	})

	t.Run("ImportOwnedPackageConsistency", func(t *testing.T) {
		root := t.TempDir()
		file := importFixture(t, root, "echo.intercall", "procedure echo {};\n")
		out := filepath.Join(root, "gen")
		if status, _, stderr := runCLI(t, "import", "--out", out, "--package", "gen", file); status != 0 {
			t.Fatalf("first import status = %d, stderr = %q", status, stderr)
		}
		// An explicit name must equal the existing owned binding's
		// package name.
		status, _, stderr := runCLI(t, "import", "--out", out, "--package", "other", file)
		if status != 1 {
			t.Errorf("conflicting package status = %d, want 1", status)
		}
		if !strings.Contains(stderr, "must equal an existing owned binding's package name") {
			t.Errorf("stderr = %q, want the package-consistency error", stderr)
		}
		// Without an explicit name the owned binding's package clause
		// wins, and the identical invocation replaces nothing.
		binding := filepath.Join(out, "binding_gen.go")
		before, err := os.Stat(binding)
		if err != nil {
			t.Fatal(err)
		}
		status, _, stderr = runCLI(t, "import", "--out", out, file)
		if status != 0 {
			t.Fatalf("defaulted import status = %d, stderr = %q", status, stderr)
		}
		after, err := os.Stat(binding)
		if err != nil {
			t.Fatal(err)
		}
		if !os.SameFile(before, after) {
			t.Error("identical repeated import replaced the binding")
		}
	})

	t.Run("ImportValidationFailureCreatesNothing", func(t *testing.T) {
		root := t.TempDir()
		file := importFixture(t, root, "broken.intercall", "procedure broken {")
		out := filepath.Join(root, "out")
		status, _, stderr := runCLI(t, "import", "--out", out, file)
		if status != 1 {
			t.Errorf("status = %d, want 1", status)
		}
		if !strings.Contains(stderr, "broken.intercall:1:19:") {
			t.Errorf("stderr = %q, want the EOF diagnostic at offset len(input)", stderr)
		}
		if _, err := os.Stat(out); !os.IsNotExist(err) {
			t.Error("validation failure created the output directory")
		}
	})

	t.Run("ImportUnownedBindingRejected", func(t *testing.T) {
		root := t.TempDir()
		file := importFixture(t, root, "echo.intercall", "procedure echo {};\n")
		out := filepath.Join(root, "out")
		if err := os.MkdirAll(out, 0o755); err != nil {
			t.Fatal(err)
		}
		hand := filepath.Join(out, "binding_gen.go")
		if err := os.WriteFile(hand, []byte("package gen\n\nvar x = 1\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		status, _, stderr := runCLI(t, "import", "--out", out, file)
		if status != 1 {
			t.Errorf("status = %d, want 1", status)
		}
		if !strings.Contains(stderr, "not replaceable") {
			t.Errorf("stderr = %q, want the ownership error", stderr)
		}
		if got := readFile(t, hand); string(got) != "package gen\n\nvar x = 1\n" {
			t.Error("the unowned binding was modified")
		}
		if strings.Contains(stderr, ".tmp-") {
			t.Errorf("stderr reports a staging path: %q", stderr)
		}
	})

	t.Run("ImportOperandCount", func(t *testing.T) {
		root := t.TempDir()
		status, _, stderr := runCLI(t, "import", "--out", root)
		if status != 1 || !strings.Contains(stderr, "import requires exactly one interface file, got 0 operands") {
			t.Errorf("zero operands: status %d, stderr %q", status, stderr)
		}
		file := importFixture(t, root, "echo.intercall", "procedure echo {};\n")
		status, _, stderr = runCLI(t, "import", "--out", root, file, file)
		if status != 1 || !strings.Contains(stderr, "import requires exactly one interface file, got 2 operands") {
			t.Errorf("two operands: status %d, stderr %q", status, stderr)
		}
	})

	t.Run("ImportStdinNotSupported", func(t *testing.T) {
		root := t.TempDir()
		status, _, stderr := runCLI(t, "import", "--out", filepath.Join(root, "out"), "-")
		if status != 1 {
			t.Errorf("status = %d, want 1", status)
		}
		if !strings.Contains(stderr, "reading -:") {
			t.Errorf("stderr = %q, want a read error for the - operand", stderr)
		}
		if strings.Contains(stderr, "stdin") {
			t.Errorf("stderr reads stdin: %q", stderr)
		}
	})

	t.Run("ImportRepeatableGoName", func(t *testing.T) {
		root := t.TempDir()
		file := importFixture(t, root, "point.intercall", "type point record {\n    x int32;\n    y int32;\n};\nprocedure echo {\n    value point;\n} point;\n")
		status, _, stderr := runCLI(t, "import", "--out", filepath.Join(root, "gen"), "--package", "gen",
			"--go-name", "type:point=Point2", "--go-name", "type:point/field:x=XCoord", file)
		if status != 0 {
			t.Fatalf("import status = %d, stderr = %q", status, stderr)
		}
		binding := readFile(t, filepath.Join(root, "gen", "binding_gen.go"))
		for _, want := range []string{"type Point2 struct", "XCoord int32"} {
			if !strings.Contains(string(binding), want) {
				t.Errorf("generated binding misses %q", want)
			}
		}
	})

	t.Run("ExportSuccess", func(t *testing.T) {
		root := exportFixture(t)
		cliEnv(t, root)
		out := filepath.Join(root, "out")
		intf := filepath.Join(root, "interfaces", "api.intercall")
		// The first run is the SPEC-correct first-run flow: the output
		// directory is fresh, discovery accepts it, and the write
		// creates --out if necessary.
		if _, err := os.Stat(out); !os.IsNotExist(err) {
			t.Fatal("the output directory must be fresh for the first-run flow")
		}
		status, stdout, stderr := runCLI(t, "export", "--out", out, "--interface", intf, "--package", "gen", "./prov")
		if status != 0 {
			t.Fatalf("export status = %d, stderr = %q", status, stderr)
		}
		if stdout != "" || stderr != "" {
			t.Errorf("successful export printed: stdout %q stderr %q", stdout, stderr)
		}
		if info, err := os.Stat(out); err != nil || !info.IsDir() {
			t.Error("the command did not create the fresh output directory")
		}
		binding := readFile(t, filepath.Join(out, "binding_gen.go"))
		lines := strings.Split(string(binding), "\n")
		if lines[0] != "// Code generated by intercall-go; DO NOT EDIT." {
			t.Errorf("binding first line = %q", lines[0])
		}
		if !strings.HasPrefix(lines[1], "// intercall-go binding: export sha256:") {
			t.Errorf("binding ownership line = %q", lines[1])
		}
		if !strings.Contains(string(binding), "package gen") || !strings.Contains(string(binding), "func ExportBinding() intercall.ExportBinding") {
			t.Error("generated export binding is incomplete")
		}
		src := readFile(t, intf)
		stamp := interfaceStamp(t, src)
		if stamp != bindingStamp(t, binding) {
			t.Error("binding and interface stamps differ")
		}
		body := interfaceBody(t, src)
		if stamp != tool.ArtifactStamp(body) {
			t.Error("interface stamp is not the digest of its body")
		}
		// The canonical interface carries the fixed runtime exceptions
		// and the selected procedures in wire-name order.
		text := string(body)
		for _, want := range []string{"exception internal_exception;", "procedure greet {", "procedure ping {", "procedure status {"} {
			if !strings.Contains(text, want) {
				t.Errorf("interface body misses %q:\n%s", want, text)
			}
		}
		if strings.Index(text, "procedure greet") > strings.Index(text, "procedure ping") || strings.Index(text, "procedure ping") > strings.Index(text, "procedure status") {
			t.Error("procedures are not in wire-name byte order")
		}
	})

	t.Run("ExportPackageDefault", func(t *testing.T) {
		root := exportFixture(t)
		cliEnv(t, root)
		intf := filepath.Join(root, "interfaces", "api.intercall")
		// A fresh output uses the output directory's base name.
		fresh := filepath.Join(root, "genpkg")
		status, _, stderr := runCLI(t, "export", "--out", fresh, "--interface", intf, "./prov")
		if status != 0 {
			t.Fatalf("fresh-dir export status = %d, stderr = %q", status, stderr)
		}
		binding := readFile(t, filepath.Join(fresh, "binding_gen.go"))
		if !strings.Contains(string(binding), "package genpkg") {
			t.Error("export into a fresh output did not use the directory's base name")
		}
		// Over an existing owned output package, the owned binding's
		// package clause wins without --package.
		out := filepath.Join(root, "owned")
		seedExportBinding(t, out, filepath.Join(root, "interfaces", "owned.intercall"))
		status, _, stderr = runCLI(t, "export", "--out", out, "--interface", filepath.Join(root, "interfaces", "owned.intercall"), "./prov")
		if status != 0 {
			t.Fatalf("owned-dir export status = %d, stderr = %q", status, stderr)
		}
		binding = readFile(t, filepath.Join(out, "binding_gen.go"))
		if !strings.Contains(string(binding), "package gen") {
			t.Error("export without --package did not use the owned binding's package")
		}
		// An explicit name must equal the owned binding's package.
		status, _, stderr = runCLI(t, "export", "--out", out, "--interface", filepath.Join(root, "interfaces", "owned.intercall"), "--package", "other", "./prov")
		if status != 1 || !strings.Contains(stderr, "must equal an existing owned binding's package name") {
			t.Errorf("conflicting package: status %d, stderr %q", status, stderr)
		}
	})

	t.Run("ExportValidationFailureCreatesNothing", func(t *testing.T) {
		root := exportFixture(t)
		cliEnv(t, root)
		out := filepath.Join(root, "out")
		intf := filepath.Join(root, "interfaces", "api.intercall")
		// A first-run success creates the owned pair, so a later
		// validation failure must replace nothing.
		if status, _, stderr := runCLI(t, "export", "--out", out, "--interface", intf, "./prov"); status != 0 {
			t.Fatalf("first-run export status = %d, stderr = %q", status, stderr)
		}
		bindingPath := filepath.Join(out, "binding_gen.go")
		bindingBefore, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		intfBefore, err := os.Stat(intf)
		if err != nil {
			t.Fatal(err)
		}
		// A pattern that matches no package is a validation failure.
		status, _, stderr := runCLI(t, "export", "--out", out, "--interface", intf, "./nope")
		if status != 1 {
			t.Errorf("status = %d, want 1", status)
		}
		if !strings.Contains(stderr, "nope") {
			t.Errorf("stderr = %q, want the pattern diagnostic", stderr)
		}
		if !strings.Contains(stderr, ":1:1:") {
			t.Errorf("stderr = %q, want a 1:1 operand diagnostic", stderr)
		}
		if after, err := os.Stat(bindingPath); err != nil || !os.SameFile(bindingBefore, after) {
			t.Error("validation failure replaced the owned binding")
		}
		if after, err := os.Stat(intf); err != nil || !os.SameFile(intfBefore, after) {
			t.Error("validation failure replaced the owned interface")
		}
		// A fresh output directory is not created on validation
		// failure: the discovery phase rejects it before any mutation.
		fresh := filepath.Join(root, "fresh")
		status, _, stderr = runCLI(t, "export", "--out", fresh, "--interface", intf, "./nope")
		if status != 1 {
			t.Errorf("fresh-dir status = %d, want 1", status)
		}
		if _, err := os.Stat(fresh); !os.IsNotExist(err) {
			t.Error("validation failure created the fresh output directory")
		}
	})

	t.Run("ExportUnownedCollisions", func(t *testing.T) {
		root := exportFixture(t)
		cliEnv(t, root)
		out := filepath.Join(root, "out")
		intf := filepath.Join(root, "interfaces", "api.intercall")
		// An existing owned output package models a checked-in binding
		// over which the command regenerates; the collisions below must
		// never be replaced or modified.
		seedExportBinding(t, out, intf)
		bindingPath := filepath.Join(out, "binding_gen.go")

		// A handwritten binding is an unowned collision: nothing is
		// replaced and the interface is untouched.
		owned := readFile(t, bindingPath)
		if err := os.WriteFile(bindingPath, []byte("package gen\n\nvar x = 1\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		intfBefore, err := os.Stat(intf)
		if err != nil {
			t.Fatal(err)
		}
		status, _, stderr := runCLI(t, "export", "--out", out, "--interface", intf, "./prov")
		if status != 1 || !strings.Contains(stderr, "not replaceable") {
			t.Errorf("unowned binding: status %d, stderr %q", status, stderr)
		}
		if got := readFile(t, bindingPath); string(got) != "package gen\n\nvar x = 1\n" {
			t.Error("the unowned binding was modified")
		}
		if after, err := os.Stat(intf); err != nil || !os.SameFile(intfBefore, after) {
			t.Error("the interface was replaced despite the unowned binding")
		}
		if strings.Contains(stderr, ".tmp-") {
			t.Errorf("stderr reports a staging path: %q", stderr)
		}

		// An unmarked interface is an unowned collision: the owned
		// binding is untouched.
		if err := os.WriteFile(bindingPath, owned, 0o644); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(intf, []byte("exception seed;\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		bindingBefore, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		status, _, stderr = runCLI(t, "export", "--out", out, "--interface", intf, "./prov")
		if status != 1 || !strings.Contains(stderr, "not replaceable") {
			t.Errorf("unowned interface: status %d, stderr %q", status, stderr)
		}
		if after, err := os.Stat(bindingPath); err != nil || !os.SameFile(bindingBefore, after) {
			t.Error("the binding was replaced despite the unowned interface")
		}
		if got := readFile(t, intf); string(got) != "exception seed;\n" {
			t.Error("the unowned interface was modified")
		}
	})

	t.Run("ExportIncludeExclude", func(t *testing.T) {
		root := exportFixture(t)
		cliEnv(t, root)
		out := filepath.Join(root, "out")
		// Repeatable --include values accumulate and restrict the
		// selection.
		status, _, stderr := runCLI(t, "export", "--out", out, "--interface", filepath.Join(root, "interfaces", "inc.intercall"),
			"--include", "example.com/cli/prov.Greet", "--include", "example.com/cli/prov.Status", "./prov")
		if status != 0 {
			t.Fatalf("include export status = %d, stderr = %q", status, stderr)
		}
		body := string(interfaceBody(t, readFile(t, filepath.Join(root, "interfaces", "inc.intercall"))))
		if !strings.Contains(body, "procedure greet") || !strings.Contains(body, "procedure status") {
			t.Errorf("include selection misses a procedure:\n%s", body)
		}
		if strings.Contains(body, "procedure ping") {
			t.Errorf("include selection kept an excluded procedure:\n%s", body)
		}
		// A repeatable --exclude removes from the include set, so
		// exclusion wins.
		status, _, stderr = runCLI(t, "export", "--out", out, "--interface", filepath.Join(root, "interfaces", "exc.intercall"),
			"--include", "example.com/cli/prov.Greet", "--include", "example.com/cli/prov.Status",
			"--exclude", "example.com/cli/prov.Greet", "--exclude", "example.com/cli/prov.Status", "./prov")
		if status != 0 {
			t.Fatalf("exclude export status = %d, stderr = %q", status, stderr)
		}
		body = string(interfaceBody(t, readFile(t, filepath.Join(root, "interfaces", "exc.intercall"))))
		if strings.Contains(body, "procedure greet") || strings.Contains(body, "procedure status") || strings.Contains(body, "procedure ping") {
			t.Errorf("exclude selection kept a procedure:\n%s", body)
		}
		if !strings.Contains(body, "exception internal_exception;") {
			t.Errorf("empty selection still carries the fixed exceptions:\n%s", body)
		}
	})

	t.Run("ExportDeterministicRepeatInvocation", func(t *testing.T) {
		root := exportFixture(t)
		cliEnv(t, root)
		out := filepath.Join(root, "out")
		intf := filepath.Join(root, "interfaces", "api.intercall")
		args := []string{"export", "--out", out, "--interface", intf, "./prov"}
		if status, _, stderr := runCLI(t, args...); status != 0 {
			t.Fatalf("first export status = %d, stderr = %q", status, stderr)
		}
		bindingPath := filepath.Join(out, "binding_gen.go")
		bindingBefore, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		intfBefore, err := os.Stat(intf)
		if err != nil {
			t.Fatal(err)
		}
		firstBinding := readFile(t, bindingPath)
		firstIntf := readFile(t, intf)
		status, _, stderr := runCLI(t, args...)
		if status != 0 {
			t.Fatalf("second export status = %d, stderr = %q", status, stderr)
		}
		if !bytes.Equal(readFile(t, bindingPath), firstBinding) || !bytes.Equal(readFile(t, intf), firstIntf) {
			t.Error("repeated invocation changed the artifact bytes")
		}
		bindingAfter, err := os.Stat(bindingPath)
		if err != nil {
			t.Fatal(err)
		}
		intfAfter, err := os.Stat(intf)
		if err != nil {
			t.Fatal(err)
		}
		if !os.SameFile(bindingBefore, bindingAfter) || !os.SameFile(intfBefore, intfAfter) {
			t.Error("repeated invocation replaced an unchanged target")
		}
		if !bindingBefore.ModTime().Equal(bindingAfter.ModTime()) || !intfBefore.ModTime().Equal(intfAfter.ModTime()) {
			t.Error("repeated invocation rewrote an unchanged target")
		}
	})

	t.Run("ExportInterruptedRepair", func(t *testing.T) {
		root := exportFixture(t)
		cliEnv(t, root)
		out := filepath.Join(root, "out")
		intf := filepath.Join(root, "interfaces", "api.intercall")
		args := []string{"export", "--out", out, "--interface", intf, "./prov"}
		if status, _, stderr := runCLI(t, args...); status != 0 {
			t.Fatalf("first export status = %d, stderr = %q", status, stderr)
		}
		// Exactly one missing owned target is recoverable ownership
		// state: the next invocation deterministically repairs both.
		if err := os.Remove(intf); err != nil {
			t.Fatal(err)
		}
		status, _, stderr := runCLI(t, args...)
		if status != 0 {
			t.Fatalf("repair export status = %d, stderr = %q", status, stderr)
		}
		binding := readFile(t, filepath.Join(out, "binding_gen.go"))
		src := readFile(t, intf)
		if got := interfaceStamp(t, src); got != bindingStamp(t, binding) {
			t.Error("repaired binding and interface stamps differ")
		}
		body := interfaceBody(t, src)
		if got := tool.ArtifactStamp(body); got != bindingStamp(t, binding) {
			t.Error("repaired stamps do not hash the canonical body")
		}
	})

	t.Run("ExportDistinctTargets", func(t *testing.T) {
		root := t.TempDir()
		status, _, stderr := runCLI(t, "export", "--out", filepath.Join(root, "out"), "--interface", filepath.Join(root, "out", "binding_gen.go"), "./prov")
		if status != 1 {
			t.Errorf("status = %d, want 1", status)
		}
		if !strings.Contains(stderr, "must be distinct") {
			t.Errorf("stderr = %q, want the distinct-targets error", stderr)
		}
	})
}
