// Package importfixture is the compiled import-binding fixture of
// internal/tool.
//
// binding_gen.go is generated byte-for-byte by the import emitter from
// internal/tool/testdata/import/import.intercall; tests in internal/tool
// regenerate it in memory, stage it through the artifact writer, and
// verify the checked-in file never drifts. This file is the handwritten
// test surface: it exposes the generated private response decoders, the
// codec pairs, the codec and response error sentinels, the machine
// metadata constant, and Go type aliases for the anonymous inline
// records, so generation, runtime, and fuzz tests can use them without
// spelling generated internals.
package importfixture

// SemanticPayload returns the exact text of the generated
// _intercallSemantic constant: the unpadded RFC 4648 base64url encoding
// of the canonical interface body, split into quoted chunks.
func SemanticPayload() string { return _intercallSemantic }

// Go type aliases for the anonymous inline records of the fixture
// interface. The generated functions spell these struct types inline
// with their exact intercall tags; the aliases are identical types.
type (
	// PaintOrigin is record { x int32; y int32; }, the paint origin and
	// the locate box corner.
	PaintOrigin = struct {
		X int32 `intercall:"x"`
		Y int32 `intercall:"y"`
	}
	// PaintSize is record { width uint32; height uint32; }, the paint
	// size parameter.
	PaintSize = struct {
		Width  uint32 `intercall:"width"`
		Height uint32 `intercall:"height"`
	}
	// PaintResult is record { width uint32; height uint32; }, the paint
	// return value. It shares its wire structure with PaintSize, so the
	// two anonymous records share one codec pair.
	PaintResult = struct {
		Width  uint32 `intercall:"width"`
		Height uint32 `intercall:"height"`
	}
	// LocateBox is record { corner record { x int32; y int32; }; label
	// string; }, the locate parameter.
	LocateBox = struct {
		Corner PaintOrigin `intercall:"corner"`
		Label  string      `intercall:"label"`
	}
	// FailedPayload is the payload record of exception failed.
	FailedPayload = struct {
		Code    int32  `intercall:"code"`
		Message string `intercall:"message"`
	}
	// RecordEmpty is record {}.
	RecordEmpty = struct{}
)

// Error sentinels of the generated codecs and response decoders.
var (
	ErrTruncated  = _intercallerror_short_8e6f381b5f48ed3c // fewer bytes than a fixed-width value
	ErrTooLong    = _intercallerror_long_e8fb175d020577b4  // declared length or count exceeds the payload
	ErrNaN        = _intercallerror_nan_81e7acbc891a3841   // noncanonical NaN bit pattern
	ErrUTF8       = _intercallerror_utf8_21fa605c915dede7  // invalid UTF-8 in a string
	ErrTrailing   = _intercallerror_trailing_780879067f3b9aee
	ErrUnknownKey = _intercallerror_unknown_key_a7606243fcb8ec95
)

// Codecs exposes the generated codec pairs of the fixture interface that
// the runtime and decoder tests need. Encoders append one value to an
// owned payload; decoders return the value with the exact unconsumed
// remainder.
var Codecs = struct {
	EncodeString        func([]byte, string) ([]byte, error)
	DecodeString        func([]byte) (string, []byte, error)
	EncodeInt64         func([]byte, int64) ([]byte, error)
	DecodeInt64         func([]byte) (int64, []byte, error)
	EncodeUint32        func([]byte, uint32) ([]byte, error)
	DecodeUint32        func([]byte) (uint32, []byte, error)
	EncodeUint64        func([]byte, uint64) ([]byte, error)
	DecodeUint64        func([]byte) (uint64, []byte, error)
	EncodeBytes         func([]byte, []byte) ([]byte, error)
	DecodeBytes         func([]byte) ([]byte, []byte, error)
	EncodeListUint8     func([]byte, []uint8) ([]byte, error)
	DecodeListUint8     func([]byte) ([]uint8, []byte, error)
	EncodeUserID        func([]byte, UserID) ([]byte, error)
	DecodeUserID        func([]byte) (UserID, []byte, error)
	EncodePoint         func([]byte, Point) ([]byte, error)
	DecodePoint         func([]byte) (Point, []byte, error)
	EncodeEmpty         func([]byte, Empty) ([]byte, error)
	DecodeEmpty         func([]byte) (Empty, []byte, error)
	EncodeNames         func([]byte, Names) ([]byte, error)
	DecodeNames         func([]byte) (Names, []byte, error)
	EncodeBlob          func([]byte, Blob) ([]byte, error)
	DecodeBlob          func([]byte) (Blob, []byte, error)
	EncodePaintOrigin   func([]byte, PaintOrigin) ([]byte, error)
	DecodePaintOrigin   func([]byte) (PaintOrigin, []byte, error)
	EncodePaintSize     func([]byte, PaintSize) ([]byte, error)
	DecodePaintSize     func([]byte) (PaintSize, []byte, error)
	EncodePaintResult   func([]byte, PaintResult) ([]byte, error)
	DecodePaintResult   func([]byte) (PaintResult, []byte, error)
	EncodeLocateBox     func([]byte, LocateBox) ([]byte, error)
	DecodeLocateBox     func([]byte) (LocateBox, []byte, error)
	EncodeFailedPayload func([]byte, FailedPayload) ([]byte, error)
	DecodeFailedPayload func([]byte) (FailedPayload, []byte, error)
	EncodeRecordEmpty   func([]byte, RecordEmpty) ([]byte, error)
	DecodeRecordEmpty   func([]byte) (RecordEmpty, []byte, error)
	EncodeListEmpty     func([]byte, []Empty) ([]byte, error)
	DecodeListEmpty     func([]byte) ([]Empty, []byte, error)
}{
	EncodeString:        _intercallenc_string_00f359e600d57533,
	DecodeString:        _intercalldec_string_e113d3e53c0a20ab,
	EncodeInt64:         _intercallenc_int64_e7f52489efcdea71,
	DecodeInt64:         _intercalldec_int64_b1e23aba3828fe59,
	EncodeUint32:        _intercallenc_uint32_849a205c3f38007b,
	DecodeUint32:        _intercalldec_uint32_2c359ae3014ca813,
	EncodeUint64:        _intercallenc_uint64_849a235c3f380556,
	DecodeUint64:        _intercalldec_uint64_2c359de3014cad0e,
	EncodeBytes:         _intercallenc_bytes_6b87e24ef38333c9,
	DecodeBytes:         _intercalldec_bytes_dc8f190227fa8a41,
	EncodeListUint8:     _intercallenc_list_uint8_fbe83adc98d1de40,
	DecodeListUint8:     _intercalldec_list_uint8_85ffe9748dbe7ae8,
	EncodeUserID:        _intercallenc_type_user_id_6d1e6a3f9ce24d1b,
	DecodeUserID:        _intercalldec_type_user_id_3126e3c36ce2c1e3,
	EncodePoint:         _intercallenc_type_point_41c85497633e6c1a,
	DecodePoint:         _intercalldec_type_point_13bb84b3d4b45cd2,
	EncodeEmpty:         _intercallenc_type_empty_d7948148fc4b8663,
	DecodeEmpty:         _intercalldec_type_empty_ebbde05522390e0b,
	EncodeNames:         _intercallenc_type_names_3a79a20d5bb07688,
	DecodeNames:         _intercalldec_type_names_2f8d71a1a91ab970,
	EncodeBlob:          _intercallenc_type_blob_e1acc4fdc2289b89,
	DecodeBlob:          _intercalldec_type_blob_1af15a4467d7d621,
	EncodePaintOrigin:   _intercallenc_record_x_int32_y_int32__41afb291be0604b7,
	DecodePaintOrigin:   _intercalldec_record_x_int32_y_int32__593ba06c025edc9f,
	EncodePaintSize:     _intercallenc_record_width_uint32_height_uint32__73d0043a1c2de279,
	DecodePaintSize:     _intercalldec_record_width_uint32_height_uint32__781395a0cd400f01,
	EncodePaintResult:   _intercallenc_record_width_uint32_height_uint32__73d0043a1c2de279,
	DecodePaintResult:   _intercalldec_record_width_uint32_height_uint32__781395a0cd400f01,
	EncodeLocateBox:     _intercallenc_record_corner_record_x_int32_y_int32__label_string__b203f8a78d3cc9f9,
	DecodeLocateBox:     _intercalldec_record_corner_record_x_int32_y_int32__label_string__6be99887be9b4b81,
	EncodeFailedPayload: _intercallenc_record_code_int32_message_string__a7b4fae790da6661,
	DecodeFailedPayload: _intercalldec_record_code_int32_message_string__d2d6ef92f192a229,
	EncodeRecordEmpty:   _intercallenc_record___15061e0cdb39bf87,
	DecodeRecordEmpty:   _intercalldec_record___02611fdc3522b7cf,
	EncodeListEmpty:     _intercallenc_list_empty_2f3b7b645de18e03,
	DecodeListEmpty:     _intercalldec_list_empty_0ca829f76819e63b,
}

// Responses exposes the generated response decoder of every fixture
// procedure through one uniform signature. Each decoder accepts the
// exception key zero as the procedure's success value and every declared
// exception key, consumes the payload exactly, and stores the decoded
// result or exception. The three returned values are the stored result
// (the zero value when an exception was accepted), the stored exception
// (nil on success), and the decoder error.
var Responses = struct {
	DecodeEcho   func(key uint64, payload []byte) (any, error, error)
	DecodeAdd    func(key uint64, payload []byte) (any, error, error)
	DecodeSample func(key uint64, payload []byte) (any, error, error)
	DecodeWave   func(key uint64, payload []byte) (any, error, error)
	DecodePaint  func(key uint64, payload []byte) (any, error, error)
	DecodeLocate func(key uint64, payload []byte) (any, error, error)
	DecodeFetch  func(key uint64, payload []byte) (any, error, error)
	DecodePing   func(key uint64, payload []byte) (any, error, error)
	DecodeStamp  func(key uint64, payload []byte) (any, error, error)
	DecodeLoad   func(key uint64, payload []byte) (any, error, error)
	DecodeTiny   func(key uint64, payload []byte) (any, error, error)
}{
	DecodeEcho: func(key uint64, payload []byte) (any, error, error) {
		var out string
		var exc error
		err := _intercalldecresp_echo_6fe006f4937533cd(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodeAdd: func(key uint64, payload []byte) (any, error, error) {
		var out int64
		var exc error
		err := _intercalldecresp_add_5e72c14f6c13c307(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodeSample: func(key uint64, payload []byte) (any, error, error) {
		var out []byte
		var exc error
		err := _intercalldecresp_sample_fbb0835cbae3b12c(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodeWave: func(key uint64, payload []byte) (any, error, error) {
		var out uint32
		var exc error
		err := _intercalldecresp_wave_d4c806f43bd837a5(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodePaint: func(key uint64, payload []byte) (any, error, error) {
		var out PaintResult
		var exc error
		err := _intercalldecresp_paint_97cd7f2b67f8169e(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodeLocate: func(key uint64, payload []byte) (any, error, error) {
		var out Point
		var exc error
		err := _intercalldecresp_locate_86663fa0151dce50(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodeFetch: func(key uint64, payload []byte) (any, error, error) {
		var out Blob
		var exc error
		err := _intercalldecresp_fetch_fb5e747edaa5ec2e(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodePing: func(key uint64, payload []byte) (any, error, error) {
		var exc error
		err := _intercalldecresp_ping_0039cdf4547dbafa(key, payload, &exc)
		return nil, exc, err
	},
	DecodeStamp: func(key uint64, payload []byte) (any, error, error) {
		var out RecordEmpty
		var exc error
		err := _intercalldecresp_stamp_efd56b2038fbbdd7(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodeLoad: func(key uint64, payload []byte) (any, error, error) {
		var out []Empty
		var exc error
		err := _intercalldecresp_load_ad2c16f4b65d2712(key, payload, &out, &exc)
		return out, exc, err
	},
	DecodeTiny: func(key uint64, payload []byte) (any, error, error) {
		var out uint32
		var exc error
		err := _intercalldecresp_tiny_dbe049f43f6b2950(key, payload, &out, &exc)
		return out, exc, err
	},
}
