import assert from "node:assert/strict";
import { access, mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import test from "node:test";

const run = promisify(execFile);

test("CLI import validates before writing and emits owned binding", async () => {
    const root = await mkdtemp(join(tmpdir(), "intercall-cli-"));
    const out = join(root, "generated");
    const result = await run(process.execPath, ["dist/cli/main.js", "import", "--out", out, "test/fixtures/import/empty.intercall"], { cwd: process.cwd() });
    assert.equal(result.stderr, "");
    const output = (await readFile(join(out, "binding_gen.ts"))).toString();
    assert.match(output, /^\/\/ Code generated by intercall-ts/u);
    await assert.rejects(() => run(process.execPath, ["dist/cli/main.js", "import", "--out", join(root, "bad"), "missing.intercall"], { cwd: process.cwd() }));
    await assert.rejects(() => access(join(root, "bad")));
    await rm(root, { recursive: true, force: true });
});
