import assert from "node:assert/strict";
import { access, mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import test from "node:test";
import { artifactStamp } from "../../dist/cli/ownership.js";

const run = promisify(execFile);

test("CLI export discovers providers and writes owned artifacts", async () => {
    const root = await mkdtemp(join(tmpdir(), "intercall-export-"));
    const out = join(root, "generated");
    const interfacePath = join(root, "api", "browser.intercall");
    await run(process.execPath, ["dist/cli/main.js", "export", "--project", "test/fixtures/compiler/tsconfig-discovery.json", "--out", out, "--interface", interfacePath, "test/fixtures/compiler/discovery.ts"], { cwd: process.cwd() });
    const binding = (await readFile(join(out, "binding_gen.ts"))).toString();
    const interfaceText = (await readFile(interfacePath)).toString();
    const interfaceBody = interfaceText.replace(/^\/\* Code generated by intercall-ts; artifact sha256:[0-9a-f]{64}; DO NOT EDIT\. \*\/\n\n/u, "");
    assert.match(binding, new RegExp(`binding: export sha256:${artifactStamp(interfaceBody)}`));
    assert.match(binding, /provider_0/);
    assert.match(binding, /decodeProgram/);
    assert.match(interfaceText, /artifact sha256:/);
    await assert.rejects(() => access(join(root, "missing")));
    await rm(root, { recursive: true, force: true });
});
