import assert from "node:assert/strict";
import test from "node:test";
import { parseInterface, validateInterface } from "../../dist/syntax/index.js";
import { buildImportGeneration, buildValidatedImportGeneration, emitImportMetadata, hasGeneratedTypeScriptMarker, readGeneratedMetadata } from "../../dist/tool/index.js";

test("requires the exact generated-file marker before metadata use", () => {
    assert.equal(hasGeneratedTypeScriptMarker("// Code generated by intercall-ts; DO NOT EDIT.\ncontent"), true);
    assert.equal(hasGeneratedTypeScriptMarker("// Code generated by user; DO NOT EDIT.\ncontent"), false);
    assert.throws(() => readGeneratedMetadata("// Code generated by intercall-ts; DO NOT EDIT.\n"), /missing/);
});

test("emits canonical semantic metadata and machine type rows", () => {
    const file = parseInterface("meta.intercall", new TextEncoder().encode("type user_id uint64;"));
    validateInterface(file);
    const generation = buildValidatedImportGeneration(file, buildImportGeneration(file));
    const output = emitImportMetadata(file, generation);
    assert.match(output, /export const interfaceBody/);
    assert.match(output, /type user_id uint64;/);
    assert.match(output, /interfaceIDHex/);
    assert.match(output, /machineTypes/);
    assert.equal(output, emitImportMetadata(file, generation));
    const metadata = readGeneratedMetadata(`// Code generated by intercall-ts; DO NOT EDIT.\n${output}`);
    assert.equal(metadata.machineTypes[0].wireName, "user_id");
});
