import assert from "node:assert/strict";
import test from "node:test";
import { attachDocumentation, formatInterface, parseInterface, validateInterface } from "../../dist/syntax/index.js";
import { buildImportGeneration, buildValidatedImportGeneration, buildValidatedImportSource, decodeGeneratedInterface, emitImportMetadata, formatGeneratedSource, hasGeneratedTypeScriptMarker, readGeneratedMetadata, semanticDocumentation, validateMetadataRows } from "../../dist/tool/index.js";

test("requires the exact generated-file marker before metadata use", () => {
    assert.equal(hasGeneratedTypeScriptMarker("// Code generated by intercall-ts; DO NOT EDIT.\ncontent"), true);
    assert.equal(hasGeneratedTypeScriptMarker("// Code generated by user; DO NOT EDIT.\ncontent"), false);
    assert.throws(() => readGeneratedMetadata("// Code generated by intercall-ts; DO NOT EDIT.\n"), /missing/);
    const forged = "// Code generated by intercall-ts; DO NOT EDIT.\nexport const interfaceBodyChunks = Object.freeze([\"%%%\"]);\nexport const interfaceIDHex = \"0000000000000000000000000000000000000000000000000000000000000000\";\nexport const machineTypes = Object.freeze([{\"wireName\":\"x\",\"nativeName\":\"X\"},{\"wireName\":\"x\",\"nativeName\":\"Y\"}]);\n";
    assert.throws(() => readGeneratedMetadata(forged), /duplicate/);
    const valid = "// Code generated by intercall-ts; DO NOT EDIT.\nexport const interfaceBodyChunks = Object.freeze([]);\nexport const interfaceIDHex = \"0000000000000000000000000000000000000000000000000000000000000000\";\nexport const machineTypes = Object.freeze([]);\n";
    assert.throws(() => readGeneratedMetadata(valid.replace("export const interfaceBodyChunks", "// export const interfaceBodyChunks")), /missing/);
    assert.throws(() => readGeneratedMetadata(`${valid}export const machineTypes = Object.freeze([]);\n`), /duplicate/);
});

test("round-trips canonical semantic body and interface ID", () => {
    const file = parseInterface("roundtrip.intercall", new TextEncoder().encode("type user record { id uint64; };\n"));
    validateInterface(file);
    const body = formatInterface(file);
    const generated = formatGeneratedSource(buildValidatedImportSource(file));
    const metadata = readGeneratedMetadata(`// Code generated by intercall-ts; DO NOT EDIT.\n${generated}`);
    assert.equal(formatInterface(decodeGeneratedInterface(metadata)), body);
});

test("emits canonical semantic metadata and machine type rows", () => {
    const file = parseInterface("meta.intercall", new TextEncoder().encode("type user_id uint64;"));
    validateInterface(file);
    const generation = buildValidatedImportGeneration(file, buildImportGeneration(file));
    const output = emitImportMetadata(file, generation);
    assert.match(output, /export const interfaceBody/);
    assert.match(output, /type user_id uint64;/);
    assert.match(output, /interfaceIDHex/);
    assert.match(output, /machineTypes/);
    assert.equal(output, emitImportMetadata(file, generation));
    const metadata = readGeneratedMetadata(`// Code generated by intercall-ts; DO NOT EDIT.\n${output}`);
    assert.equal(metadata.machineTypes[0].wireName, "user_id");
    const documented = parseInterface("docs.intercall", new TextEncoder().encode("/* User documentation. */\ntype user uint8;"));
    validateInterface(documented);
    attachDocumentation(documented);
    assert.equal(semanticDocumentation(documented).get("user"), "User documentation.");
    const decoded = decodeGeneratedInterface(metadata);
    assert.equal(decoded.declarations[0].name.name, "user_id");
    validateMetadataRows(decoded, metadata.machineTypes);
    assert.throws(() => validateMetadataRows(decoded, []), /missing/);
});
