package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// Example demonstrates one complete intercall-go import invocation: it
// writes the exact exported interface of the GO.md quick-start
// walkthrough (gen/hello.intercall, including its ownership marker and
// the three fixed runtime exceptions), runs the command against a
// temporary output directory, and prints the deterministic ownership
// lines of the generated binding. The example runs entirely outside the
// repository and removes its temporary files afterwards; no test leaves
// repository files dirty.
//
// GO.md step 3 imports this exact interface with this exact command, so
// the doc test pins the documented example to the generated bytes,
// including the SHA-256 artifact stamp of the canonical body quoted in
// GO.md.
func Example() {
	dir, err := os.MkdirTemp("", "intercall-go-example")
	if err != nil {
		panic(err)
	}
	defer os.RemoveAll(dir)

	interfaceFile := filepath.Join(dir, "hello.intercall")
	if err := os.WriteFile(interfaceFile, []byte(`/* Code generated by intercall-go; artifact sha256:cf123289caa70b7d11a727e07e96cc4de5bde0d0ffbf5acacb9b22903f7f85c9; DO NOT EDIT. */

exception internal_exception;

exception invalid_arguments;

exception procedure_not_found;

/* Hello returns a greeting for name. */
procedure hello {
    /* The name to greet. */
    name string;
}
/* The greeting. */
string;
`), 0o644); err != nil {
		panic(err)
	}

	out := filepath.Join(dir, "helloclient")
	var stdout, stderr bytes.Buffer
	if status := run([]string{"import", "--out", out, interfaceFile}, &stdout, &stderr); status != 0 {
		panic(fmt.Sprintf("intercall-go import exited with status %d: %s", status, stderr.String()))
	}

	binding, err := os.ReadFile(filepath.Join(out, "binding_gen.go"))
	if err != nil {
		panic(err)
	}
	lines := bytes.SplitN(binding, []byte("\n"), 3)
	fmt.Printf("%s\n%s\n", lines[0], lines[1])

	// Output:
	// // Code generated by intercall-go; DO NOT EDIT.
	// // intercall-go binding: import sha256:cf123289caa70b7d11a727e07e96cc4de5bde0d0ffbf5acacb9b22903f7f85c9
}
