// Code generated by intercall-go; DO NOT EDIT.
// intercall-go binding: export sha256:b9b1fb705669f27661efccd96bc757da250a33c69decbd3eb952f7ee0758e24f

package exportfixture

import (
	"context"
	"errors"
	"github.com/cerasos/intercall/go"
	"github.com/cerasos/intercall/go/internal/tool/exportfixture/prov"
	"math"
	"unicode/utf8"
)

const _intercallmaxint_a986121adce7d8c5 = int(^uint(0) >> 1)

var (
	_intercallerror_long_e8fb175d020577b4  = errors.New("intercall: wire length exceeds available bytes")
	_intercallerror_nan_81e7acbc891a3841   = errors.New("intercall: noncanonical NaN bit pattern")
	_intercallerror_short_8e6f381b5f48ed3c = errors.New("intercall: truncated wire value")
	_intercallerror_utf8_21fa605c915dede7  = errors.New("intercall: string is not valid UTF-8")
)

func _intercallenc_int8_2b2537505a97b829(buf []byte, v int8) ([]byte, error) {
	return append(buf, byte(v)), nil
}

func _intercalldec_int8_8e851e84d785af51(src []byte) (int8, []byte, error) {
	if len(src) < 1 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int8(src[0]), src[1:], nil
}

func _intercallenc_int16_e7f51d89efcdde56(buf []byte, v int16) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8)), nil
}

func _intercalldec_int16_b1e233ba3828f2be(src []byte) (int16, []byte, error) {
	if len(src) < 2 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int16(src[0]) | int16(src[1])<<8, src[2:], nil
}

func _intercallenc_int32_e7f51f89efcde1f4(buf []byte, v int32) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)), nil
}

func _intercalldec_int32_b1e235ba3828f5dc(src []byte) (int32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int32(src[0]) | int32(src[1])<<8 | int32(src[2])<<16 | int32(src[3])<<24, src[4:], nil
}

func _intercallenc_int64_e7f52489efcdea71(buf []byte, v int64) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56)), nil
}

func _intercalldec_int64_b1e23aba3828fe59(src []byte) (int64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int64(src[0]) | int64(src[1])<<8 | int64(src[2])<<16 | int64(src[3])<<24 | int64(src[4])<<32 | int64(src[5])<<40 | int64(src[6])<<48 | int64(src[7])<<56, src[8:], nil
}

func _intercallenc_uint8_77a42def2538a018(buf []byte, v uint8) ([]byte, error) {
	return append(buf, byte(v)), nil
}

func _intercalldec_uint8_ebdba4a25c65fcd0(src []byte) (uint8, []byte, error) {
	if len(src) < 1 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint8(src[0]), src[1:], nil
}

func _intercallenc_uint16_849a1e5c3f37fcd5(buf []byte, v uint16) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8)), nil
}

func _intercalldec_uint16_2c3598e3014ca48d(src []byte) (uint16, []byte, error) {
	if len(src) < 2 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint16(src[0]) | uint16(src[1])<<8, src[2:], nil
}

func _intercallenc_uint32_849a205c3f38007b(buf []byte, v uint32) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)), nil
}

func _intercalldec_uint32_2c359ae3014ca813(src []byte) (uint32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint32(src[0]) | uint32(src[1])<<8 | uint32(src[2])<<16 | uint32(src[3])<<24, src[4:], nil
}

func _intercallenc_uint64_849a235c3f380556(buf []byte, v uint64) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56)), nil
}

func _intercalldec_uint64_2c359de3014cad0e(src []byte) (uint64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint64(src[0]) | uint64(src[1])<<8 | uint64(src[2])<<16 | uint64(src[3])<<24 | uint64(src[4])<<32 | uint64(src[5])<<40 | uint64(src[6])<<48 | uint64(src[7])<<56, src[8:], nil
}

func _intercallenc_float32_6a8f4eea7f75b7d9(buf []byte, v float32) ([]byte, error) {
	var bits uint32
	if v != v {
		bits = 0x7fc00000
	} else {
		bits = math.Float32bits(v)
	}
	return append(buf, byte(bits), byte(bits>>8), byte(bits>>16), byte(bits>>24)), nil
}

func _intercalldec_float32_a273938b3b463041(src []byte) (float32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	bits := uint32(src[0]) | uint32(src[1])<<8 | uint32(src[2])<<16 | uint32(src[3])<<24
	v := math.Float32frombits(bits)
	if v != v && bits != 0x7fc00000 {
		return 0, nil, _intercallerror_nan_81e7acbc891a3841
	}
	return v, src[4:], nil
}

func _intercallenc_float64_6a8f51ea7f75bd30(buf []byte, v float64) ([]byte, error) {
	var bits uint64
	if v != v {
		bits = 0x7ff8000000000000
	} else {
		bits = math.Float64bits(v)
	}
	return append(buf, byte(bits), byte(bits>>8), byte(bits>>16), byte(bits>>24), byte(bits>>32), byte(bits>>40), byte(bits>>48), byte(bits>>56)), nil
}

func _intercalldec_float64_a273968b3b4635b8(src []byte) (float64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	bits := uint64(src[0]) | uint64(src[1])<<8 | uint64(src[2])<<16 | uint64(src[3])<<24 |
		uint64(src[4])<<32 | uint64(src[5])<<40 | uint64(src[6])<<48 | uint64(src[7])<<56
	v := math.Float64frombits(bits)
	if v != v && bits != 0x7ff8000000000000 {
		return 0, nil, _intercallerror_nan_81e7acbc891a3841
	}
	return v, src[8:], nil
}

func _intercallenc_string_00f359e600d57533(buf []byte, v string) ([]byte, error) {
	if !utf8.ValidString(v) {
		return nil, _intercallerror_utf8_21fa605c915dede7
	}
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return append(buf, v...), nil
}

func _intercalldec_string_e113d3e53c0a20ab(src []byte) (string, []byte, error) {
	n64, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return "", nil, err
	}
	if n64 > uint64(len(src)) {
		return "", nil, _intercallerror_long_e8fb175d020577b4
	}
	n := int(n64)
	b := src[:n]
	if !utf8.Valid(b) {
		return "", nil, _intercallerror_utf8_21fa605c915dede7
	}
	return string(b), src[n:], nil
}

func _intercallenc_bytes_6b87e24ef38333c9(buf []byte, v []byte) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return append(buf, v...), nil
}

func _intercalldec_bytes_dc8f190227fa8a41(src []byte) ([]byte, []byte, error) {
	n64, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return nil, nil, err
	}
	if n64 > uint64(len(src)) {
		return nil, nil, _intercallerror_long_e8fb175d020577b4
	}
	n := int(n64)
	dst := make([]byte, n)
	copy(dst, src[:n])
	return dst, src[n:], nil
}

func _intercallenc_type_point_41c85497633e6c1a(buf []byte, v prov.Point) ([]byte, error) {
	var err error
	buf, err = _intercallenc_float64_6a8f51ea7f75bd30(buf, v.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_float64_6a8f51ea7f75bd30(buf, v.Y)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_point_13bb84b3d4b45cd2(src []byte) (prov.Point, []byte, error) {
	var v prov.Point
	var err error
	v.X, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v, nil, err
	}
	v.Y, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_type_user_id_6d1e6a3f9ce24d1b(buf []byte, v prov.UserID) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_user_id_3126e3c36ce2c1e3(src []byte) (prov.UserID, []byte, error) {
	v, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return prov.UserID(v), nil, err
	}
	return prov.UserID(v), src, nil
}
func _intercallenc_record_x_int32_y_int32__struct____X_int32__Y_int32___412839956ef1eb69(buf []byte, v struct {
	X int32
	Y int32
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Y)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_x_int32_y_int32__struct____X_int32__Y_int32___64520c53ce0ee831(src []byte) (struct {
	X int32
	Y int32
}, []byte, error) {
	var v struct {
		X int32
		Y int32
	}
	var err error
	v.X, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Y, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___5f07b5088bd2f3e3(buf []byte, v struct {
	Width  uint32
	Height uint32
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint32_849a205c3f38007b(buf, v.Width)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint32_849a205c3f38007b(buf, v.Height)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___3337324db410126b(src []byte) (struct {
	Width  uint32
	Height uint32
}, []byte, error) {
	var v struct {
		Width  uint32
		Height uint32
	}
	var err error
	v.Width, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v, nil, err
	}
	v.Height, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_list_uint8___uint8_f5408e3ade976024(buf []byte, v []uint8) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_uint8_77a42def2538a018(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_uint8___uint8_ed36b3402c96257c(src []byte) ([]uint8, []byte, error) {
	var v []uint8
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]uint8, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_record___prov_Empty_0f31b3c853dda7c5(buf []byte, v prov.Empty) ([]byte, error) {
	return buf, nil
}

func _intercalldec_record___prov_Empty_8bc6e048a4641e3d(src []byte) (prov.Empty, []byte, error) {
	return prov.Empty{}, src, nil
}
func _intercallenc_record_code_int32_message_string__prov_Failed_d65a7df1fbfd9bb7(buf []byte, v prov.Failed) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Code)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_string_00f359e600d57533(buf, v.Message)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_code_int32_message_string__prov_Failed_e598e6e4369976bf(src []byte) (prov.Failed, []byte, error) {
	var v prov.Failed
	var err error
	v.Code, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Message, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_code_int32__prov_Shared_2cc18b0044d7fe08(buf []byte, v prov.Shared) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Code)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_code_int32__prov_Shared_874999387e5902b0(src []byte) (prov.Shared, []byte, error) {
	var v prov.Shared
	var err error
	v.Code, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercalldereq_add_785d921dde991182(src []byte) (int64, int64, []byte, error) {
	var v0 int64
	var v1 int64
	var err error
	v0, src, err = _intercalldec_int64_b1e23aba3828fe59(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_int64_b1e23aba3828fe59(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_crash_94c3b54ff311327a(src []byte) (string, []byte, error) {
	var v0 string
	var err error
	v0, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_echo_447474c15333e61e(src []byte) (string, []byte, error) {
	var v0 string
	var err error
	v0, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_fetch_6e77f47583666d7f(src []byte) (prov.UserID, []byte, error) {
	var v0 prov.UserID
	var err error
	v0, src, err = _intercalldec_type_user_id_3126e3c36ce2c1e3(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_paint_793e81eb864e04e3(src []byte) (struct {
	X int32
	Y int32
}, struct {
	Width  uint32
	Height uint32
}, []byte, error) {
	var v0 struct {
		X int32
		Y int32
	}
	var v1 struct {
		Width  uint32
		Height uint32
	}
	var err error
	v0, src, err = _intercalldec_record_x_int32_y_int32__struct____X_int32__Y_int32___64520c53ce0ee831(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___3337324db410126b(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_ping_b41a89c1922b222d(src []byte) ([]byte, error) {
	return src, nil
}

func _intercalldereq_sample_5f17e8dec708cf23(src []byte) ([]byte, uint8, []byte, error) {
	var v0 []byte
	var v1 uint8
	var err error
	v0, src, err = _intercalldec_bytes_dc8f190227fa8a41(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_wave_bc0cbcc196779c26(src []byte) ([]uint8, []byte, error) {
	var v0 []uint8
	var err error
	v0, src, err = _intercalldec_list_uint8___uint8_ed36b3402c96257c(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercallmatch_exc_6eefd8396f76a36d(err error) (uint64, []byte) {
	var match int
	var excKey uint64
	var excPayload []byte
	var encErr error
	if err == error(prov.ErrDenied) {
		match++
		excKey = 0x7fbdf637a78620b0
	}
	if e, ok := err.(*prov.Empty); ok && e != nil {
		match++
		excKey = 0xeab4dd94951d6a30
		excPayload, encErr = _intercallenc_record___prov_Empty_0f31b3c853dda7c5(nil, *e)
	}
	if err == error(prov.ErrShared) {
		match++
		excKey = 0x9af2b5f7e68bde66
	}
	if err == error(prov.ErrWeird) {
		match++
		excKey = 0xc89fac47c60e0b40
	}
	if e, ok := err.(*prov.Failed); ok && e != nil {
		match++
		excKey = 0x583fb304d69368ca
		excPayload, encErr = _intercallenc_record_code_int32_message_string__prov_Failed_d65a7df1fbfd9bb7(nil, *e)
	}
	if e, ok := err.(*prov.Shared); ok && e != nil {
		match++
		excKey = 0xa3f509f715a249fe
		excPayload, encErr = _intercallenc_record_code_int32__prov_Shared_2cc18b0044d7fe08(nil, *e)
	}
	if match != 1 || encErr != nil {
		return 0x1aaec22e85996f50, nil
	}
	return excKey, excPayload
}

func _intercalldispatch_6ba7a6d72caedc56(_intercallctx_01508600011dfaaf context.Context, _intercallkey_016b85000134c0a5 uint64, _intercallpayload_31bab4d98281f99a []byte) (uint64, []byte) {
	switch _intercallkey_016b85000134c0a5 {
	case 0x8425decb5e996afe:
		v0, v1, rest, err := _intercalldereq_add_785d921dde991182(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := prov.Add(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_int64_e7f52489efcdea71(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xd4fb7594c57f2f66:
		v0, rest, err := _intercalldereq_crash_94c3b54ff311327a(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		err = prov.Crash(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		return 0, nil
	case 0x159eb91a98f8f42:
		v0, rest, err := _intercalldereq_echo_447474c15333e61e(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := prov.Echo(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_string_00f359e600d57533(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xb50b5c7d5249d7a3:
		v0, rest, err := _intercalldereq_fetch_6e77f47583666d7f(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := prov.Fetch(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_type_point_41c85497633e6c1a(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x52095929e015a29f:
		v0, v1, rest, err := _intercalldereq_paint_793e81eb864e04e3(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := prov.Paint(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___5f07b5088bd2f3e3(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xa3aa209174f340d1:
		rest, err := _intercalldereq_ping_b41a89c1922b222d(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		err = prov.Ping(_intercallctx_01508600011dfaaf)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		return 0, nil
	case 0x2549b9c663851f:
		v0, v1, rest, err := _intercalldereq_sample_5f17e8dec708cf23(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := prov.Sample(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_bytes_6b87e24ef38333c9(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x664ffb9151feebb2:
		v0, rest, err := _intercalldereq_wave_bc0cbcc196779c26(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := prov.Wave(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_uint32_849a205c3f38007b(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	default:
		return 0x970e76fcc5e2dacb, nil
	}
}

var _intercallbinding_47f982b7aff8567b = func() intercall.ExportBinding {
	b, err := intercall.NewExportBindingWithInterfaceID(_intercalldispatch_6ba7a6d72caedc56,
		intercall.InterfaceID{
			0xb9,
			0xb1,
			0xfb,
			0x70,
			0x56,
			0x69,
			0xf2,
			0x76,
			0x61,
			0xef,
			0xcc,
			0xd9,
			0x6b,
			0xc7,
			0x57,
			0xda,
			0x25,
			0x0a,
			0x33,
			0xc6,
			0x9d,
			0xec,
			0xbd,
			0x3e,
			0xb9,
			0x52,
			0xf7,
			0xee,
			0x07,
			0x58,
			0xe2,
			0x4f,
		},
	)
	if err != nil {
		panic(err)
	}
	return b
}()

// ExportBinding returns the package's immutable export binding.
func ExportBinding() intercall.ExportBinding {
	return _intercallbinding_47f982b7aff8567b
}
