// Code generated by intercall-go; DO NOT EDIT.

package fixture

import (
	"errors"
	"math"
	"unicode/utf8"
)

const _intercallmaxint_a986121adce7d8c5 = int(^uint(0) >> 1)

var (
	_intercallerror_long_e8fb175d020577b4  = errors.New("intercall: wire length exceeds available bytes")
	_intercallerror_nan_81e7acbc891a3841   = errors.New("intercall: noncanonical NaN bit pattern")
	_intercallerror_short_8e6f381b5f48ed3c = errors.New("intercall: truncated wire value")
	_intercallerror_utf8_21fa605c915dede7  = errors.New("intercall: string is not valid UTF-8")
)

// @intercall type user_id
type UserID uint64

// @intercall type name
type Name string

// @intercall type point
type Point struct {
	X float64 `intercall:"x"`
	Y float64 `intercall:"y"`
}

// @intercall type pixel
type Pixel struct {
	Red   uint8 `intercall:"red"`
	Green uint8 `intercall:"green"`
	Blue  uint8 `intercall:"blue"`
}

// @intercall type empty
type Empty struct{}

// @intercall type names
type Names []string

// @intercall type matrix
type Matrix [][]int32

// @intercall type blob
type Blob []byte

// @intercall type customer_id
type CustomerID UserID

func _intercallenc_int8_2b2537505a97b829(buf []byte, v int8) ([]byte, error) {
	return append(buf, byte(v)), nil
}

func _intercalldec_int8_8e851e84d785af51(src []byte) (int8, []byte, error) {
	if len(src) < 1 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int8(src[0]), src[1:], nil
}

func _intercallenc_int16_e7f51d89efcdde56(buf []byte, v int16) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8)), nil
}

func _intercalldec_int16_b1e233ba3828f2be(src []byte) (int16, []byte, error) {
	if len(src) < 2 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int16(src[0]) | int16(src[1])<<8, src[2:], nil
}

func _intercallenc_int32_e7f51f89efcde1f4(buf []byte, v int32) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)), nil
}

func _intercalldec_int32_b1e235ba3828f5dc(src []byte) (int32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int32(src[0]) | int32(src[1])<<8 | int32(src[2])<<16 | int32(src[3])<<24, src[4:], nil
}

func _intercallenc_int64_e7f52489efcdea71(buf []byte, v int64) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56)), nil
}

func _intercalldec_int64_b1e23aba3828fe59(src []byte) (int64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int64(src[0]) | int64(src[1])<<8 | int64(src[2])<<16 | int64(src[3])<<24 | int64(src[4])<<32 | int64(src[5])<<40 | int64(src[6])<<48 | int64(src[7])<<56, src[8:], nil
}

func _intercallenc_uint8_77a42def2538a018(buf []byte, v uint8) ([]byte, error) {
	return append(buf, byte(v)), nil
}

func _intercalldec_uint8_ebdba4a25c65fcd0(src []byte) (uint8, []byte, error) {
	if len(src) < 1 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint8(src[0]), src[1:], nil
}

func _intercallenc_uint16_849a1e5c3f37fcd5(buf []byte, v uint16) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8)), nil
}

func _intercalldec_uint16_2c3598e3014ca48d(src []byte) (uint16, []byte, error) {
	if len(src) < 2 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint16(src[0]) | uint16(src[1])<<8, src[2:], nil
}

func _intercallenc_uint32_849a205c3f38007b(buf []byte, v uint32) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)), nil
}

func _intercalldec_uint32_2c359ae3014ca813(src []byte) (uint32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint32(src[0]) | uint32(src[1])<<8 | uint32(src[2])<<16 | uint32(src[3])<<24, src[4:], nil
}

func _intercallenc_uint64_849a235c3f380556(buf []byte, v uint64) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56)), nil
}

func _intercalldec_uint64_2c359de3014cad0e(src []byte) (uint64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint64(src[0]) | uint64(src[1])<<8 | uint64(src[2])<<16 | uint64(src[3])<<24 | uint64(src[4])<<32 | uint64(src[5])<<40 | uint64(src[6])<<48 | uint64(src[7])<<56, src[8:], nil
}

func _intercallenc_float32_6a8f4eea7f75b7d9(buf []byte, v float32) ([]byte, error) {
	var bits uint32
	if v != v {
		bits = 0x7fc00000
	} else {
		bits = math.Float32bits(v)
	}
	return append(buf, byte(bits), byte(bits>>8), byte(bits>>16), byte(bits>>24)), nil
}

func _intercalldec_float32_a273938b3b463041(src []byte) (float32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	bits := uint32(src[0]) | uint32(src[1])<<8 | uint32(src[2])<<16 | uint32(src[3])<<24
	v := math.Float32frombits(bits)
	if v != v && bits != 0x7fc00000 {
		return 0, nil, _intercallerror_nan_81e7acbc891a3841
	}
	return v, src[4:], nil
}

func _intercallenc_float64_6a8f51ea7f75bd30(buf []byte, v float64) ([]byte, error) {
	var bits uint64
	if v != v {
		bits = 0x7ff8000000000000
	} else {
		bits = math.Float64bits(v)
	}
	return append(buf, byte(bits), byte(bits>>8), byte(bits>>16), byte(bits>>24), byte(bits>>32), byte(bits>>40), byte(bits>>48), byte(bits>>56)), nil
}

func _intercalldec_float64_a273968b3b4635b8(src []byte) (float64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	bits := uint64(src[0]) | uint64(src[1])<<8 | uint64(src[2])<<16 | uint64(src[3])<<24 |
		uint64(src[4])<<32 | uint64(src[5])<<40 | uint64(src[6])<<48 | uint64(src[7])<<56
	v := math.Float64frombits(bits)
	if v != v && bits != 0x7ff8000000000000 {
		return 0, nil, _intercallerror_nan_81e7acbc891a3841
	}
	return v, src[8:], nil
}

func _intercallenc_string_00f359e600d57533(buf []byte, v string) ([]byte, error) {
	if !utf8.ValidString(v) {
		return nil, _intercallerror_utf8_21fa605c915dede7
	}
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return append(buf, v...), nil
}

func _intercalldec_string_e113d3e53c0a20ab(src []byte) (string, []byte, error) {
	n64, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return "", nil, err
	}
	if n64 > uint64(len(src)) {
		return "", nil, _intercallerror_long_e8fb175d020577b4
	}
	n := int(n64)
	b := src[:n]
	if !utf8.Valid(b) {
		return "", nil, _intercallerror_utf8_21fa605c915dede7
	}
	return string(b), src[n:], nil
}

func _intercallenc_bytes_6b87e24ef38333c9(buf []byte, v []byte) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return append(buf, v...), nil
}

func _intercalldec_bytes_dc8f190227fa8a41(src []byte) ([]byte, []byte, error) {
	n64, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return nil, nil, err
	}
	if n64 > uint64(len(src)) {
		return nil, nil, _intercallerror_long_e8fb175d020577b4
	}
	n := int(n64)
	dst := make([]byte, n)
	copy(dst, src[:n])
	return dst, src[n:], nil
}

func _intercallenc_type_user_id_6d1e6a3f9ce24d1b(buf []byte, v UserID) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_user_id_3126e3c36ce2c1e3(src []byte) (UserID, []byte, error) {
	v, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return UserID(v), nil, err
	}
	return UserID(v), src, nil
}
func _intercallenc_type_name_bd7f3efdad3b4199(buf []byte, v Name) ([]byte, error) {
	var err error
	buf, err = _intercallenc_string_00f359e600d57533(buf, string(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_name_83b24444a367a371(src []byte) (Name, []byte, error) {
	v, src, err := _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return Name(v), nil, err
	}
	return Name(v), src, nil
}
func _intercallenc_type_point_41c85497633e6c1a(buf []byte, v Point) ([]byte, error) {
	var err error
	buf, err = _intercallenc_float64_6a8f51ea7f75bd30(buf, v.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_float64_6a8f51ea7f75bd30(buf, v.Y)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_point_13bb84b3d4b45cd2(src []byte) (Point, []byte, error) {
	var v Point
	var err error
	v.X, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v, nil, err
	}
	v.Y, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_type_pixel_0b7c359743d44ca0(buf []byte, v Pixel) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Red)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Green)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Blue)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_pixel_e142b5b3b88abfb8(src []byte) (Pixel, []byte, error) {
	var v Pixel
	var err error
	v.Red, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Green, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Blue, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_type_empty_d7948148fc4b8663(buf []byte, v Empty) ([]byte, error) {
	return buf, nil
}

func _intercalldec_type_empty_ebbde05522390e0b(src []byte) (Empty, []byte, error) {
	return Empty{}, src, nil
}
func _intercallenc_type_names_3a79a20d5bb07688(buf []byte, v Names) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_string_00f359e600d57533(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_type_names_2f8d71a1a91ab970(src []byte) (Names, []byte, error) {
	var v Names
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]string, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_string_e113d3e53c0a20ab(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_type_matrix_963182a3387ab87b(buf []byte, v Matrix) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v[i0])))
		if err != nil {
			return nil, err
		}
		for i1 := range v[i0] {
			buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v[i0][i1])
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func _intercalldec_type_matrix_e9b99b4c3dfe24c3(src []byte) (Matrix, []byte, error) {
	var v Matrix
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([][]int32, int(count0))
	for i2 := range v {
		var count1 uint64
		count1, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
		if err != nil {
			return v, nil, err
		}
		if count1 > uint64(len(src)) {
			return v, nil, _intercallerror_long_e8fb175d020577b4
		}
		v[i2] = make([]int32, int(count1))
		for i3 := range v[i2] {
			v[i2][i3], src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
			if err != nil {
				return v, nil, err
			}
		}
	}
	return v, src, nil
}
func _intercallenc_type_blob_e1acc4fdc2289b89(buf []byte, v Blob) ([]byte, error) {
	var err error
	buf, err = _intercallenc_bytes_6b87e24ef38333c9(buf, []byte(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_blob_1af15a4467d7d621(src []byte) (Blob, []byte, error) {
	v, src, err := _intercalldec_bytes_dc8f190227fa8a41(src)
	if err != nil {
		return Blob(v), nil, err
	}
	return Blob(v), src, nil
}
func _intercallenc_type_customer_id_26df84587197fe58(buf []byte, v CustomerID) ([]byte, error) {
	var err error
	buf, err = _intercallenc_type_user_id_6d1e6a3f9ce24d1b(buf, UserID(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_customer_id_cf0fae21aea14a40(src []byte) (CustomerID, []byte, error) {
	v, src, err := _intercalldec_type_user_id_3126e3c36ce2c1e3(src)
	if err != nil {
		return CustomerID(v), nil, err
	}
	return CustomerID(v), src, nil
}
func _intercallenc_list_int32_bffe8cff3a38138c(buf []byte, v []int32) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_int32_1de55c1b573cff84(src []byte) ([]int32, []byte, error) {
	var v []int32
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]int32, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_record_code_int32_message_string__a7b4fae790da6661(buf []byte, v struct {
	Code    int32  `intercall:"code"`
	Message string `intercall:"message"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Code)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_string_00f359e600d57533(buf, v.Message)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_code_int32_message_string__d2d6ef92f192a229(src []byte) (struct {
	Code    int32  `intercall:"code"`
	Message string `intercall:"message"`
}, []byte, error) {
	var v struct {
		Code    int32  `intercall:"code"`
		Message string `intercall:"message"`
	}
	var err error
	v.Code, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Message, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_list_pixel_63242fb2a56c0840(buf []byte, v []Pixel) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_type_pixel_0b7c359743d44ca0(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_pixel_d79ede49fcfaed08(src []byte) ([]Pixel, []byte, error) {
	var v []Pixel
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]Pixel, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_type_pixel_e142b5b3b88abfb8(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_list_name_4d2b88778f7128b9(buf []byte, v []Name) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_type_name_bd7f3efdad3b4199(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_name_3867292ea6a4d1e1(src []byte) ([]Name, []byte, error) {
	var v []Name
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]Name, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_type_name_83b24444a367a371(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_list_string_559587cd4b72967b(buf []byte, v []string) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_string_00f359e600d57533(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_string_2f1a4c8650edf423(src []byte) ([]string, []byte, error) {
	var v []string
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]string, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_string_e113d3e53c0a20ab(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_record_x_int32_y_int32__41afb291be0604b7(buf []byte, v struct {
	X int32 `intercall:"x"`
	Y int32 `intercall:"y"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Y)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_x_int32_y_int32__593ba06c025edc9f(src []byte) (struct {
	X int32 `intercall:"x"`
	Y int32 `intercall:"y"`
}, []byte, error) {
	var v struct {
		X int32 `intercall:"x"`
		Y int32 `intercall:"y"`
	}
	var err error
	v.X, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Y, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_red_uint8_green_uint8_blue_uint8_alpha_uint8__cf654ceef4d00730(buf []byte, v struct {
	Red   uint8 `intercall:"red"`
	Green uint8 `intercall:"green"`
	Blue  uint8 `intercall:"blue"`
	Alpha uint8 `intercall:"alpha"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Red)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Green)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Blue)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Alpha)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_red_uint8_green_uint8_blue_uint8_alpha_uint8__5de9c982f7831268(src []byte) (struct {
	Red   uint8 `intercall:"red"`
	Green uint8 `intercall:"green"`
	Blue  uint8 `intercall:"blue"`
	Alpha uint8 `intercall:"alpha"`
}, []byte, error) {
	var v struct {
		Red   uint8 `intercall:"red"`
		Green uint8 `intercall:"green"`
		Blue  uint8 `intercall:"blue"`
		Alpha uint8 `intercall:"alpha"`
	}
	var err error
	v.Red, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Green, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Blue, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Alpha, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_width_uint32_height_uint32__73d0043a1c2de279(buf []byte, v struct {
	Width  uint32 `intercall:"width"`
	Height uint32 `intercall:"height"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint32_849a205c3f38007b(buf, v.Width)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint32_849a205c3f38007b(buf, v.Height)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_width_uint32_height_uint32__781395a0cd400f01(src []byte) (struct {
	Width  uint32 `intercall:"width"`
	Height uint32 `intercall:"height"`
}, []byte, error) {
	var v struct {
		Width  uint32 `intercall:"width"`
		Height uint32 `intercall:"height"`
	}
	var err error
	v.Width, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v, nil, err
	}
	v.Height, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_corner_record_x_int32_y_int32__label_string__b203f8a78d3cc9f9(buf []byte, v struct {
	Corner struct {
		X int32 `intercall:"x"`
		Y int32 `intercall:"y"`
	} `intercall:"corner"`
	Label string `intercall:"label"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Corner.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Corner.Y)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_string_00f359e600d57533(buf, v.Label)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_corner_record_x_int32_y_int32__label_string__6be99887be9b4b81(src []byte) (struct {
	Corner struct {
		X int32 `intercall:"x"`
		Y int32 `intercall:"y"`
	} `intercall:"corner"`
	Label string `intercall:"label"`
}, []byte, error) {
	var v struct {
		Corner struct {
			X int32 `intercall:"x"`
			Y int32 `intercall:"y"`
		} `intercall:"corner"`
		Label string `intercall:"label"`
	}
	var err error
	v.Corner.X, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Corner.Y, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Label, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_corner_point_area_uint64__fe03dcc11a369e9e(buf []byte, v struct {
	Corner Point  `intercall:"corner"`
	Area   uint64 `intercall:"area"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_type_point_41c85497633e6c1a(buf, v.Corner)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, v.Area)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_corner_point_area_uint64__120d065a8d4da466(src []byte) (struct {
	Corner Point  `intercall:"corner"`
	Area   uint64 `intercall:"area"`
}, []byte, error) {
	var v struct {
		Corner Point  `intercall:"corner"`
		Area   uint64 `intercall:"area"`
	}
	var err error
	v.Corner, src, err = _intercalldec_type_point_13bb84b3d4b45cd2(src)
	if err != nil {
		return v, nil, err
	}
	v.Area, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_list_record_row_uint16_col_uint16_value_int64__abccb8f8f322ebc3(buf []byte, v []struct {
	Row   uint16 `intercall:"row"`
	Col   uint16 `intercall:"col"`
	Value int64  `intercall:"value"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_uint16_849a1e5c3f37fcd5(buf, v[i0].Row)
		if err != nil {
			return nil, err
		}
		buf, err = _intercallenc_uint16_849a1e5c3f37fcd5(buf, v[i0].Col)
		if err != nil {
			return nil, err
		}
		buf, err = _intercallenc_int64_e7f52489efcdea71(buf, v[i0].Value)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_record_row_uint16_col_uint16_value_int64__92cce3b29e86374b(src []byte) ([]struct {
	Row   uint16 `intercall:"row"`
	Col   uint16 `intercall:"col"`
	Value int64  `intercall:"value"`
}, []byte, error) {
	var v []struct {
		Row   uint16 `intercall:"row"`
		Col   uint16 `intercall:"col"`
		Value int64  `intercall:"value"`
	}
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]struct {
		Row   uint16 `intercall:"row"`
		Col   uint16 `intercall:"col"`
		Value int64  `intercall:"value"`
	}, int(count0))
	for i1 := range v {
		v[i1].Row, src, err = _intercalldec_uint16_2c3598e3014ca48d(src)
		if err != nil {
			return v, nil, err
		}
		v[i1].Col, src, err = _intercalldec_uint16_2c3598e3014ca48d(src)
		if err != nil {
			return v, nil, err
		}
		v[i1].Value, src, err = _intercalldec_int64_b1e23aba3828fe59(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_record_row_uint16_col_uint16_value_int64__4cc66698d5ed09bb(buf []byte, v struct {
	Row   uint16 `intercall:"row"`
	Col   uint16 `intercall:"col"`
	Value int64  `intercall:"value"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint16_849a1e5c3f37fcd5(buf, v.Row)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint16_849a1e5c3f37fcd5(buf, v.Col)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_int64_e7f52489efcdea71(buf, v.Value)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_row_uint16_col_uint16_value_int64__f9ea86f3c51d7353(src []byte) (struct {
	Row   uint16 `intercall:"row"`
	Col   uint16 `intercall:"col"`
	Value int64  `intercall:"value"`
}, []byte, error) {
	var v struct {
		Row   uint16 `intercall:"row"`
		Col   uint16 `intercall:"col"`
		Value int64  `intercall:"value"`
	}
	var err error
	v.Row, src, err = _intercalldec_uint16_2c3598e3014ca48d(src)
	if err != nil {
		return v, nil, err
	}
	v.Col, src, err = _intercalldec_uint16_2c3598e3014ca48d(src)
	if err != nil {
		return v, nil, err
	}
	v.Value, src, err = _intercalldec_int64_b1e23aba3828fe59(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_list_uint8_fbe83adc98d1de40(buf []byte, v []uint8) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_uint8_77a42def2538a018(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_uint8_85ffe9748dbe7ae8(src []byte) ([]uint8, []byte, error) {
	var v []uint8
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]uint8, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_record___15061e0cdb39bf87(buf []byte, v struct{}) ([]byte, error) {
	return buf, nil
}

func _intercalldec_record___02611fdc3522b7cf(src []byte) (struct{}, []byte, error) {
	return struct{}{}, src, nil
}
func _intercallenc_list_empty_2f3b7b645de18e03(buf []byte, v []Empty) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_list_empty_0ca829f76819e63b(src []byte) ([]Empty, []byte, error) {
	var v []Empty
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(_intercallmaxint_a986121adce7d8c5) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]Empty, int(count0))
	return v, src, nil
}
func _intercallenc_record_tag_empty_code_uint32__8db90607c139874f(buf []byte, v struct {
	Tag  Empty  `intercall:"tag"`
	Code uint32 `intercall:"code"`
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint32_849a205c3f38007b(buf, v.Code)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_tag_empty_code_uint32__8512c245185964e7(src []byte) (struct {
	Tag  Empty  `intercall:"tag"`
	Code uint32 `intercall:"code"`
}, []byte, error) {
	var v struct {
		Tag  Empty  `intercall:"tag"`
		Code uint32 `intercall:"code"`
	}
	var err error
	v.Code, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
