// Code generated by intercall-ts; DO NOT EDIT.
// intercall-ts binding: export sha256:0000000000000000000000000000000000000000000000000000000000000000

export const exportBinding = Object.freeze({});
