import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, basename, join } from "node:path";

export type ArtifactKind = "import" | "export";

export function artifactStamp(body: Uint8Array | string): string {
    return createHash("sha256").update(body).digest("hex");
}

export function generatedHeader(kind: ArtifactKind, stamp: string): string {
    return `// Code generated by intercall-ts; DO NOT EDIT.\n// intercall-ts binding: ${kind} sha256:${stamp}\n`;
}

export function generatedInterfaceHeader(stamp: string): string {
    return `/* Code generated by intercall-ts; artifact sha256:${stamp}; DO NOT EDIT. */\n\n`;
}

export async function validateOutputDirectory(path: string): Promise<void> {
    let current;
    try { current = await lstat(path); } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
        throw error;
    }
    if (!current.isDirectory() || current.isSymbolicLink()) throw new Error(`output path is not a regular directory: ${path}`);
    for (const entry of await readdir(path, { withFileTypes: true })) {
        if (entry.isFile() && /\.(?:ts|tsx|js|jsx)$/u.test(entry.name) && entry.name !== "binding_gen.ts") throw new Error(`output directory contains an unowned code file: ${entry.name}`);
        if (entry.isSymbolicLink() && entry.name === "binding_gen.ts") throw new Error("output binding is a symlink");
    }
}

export async function assertReplaceableLeaf(path: string, kind: ArtifactKind, _expectedBody: Uint8Array): Promise<void> {
    let current;
    try { current = await lstat(path); } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
        throw error;
    }
    if (!current.isFile() || current.isSymbolicLink()) throw new Error(`target is not a replaceable regular file: ${path}`);
    const lines = (await readFile(path)).toString("utf8").split("\n");
    if (lines[0] !== generatedHeader(kind, "").split("\n")[0]) throw new Error(`target is not owned by intercall-ts: ${path}`);
    const match = /^\/\/ intercall-ts binding: (import|export) sha256:([0-9a-f]{64})$/u.exec(lines[1] ?? "");
    if (match === null || match[1] !== kind) throw new Error(`target has an invalid ownership marker: ${path}`);
    if (artifactStamp(lines.slice(2).join("\n")) !== match[2]) throw new Error(`target ownership stamp does not match: ${path}`);
}

export async function replaceOwnedLeaf(path: string, kind: ArtifactKind, body: Uint8Array): Promise<void> {
    await assertReplaceableLeaf(path, kind, body);
    await replaceBytes(path, Buffer.concat([Buffer.from(generatedHeader(kind, artifactStamp(body))), Buffer.from(body)]));
}

export async function replaceOwnedInterface(path: string, body: Uint8Array): Promise<void> {
    let current;
    try { current = await lstat(path); } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") current = undefined;
        else throw error;
    }
    if (current !== undefined) {
        if (!current.isFile() || current.isSymbolicLink()) throw new Error(`target is not a replaceable regular file: ${path}`);
        const text = (await readFile(path)).toString("utf8");
        const match = /^\/\* Code generated by intercall-ts; artifact sha256:([0-9a-f]{64}); DO NOT EDIT\. \*\/\n\n/u.exec(text);
        if (match === null || artifactStamp(text.slice(match[0].length)) !== match[1]) throw new Error(`target interface ownership is invalid: ${path}`);
    }
    await replaceBytes(path, Buffer.concat([Buffer.from(generatedInterfaceHeader(artifactStamp(body))), Buffer.from(body)]));
}

async function replaceBytes(path: string, output: Buffer): Promise<void> {
    try {
        if ((await readFile(path)).equals(output)) return;
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    await mkdir(dirname(path), { recursive: true });
    const stage = join(dirname(path), `.${basename(path)}.intercall-stage-${process.pid}`);
    try {
        await writeFile(stage, output, { flag: "wx" });
        await rename(stage, path);
    } finally {
        await rm(stage, { force: true });
    }
}
