import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, basename, join } from "node:path";

export type ArtifactKind = "import" | "export";

export function artifactStamp(body: Uint8Array | string): string {
    return createHash("sha256").update(body).digest("hex");
}

export function generatedHeader(kind: ArtifactKind, stamp: string): string {
    return `// Code generated by intercall-ts; DO NOT EDIT.\n// intercall-ts binding: ${kind} sha256:${stamp}\n`;
}

export async function assertReplaceableLeaf(path: string, kind: ArtifactKind, expectedBody: Uint8Array): Promise<void> {
    let current;
    try { current = await lstat(path); } catch (error) {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
        throw error;
    }
    if (!current.isFile() || current.isSymbolicLink()) throw new Error(`target is not a replaceable regular file: ${path}`);
    const bytes = await readFile(path);
    const text = bytes.toString("utf8");
    const lines = text.split("\n");
    const marker = generatedHeader(kind, "").split("\n")[0];
    if (lines[0] !== marker) throw new Error(`target is not owned by intercall-ts: ${path}`);
    const match = /^\/\/ intercall-ts binding: (import|export) sha256:([0-9a-f]{64})$/u.exec(lines[1] ?? "");
    if (match === null || match[1] !== kind) throw new Error(`target has an invalid ownership marker: ${path}`);
    const existingBody = lines.slice(2).join("\n");
    if (artifactStamp(existingBody) !== match[2]) throw new Error(`target ownership stamp does not match: ${path}`);
}

export async function replaceOwnedLeaf(path: string, kind: ArtifactKind, body: Uint8Array): Promise<void> {
    await assertReplaceableLeaf(path, kind, body);
    const output = Buffer.concat([Buffer.from(generatedHeader(kind, artifactStamp(body))), Buffer.from(body)]);
    try {
        if ((await readFile(path)).equals(output)) return;
    } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    await mkdir(dirname(path), { recursive: true });
    const stage = join(dirname(path), `.${basename(path)}.intercall-stage-${process.pid}`);
    try {
        await writeFile(stage, output, { flag: "wx" });
        await rename(stage, path);
    } finally {
        await rm(stage, { force: true });
    }
}
