// Package exportfixture is the compiled export-binding fixture of
// internal/tool.
//
// binding_gen.go is generated byte-for-byte by the export emitter from
// the provider fixture package internal/tool/exportfixture/prov
// through the complete discovery, model, and artifact pipeline; tests
// regenerate it and verify the checked-in file never drifts. This file
// is the handwritten test surface: it exposes the generated dispatch,
// the immutable export binding, the request decoders, the codec pairs,
// and the codec error sentinels, plus Go type aliases for the
// anonymous inline records, so generation, runtime, and fuzz tests can
// use them without spelling generated internals.
package exportfixture

import (
	"github.com/cerasos/intercall"
	"github.com/cerasos/intercall/internal/tool/exportfixture/prov"
)

// Dispatch exposes the generated static procedure switch.
var Dispatch intercall.Dispatch = _intercalldispatch_6ba7a6d72caedc56

// ExportBindingHandle exposes the generated immutable export binding
// singleton, for identity tests.
var ExportBindingHandle = _intercallbinding_47f982b7aff8567b

// Go type aliases for the anonymous inline records of the fixture
// interface. The generated functions spell these struct types inline;
// the aliases are identical types.
type (
	// PaintOrigin is record { x int32; y int32; }, the paint origin
	// parameter.
	PaintOrigin = struct {
		X int32
		Y int32
	}
	// PaintSize is record { width uint32; height uint32; }, the paint
	// size parameter.
	PaintSize = struct {
		Width  uint32
		Height uint32
	}
	// PaintResult is record { width uint32; height uint32; }, the
	// paint return value. It shares its wire structure and Go type
	// with PaintSize, so the two occurrences share one codec pair.
	PaintResult = struct {
		Width  uint32
		Height uint32
	}
)

// Error sentinels of the generated codecs.
var (
	ErrTruncated = _intercallerror_short_8e6f381b5f48ed3c // fewer bytes than a fixed-width value
	ErrTooLong   = _intercallerror_long_e8fb175d020577b4  // declared length or count exceeds the payload
	ErrNaN       = _intercallerror_nan_81e7acbc891a3841   // noncanonical NaN bit pattern
	ErrUTF8      = _intercallerror_utf8_21fa605c915dede7  // invalid UTF-8 in a string
)

// Codecs exposes the generated codec pairs of the fixture interface
// that the runtime and decoder tests need. Encoders append one value
// to an owned payload; decoders return the value with the exact
// unconsumed remainder.
var Codecs = struct {
	EncodeString        func([]byte, string) ([]byte, error)
	DecodeString        func([]byte) (string, []byte, error)
	EncodeInt64         func([]byte, int64) ([]byte, error)
	DecodeInt64         func([]byte) (int64, []byte, error)
	EncodeUint8         func([]byte, uint8) ([]byte, error)
	DecodeUint8         func([]byte) (uint8, []byte, error)
	EncodeUint32        func([]byte, uint32) ([]byte, error)
	DecodeUint32        func([]byte) (uint32, []byte, error)
	EncodeUint64        func([]byte, uint64) ([]byte, error)
	DecodeUint64        func([]byte) (uint64, []byte, error)
	EncodeBytes         func([]byte, []byte) ([]byte, error)
	DecodeBytes         func([]byte) ([]byte, []byte, error)
	EncodeListUint8     func([]byte, []uint8) ([]byte, error)
	DecodeListUint8     func([]byte) ([]uint8, []byte, error)
	EncodeUserID        func([]byte, prov.UserID) ([]byte, error)
	DecodeUserID        func([]byte) (prov.UserID, []byte, error)
	EncodePoint         func([]byte, prov.Point) ([]byte, error)
	DecodePoint         func([]byte) (prov.Point, []byte, error)
	EncodePaintOrigin   func([]byte, PaintOrigin) ([]byte, error)
	DecodePaintOrigin   func([]byte) (PaintOrigin, []byte, error)
	EncodePaintSize     func([]byte, PaintSize) ([]byte, error)
	DecodePaintSize     func([]byte) (PaintSize, []byte, error)
	EncodePaintResult   func([]byte, PaintResult) ([]byte, error)
	DecodePaintResult   func([]byte) (PaintResult, []byte, error)
	EncodeFailedPayload func([]byte, prov.Failed) ([]byte, error)
	DecodeFailedPayload func([]byte) (prov.Failed, []byte, error)
	EncodeSharedPayload func([]byte, prov.Shared) ([]byte, error)
	DecodeSharedPayload func([]byte) (prov.Shared, []byte, error)
}{
	EncodeString:        _intercallenc_string_00f359e600d57533,
	DecodeString:        _intercalldec_string_e113d3e53c0a20ab,
	EncodeInt64:         _intercallenc_int64_e7f52489efcdea71,
	DecodeInt64:         _intercalldec_int64_b1e23aba3828fe59,
	EncodeUint8:         _intercallenc_uint8_77a42def2538a018,
	DecodeUint8:         _intercalldec_uint8_ebdba4a25c65fcd0,
	EncodeUint32:        _intercallenc_uint32_849a205c3f38007b,
	DecodeUint32:        _intercalldec_uint32_2c359ae3014ca813,
	EncodeUint64:        _intercallenc_uint64_849a235c3f380556,
	DecodeUint64:        _intercalldec_uint64_2c359de3014cad0e,
	EncodeBytes:         _intercallenc_bytes_6b87e24ef38333c9,
	DecodeBytes:         _intercalldec_bytes_dc8f190227fa8a41,
	EncodeListUint8:     _intercallenc_list_uint8___uint8_f5408e3ade976024,
	DecodeListUint8:     _intercalldec_list_uint8___uint8_ed36b3402c96257c,
	EncodeUserID:        _intercallenc_type_user_id_6d1e6a3f9ce24d1b,
	DecodeUserID:        _intercalldec_type_user_id_3126e3c36ce2c1e3,
	EncodePoint:         _intercallenc_type_point_41c85497633e6c1a,
	DecodePoint:         _intercalldec_type_point_13bb84b3d4b45cd2,
	EncodePaintOrigin:   _intercallenc_record_x_int32_y_int32__struct____X_int32__Y_int32___412839956ef1eb69,
	DecodePaintOrigin:   _intercalldec_record_x_int32_y_int32__struct____X_int32__Y_int32___64520c53ce0ee831,
	EncodePaintSize:     _intercallenc_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___5f07b5088bd2f3e3,
	DecodePaintSize:     _intercalldec_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___3337324db410126b,
	EncodePaintResult:   _intercallenc_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___5f07b5088bd2f3e3,
	DecodePaintResult:   _intercalldec_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___3337324db410126b,
	EncodeFailedPayload: _intercallenc_record_code_int32_message_string__prov_Failed_d65a7df1fbfd9bb7,
	DecodeFailedPayload: _intercalldec_record_code_int32_message_string__prov_Failed_e598e6e4369976bf,
	EncodeSharedPayload: _intercallenc_record_code_int32__prov_Shared_2cc18b0044d7fe08,
	DecodeSharedPayload: _intercalldec_record_code_int32__prov_Shared_874999387e5902b0,
}

// Requests exposes the generated request decoder of every fixture
// procedure through one uniform signature. Each decoder decodes the
// wire parameters in declaration order and returns them with the exact
// unconsumed remainder and the decoder error; the dispatch turns every
// decoder error and every nonempty remainder into the fixed
// invalid_arguments exception without invoking the provider.
var Requests = struct {
	DecodeAdd    func([]byte) (int64, int64, []byte, error)
	DecodeCrash  func([]byte) (string, []byte, error)
	DecodeEcho   func([]byte) (string, []byte, error)
	DecodeFetch  func([]byte) (prov.UserID, []byte, error)
	DecodePaint  func([]byte) (PaintOrigin, PaintSize, []byte, error)
	DecodePing   func([]byte) ([]byte, error)
	DecodeSample func([]byte) ([]byte, uint8, []byte, error)
	DecodeWave   func([]byte) ([]uint8, []byte, error)
}{
	DecodeAdd:    _intercalldereq_add_785d921dde991182,
	DecodeCrash:  _intercalldereq_crash_94c3b54ff311327a,
	DecodeEcho:   _intercalldereq_echo_447474c15333e61e,
	DecodeFetch:  _intercalldereq_fetch_6e77f47583666d7f,
	DecodePaint:  _intercalldereq_paint_793e81eb864e04e3,
	DecodePing:   _intercalldereq_ping_b41a89c1922b222d,
	DecodeSample: _intercalldereq_sample_5f17e8dec708cf23,
	DecodeWave:   _intercalldereq_wave_bc0cbcc196779c26,
}
