// Package fixture is the compiled codec fixture of internal/tool.
//
// codec_gen.go is generated byte-for-byte by the codec emitter from
// internal/tool/testdata/fixture.intercall; tests in internal/tool
// regenerate it in memory and verify the checked-in file never drifts.
// This file is the handwritten test surface: it exposes the generated
// private codec functions, their error sentinels, and Go type aliases for
// the anonymous inline records, so wire-vector, round-trip, malformed,
// and fuzz tests can use them without spelling generated internals.
package fixture

// Go type aliases for the anonymous inline records of the fixture
// interface. The generated functions spell these struct types inline with
// their exact intercall tags; the aliases are identical types.
type (
	// RecordXY is record { x int32; y int32; }, the paint origin and
	// locate corner.
	RecordXY = struct {
		X int32 `intercall:"x"`
		Y int32 `intercall:"y"`
	}
	// RecordRGBA is record { red uint8; green uint8; blue uint8;
	// alpha uint8; }, the paint color.
	RecordRGBA = struct {
		Red   uint8 `intercall:"red"`
		Green uint8 `intercall:"green"`
		Blue  uint8 `intercall:"blue"`
		Alpha uint8 `intercall:"alpha"`
	}
	// RecordWH is record { width uint32; height uint32; }, the paint
	// result.
	RecordWH = struct {
		Width  uint32 `intercall:"width"`
		Height uint32 `intercall:"height"`
	}
	// LocateBox is record { corner record { x int32; y int32; }; label
	// string; }.
	LocateBox = struct {
		Corner RecordXY `intercall:"corner"`
		Label  string   `intercall:"label"`
	}
	// LocateResult is record { corner point; area uint64; }.
	LocateResult = struct {
		Corner Point  `intercall:"corner"`
		Area   uint64 `intercall:"area"`
	}
	// GridRow is record { row uint16; col uint16; value int64; }.
	GridRow = struct {
		Row   uint16 `intercall:"row"`
		Col   uint16 `intercall:"col"`
		Value int64  `intercall:"value"`
	}
	// FailedPayload is the payload record of exception failed.
	FailedPayload = struct {
		Code    int32  `intercall:"code"`
		Message string `intercall:"message"`
	}
	// TinyNote is record { tag empty; code uint32; }, a record with one
	// zero-width field.
	TinyNote = struct {
		Tag  Empty  `intercall:"tag"`
		Code uint32 `intercall:"code"`
	}
	// RecordEmpty is record {}.
	RecordEmpty = struct{}
)

// Error sentinels of the generated codecs.
var (
	ErrTruncated = _intercallerror_short_8e6f381b5f48ed3c // fewer bytes than a fixed-width value
	ErrTooLong   = _intercallerror_long_e8fb175d020577b4  // declared length or count exceeds the payload
	ErrNaN       = _intercallerror_nan_81e7acbc891a3841   // noncanonical NaN bit pattern
	ErrUTF8      = _intercallerror_utf8_21fa605c915dede7  // invalid UTF-8 in a string
)

// Codecs exposes every generated codec pair. Encoders append one value to
// an owned payload; decoders return the value with the exact unconsumed
// remainder.
var Codecs = struct {
	EncodeInt8    func([]byte, int8) ([]byte, error)
	DecodeInt8    func([]byte) (int8, []byte, error)
	EncodeInt16   func([]byte, int16) ([]byte, error)
	DecodeInt16   func([]byte) (int16, []byte, error)
	EncodeInt32   func([]byte, int32) ([]byte, error)
	DecodeInt32   func([]byte) (int32, []byte, error)
	EncodeInt64   func([]byte, int64) ([]byte, error)
	DecodeInt64   func([]byte) (int64, []byte, error)
	EncodeUint8   func([]byte, uint8) ([]byte, error)
	DecodeUint8   func([]byte) (uint8, []byte, error)
	EncodeUint16  func([]byte, uint16) ([]byte, error)
	DecodeUint16  func([]byte) (uint16, []byte, error)
	EncodeUint32  func([]byte, uint32) ([]byte, error)
	DecodeUint32  func([]byte) (uint32, []byte, error)
	EncodeUint64  func([]byte, uint64) ([]byte, error)
	DecodeUint64  func([]byte) (uint64, []byte, error)
	EncodeFloat32 func([]byte, float32) ([]byte, error)
	DecodeFloat32 func([]byte) (float32, []byte, error)
	EncodeFloat64 func([]byte, float64) ([]byte, error)
	DecodeFloat64 func([]byte) (float64, []byte, error)
	EncodeString  func([]byte, string) ([]byte, error)
	DecodeString  func([]byte) (string, []byte, error)
	EncodeBytes   func([]byte, []byte) ([]byte, error)
	DecodeBytes   func([]byte) ([]byte, []byte, error)

	EncodeUserID     func([]byte, UserID) ([]byte, error)
	DecodeUserID     func([]byte) (UserID, []byte, error)
	EncodeName       func([]byte, Name) ([]byte, error)
	DecodeName       func([]byte) (Name, []byte, error)
	EncodePoint      func([]byte, Point) ([]byte, error)
	DecodePoint      func([]byte) (Point, []byte, error)
	EncodePixel      func([]byte, Pixel) ([]byte, error)
	DecodePixel      func([]byte) (Pixel, []byte, error)
	EncodeEmpty      func([]byte, Empty) ([]byte, error)
	DecodeEmpty      func([]byte) (Empty, []byte, error)
	EncodeNames      func([]byte, Names) ([]byte, error)
	DecodeNames      func([]byte) (Names, []byte, error)
	EncodeMatrix     func([]byte, Matrix) ([]byte, error)
	DecodeMatrix     func([]byte) (Matrix, []byte, error)
	EncodeBlob       func([]byte, Blob) ([]byte, error)
	DecodeBlob       func([]byte) (Blob, []byte, error)
	EncodeCustomerID func([]byte, CustomerID) ([]byte, error)
	DecodeCustomerID func([]byte) (CustomerID, []byte, error)

	EncodeListInt32     func([]byte, []int32) ([]byte, error)
	DecodeListInt32     func([]byte) ([]int32, []byte, error)
	EncodeFailedPayload func([]byte, FailedPayload) ([]byte, error)
	DecodeFailedPayload func([]byte) (FailedPayload, []byte, error)
	EncodeListPixel     func([]byte, []Pixel) ([]byte, error)
	DecodeListPixel     func([]byte) ([]Pixel, []byte, error)
	EncodeListName      func([]byte, []Name) ([]byte, error)
	DecodeListName      func([]byte) ([]Name, []byte, error)
	EncodeListString    func([]byte, []string) ([]byte, error)
	DecodeListString    func([]byte) ([]string, []byte, error)
	EncodeRecordXY      func([]byte, RecordXY) ([]byte, error)
	DecodeRecordXY      func([]byte) (RecordXY, []byte, error)
	EncodeRecordRGBA    func([]byte, RecordRGBA) ([]byte, error)
	DecodeRecordRGBA    func([]byte) (RecordRGBA, []byte, error)
	EncodeRecordWH      func([]byte, RecordWH) ([]byte, error)
	DecodeRecordWH      func([]byte) (RecordWH, []byte, error)
	EncodeLocateBox     func([]byte, LocateBox) ([]byte, error)
	DecodeLocateBox     func([]byte) (LocateBox, []byte, error)
	EncodeLocateResult  func([]byte, LocateResult) ([]byte, error)
	DecodeLocateResult  func([]byte) (LocateResult, []byte, error)
	EncodeGridRows      func([]byte, []GridRow) ([]byte, error)
	DecodeGridRows      func([]byte) ([]GridRow, []byte, error)
	EncodeGridRow       func([]byte, GridRow) ([]byte, error)
	DecodeGridRow       func([]byte) (GridRow, []byte, error)
	EncodeListUint8     func([]byte, []uint8) ([]byte, error)
	DecodeListUint8     func([]byte) ([]uint8, []byte, error)
	EncodeRecordEmpty   func([]byte, RecordEmpty) ([]byte, error)
	DecodeRecordEmpty   func([]byte) (RecordEmpty, []byte, error)
	EncodeListEmpty     func([]byte, []Empty) ([]byte, error)
	DecodeListEmpty     func([]byte) ([]Empty, []byte, error)
	EncodeTinyNote      func([]byte, TinyNote) ([]byte, error)
	DecodeTinyNote      func([]byte) (TinyNote, []byte, error)
}{
	EncodeInt8:    _intercallenc_int8_2b2537505a97b829,
	DecodeInt8:    _intercalldec_int8_8e851e84d785af51,
	EncodeInt16:   _intercallenc_int16_e7f51d89efcdde56,
	DecodeInt16:   _intercalldec_int16_b1e233ba3828f2be,
	EncodeInt32:   _intercallenc_int32_e7f51f89efcde1f4,
	DecodeInt32:   _intercalldec_int32_b1e235ba3828f5dc,
	EncodeInt64:   _intercallenc_int64_e7f52489efcdea71,
	DecodeInt64:   _intercalldec_int64_b1e23aba3828fe59,
	EncodeUint8:   _intercallenc_uint8_77a42def2538a018,
	DecodeUint8:   _intercalldec_uint8_ebdba4a25c65fcd0,
	EncodeUint16:  _intercallenc_uint16_849a1e5c3f37fcd5,
	DecodeUint16:  _intercalldec_uint16_2c3598e3014ca48d,
	EncodeUint32:  _intercallenc_uint32_849a205c3f38007b,
	DecodeUint32:  _intercalldec_uint32_2c359ae3014ca813,
	EncodeUint64:  _intercallenc_uint64_849a235c3f380556,
	DecodeUint64:  _intercalldec_uint64_2c359de3014cad0e,
	EncodeFloat32: _intercallenc_float32_6a8f4eea7f75b7d9,
	DecodeFloat32: _intercalldec_float32_a273938b3b463041,
	EncodeFloat64: _intercallenc_float64_6a8f51ea7f75bd30,
	DecodeFloat64: _intercalldec_float64_a273968b3b4635b8,
	EncodeString:  _intercallenc_string_00f359e600d57533,
	DecodeString:  _intercalldec_string_e113d3e53c0a20ab,
	EncodeBytes:   _intercallenc_bytes_6b87e24ef38333c9,
	DecodeBytes:   _intercalldec_bytes_dc8f190227fa8a41,

	EncodeUserID:     _intercallenc_type_user_id_6d1e6a3f9ce24d1b,
	DecodeUserID:     _intercalldec_type_user_id_3126e3c36ce2c1e3,
	EncodeName:       _intercallenc_type_name_bd7f3efdad3b4199,
	DecodeName:       _intercalldec_type_name_83b24444a367a371,
	EncodePoint:      _intercallenc_type_point_41c85497633e6c1a,
	DecodePoint:      _intercalldec_type_point_13bb84b3d4b45cd2,
	EncodePixel:      _intercallenc_type_pixel_0b7c359743d44ca0,
	DecodePixel:      _intercalldec_type_pixel_e142b5b3b88abfb8,
	EncodeEmpty:      _intercallenc_type_empty_d7948148fc4b8663,
	DecodeEmpty:      _intercalldec_type_empty_ebbde05522390e0b,
	EncodeNames:      _intercallenc_type_names_3a79a20d5bb07688,
	DecodeNames:      _intercalldec_type_names_2f8d71a1a91ab970,
	EncodeMatrix:     _intercallenc_type_matrix_963182a3387ab87b,
	DecodeMatrix:     _intercalldec_type_matrix_e9b99b4c3dfe24c3,
	EncodeBlob:       _intercallenc_type_blob_e1acc4fdc2289b89,
	DecodeBlob:       _intercalldec_type_blob_1af15a4467d7d621,
	EncodeCustomerID: _intercallenc_type_customer_id_26df84587197fe58,
	DecodeCustomerID: _intercalldec_type_customer_id_cf0fae21aea14a40,

	EncodeListInt32:     _intercallenc_list_int32_bffe8cff3a38138c,
	DecodeListInt32:     _intercalldec_list_int32_1de55c1b573cff84,
	EncodeFailedPayload: _intercallenc_record_code_int32_message_string__a7b4fae790da6661,
	DecodeFailedPayload: _intercalldec_record_code_int32_message_string__d2d6ef92f192a229,
	EncodeListPixel:     _intercallenc_list_pixel_63242fb2a56c0840,
	DecodeListPixel:     _intercalldec_list_pixel_d79ede49fcfaed08,
	EncodeListName:      _intercallenc_list_name_4d2b88778f7128b9,
	DecodeListName:      _intercalldec_list_name_3867292ea6a4d1e1,
	EncodeListString:    _intercallenc_list_string_559587cd4b72967b,
	DecodeListString:    _intercalldec_list_string_2f1a4c8650edf423,
	EncodeRecordXY:      _intercallenc_record_x_int32_y_int32__41afb291be0604b7,
	DecodeRecordXY:      _intercalldec_record_x_int32_y_int32__593ba06c025edc9f,
	EncodeRecordRGBA:    _intercallenc_record_red_uint8_green_uint8_blue_uint8_alpha_uint8__cf654ceef4d00730,
	DecodeRecordRGBA:    _intercalldec_record_red_uint8_green_uint8_blue_uint8_alpha_uint8__5de9c982f7831268,
	EncodeRecordWH:      _intercallenc_record_width_uint32_height_uint32__73d0043a1c2de279,
	DecodeRecordWH:      _intercalldec_record_width_uint32_height_uint32__781395a0cd400f01,
	EncodeLocateBox:     _intercallenc_record_corner_record_x_int32_y_int32__label_string__b203f8a78d3cc9f9,
	DecodeLocateBox:     _intercalldec_record_corner_record_x_int32_y_int32__label_string__6be99887be9b4b81,
	EncodeLocateResult:  _intercallenc_record_corner_point_area_uint64__fe03dcc11a369e9e,
	DecodeLocateResult:  _intercalldec_record_corner_point_area_uint64__120d065a8d4da466,
	EncodeGridRows:      _intercallenc_list_record_row_uint16_col_uint16_value_int64__abccb8f8f322ebc3,
	DecodeGridRows:      _intercalldec_list_record_row_uint16_col_uint16_value_int64__92cce3b29e86374b,
	EncodeGridRow:       _intercallenc_record_row_uint16_col_uint16_value_int64__4cc66698d5ed09bb,
	DecodeGridRow:       _intercalldec_record_row_uint16_col_uint16_value_int64__f9ea86f3c51d7353,
	EncodeListUint8:     _intercallenc_list_uint8_fbe83adc98d1de40,
	DecodeListUint8:     _intercalldec_list_uint8_85ffe9748dbe7ae8,
	EncodeRecordEmpty:   _intercallenc_record___15061e0cdb39bf87,
	DecodeRecordEmpty:   _intercalldec_record___02611fdc3522b7cf,
	EncodeListEmpty:     _intercallenc_list_empty_2f3b7b645de18e03,
	DecodeListEmpty:     _intercalldec_list_empty_0ca829f76819e63b,
	EncodeTinyNote:      _intercallenc_record_tag_empty_code_uint32__8db90607c139874f,
	DecodeTinyNote:      _intercalldec_record_tag_empty_code_uint32__8512c245185964e7,
}
