// Code generated by intercall-go; DO NOT EDIT.
// intercall-go binding: export sha256:ec88d7cc995138d903f338d73030e78769e95000e2f5be52385a36f1003e3707

package e2eexport

import (
	"context"
	"errors"
	"github.com/cerasos/intercall/go"
	"github.com/cerasos/intercall/go/internal/integration/fixtures/provider"
	"math"
	"unicode/utf8"
)

const _intercallmaxint_a986121adce7d8c5 = int(^uint(0) >> 1)

var (
	_intercallerror_long_e8fb175d020577b4  = errors.New("intercall: wire length exceeds available bytes")
	_intercallerror_nan_81e7acbc891a3841   = errors.New("intercall: noncanonical NaN bit pattern")
	_intercallerror_short_8e6f381b5f48ed3c = errors.New("intercall: truncated wire value")
	_intercallerror_utf8_21fa605c915dede7  = errors.New("intercall: string is not valid UTF-8")
)

func _intercallenc_int8_2b2537505a97b829(buf []byte, v int8) ([]byte, error) {
	return append(buf, byte(v)), nil
}

func _intercalldec_int8_8e851e84d785af51(src []byte) (int8, []byte, error) {
	if len(src) < 1 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int8(src[0]), src[1:], nil
}

func _intercallenc_int16_e7f51d89efcdde56(buf []byte, v int16) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8)), nil
}

func _intercalldec_int16_b1e233ba3828f2be(src []byte) (int16, []byte, error) {
	if len(src) < 2 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int16(src[0]) | int16(src[1])<<8, src[2:], nil
}

func _intercallenc_int32_e7f51f89efcde1f4(buf []byte, v int32) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)), nil
}

func _intercalldec_int32_b1e235ba3828f5dc(src []byte) (int32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int32(src[0]) | int32(src[1])<<8 | int32(src[2])<<16 | int32(src[3])<<24, src[4:], nil
}

func _intercallenc_int64_e7f52489efcdea71(buf []byte, v int64) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56)), nil
}

func _intercalldec_int64_b1e23aba3828fe59(src []byte) (int64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return int64(src[0]) | int64(src[1])<<8 | int64(src[2])<<16 | int64(src[3])<<24 | int64(src[4])<<32 | int64(src[5])<<40 | int64(src[6])<<48 | int64(src[7])<<56, src[8:], nil
}

func _intercallenc_uint8_77a42def2538a018(buf []byte, v uint8) ([]byte, error) {
	return append(buf, byte(v)), nil
}

func _intercalldec_uint8_ebdba4a25c65fcd0(src []byte) (uint8, []byte, error) {
	if len(src) < 1 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint8(src[0]), src[1:], nil
}

func _intercallenc_uint16_849a1e5c3f37fcd5(buf []byte, v uint16) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8)), nil
}

func _intercalldec_uint16_2c3598e3014ca48d(src []byte) (uint16, []byte, error) {
	if len(src) < 2 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint16(src[0]) | uint16(src[1])<<8, src[2:], nil
}

func _intercallenc_uint32_849a205c3f38007b(buf []byte, v uint32) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24)), nil
}

func _intercalldec_uint32_2c359ae3014ca813(src []byte) (uint32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint32(src[0]) | uint32(src[1])<<8 | uint32(src[2])<<16 | uint32(src[3])<<24, src[4:], nil
}

func _intercallenc_uint64_849a235c3f380556(buf []byte, v uint64) ([]byte, error) {
	return append(buf, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56)), nil
}

func _intercalldec_uint64_2c359de3014cad0e(src []byte) (uint64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	return uint64(src[0]) | uint64(src[1])<<8 | uint64(src[2])<<16 | uint64(src[3])<<24 | uint64(src[4])<<32 | uint64(src[5])<<40 | uint64(src[6])<<48 | uint64(src[7])<<56, src[8:], nil
}

func _intercallenc_float32_6a8f4eea7f75b7d9(buf []byte, v float32) ([]byte, error) {
	var bits uint32
	if v != v {
		bits = 0x7fc00000
	} else {
		bits = math.Float32bits(v)
	}
	return append(buf, byte(bits), byte(bits>>8), byte(bits>>16), byte(bits>>24)), nil
}

func _intercalldec_float32_a273938b3b463041(src []byte) (float32, []byte, error) {
	if len(src) < 4 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	bits := uint32(src[0]) | uint32(src[1])<<8 | uint32(src[2])<<16 | uint32(src[3])<<24
	v := math.Float32frombits(bits)
	if v != v && bits != 0x7fc00000 {
		return 0, nil, _intercallerror_nan_81e7acbc891a3841
	}
	return v, src[4:], nil
}

func _intercallenc_float64_6a8f51ea7f75bd30(buf []byte, v float64) ([]byte, error) {
	var bits uint64
	if v != v {
		bits = 0x7ff8000000000000
	} else {
		bits = math.Float64bits(v)
	}
	return append(buf, byte(bits), byte(bits>>8), byte(bits>>16), byte(bits>>24), byte(bits>>32), byte(bits>>40), byte(bits>>48), byte(bits>>56)), nil
}

func _intercalldec_float64_a273968b3b4635b8(src []byte) (float64, []byte, error) {
	if len(src) < 8 {
		return 0, nil, _intercallerror_short_8e6f381b5f48ed3c
	}
	bits := uint64(src[0]) | uint64(src[1])<<8 | uint64(src[2])<<16 | uint64(src[3])<<24 |
		uint64(src[4])<<32 | uint64(src[5])<<40 | uint64(src[6])<<48 | uint64(src[7])<<56
	v := math.Float64frombits(bits)
	if v != v && bits != 0x7ff8000000000000 {
		return 0, nil, _intercallerror_nan_81e7acbc891a3841
	}
	return v, src[8:], nil
}

func _intercallenc_string_00f359e600d57533(buf []byte, v string) ([]byte, error) {
	if !utf8.ValidString(v) {
		return nil, _intercallerror_utf8_21fa605c915dede7
	}
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return append(buf, v...), nil
}

func _intercalldec_string_e113d3e53c0a20ab(src []byte) (string, []byte, error) {
	n64, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return "", nil, err
	}
	if n64 > uint64(len(src)) {
		return "", nil, _intercallerror_long_e8fb175d020577b4
	}
	n := int(n64)
	b := src[:n]
	if !utf8.Valid(b) {
		return "", nil, _intercallerror_utf8_21fa605c915dede7
	}
	return string(b), src[n:], nil
}

func _intercallenc_bytes_6b87e24ef38333c9(buf []byte, v []byte) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return append(buf, v...), nil
}

func _intercalldec_bytes_dc8f190227fa8a41(src []byte) ([]byte, []byte, error) {
	n64, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return nil, nil, err
	}
	if n64 > uint64(len(src)) {
		return nil, nil, _intercallerror_long_e8fb175d020577b4
	}
	n := int(n64)
	dst := make([]byte, n)
	copy(dst, src[:n])
	return dst, src[n:], nil
}

func _intercallenc_type_blob_e1acc4fdc2289b89(buf []byte, v provider.Blob) ([]byte, error) {
	var err error
	buf, err = _intercallenc_bytes_6b87e24ef38333c9(buf, []byte(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_blob_1af15a4467d7d621(src []byte) (provider.Blob, []byte, error) {
	v, src, err := _intercalldec_bytes_dc8f190227fa8a41(src)
	if err != nil {
		return provider.Blob(v), nil, err
	}
	return provider.Blob(v), src, nil
}
func _intercallenc_type_empty_d7948148fc4b8663(buf []byte, v provider.Empty) ([]byte, error) {
	return buf, nil
}

func _intercalldec_type_empty_ebbde05522390e0b(src []byte) (provider.Empty, []byte, error) {
	return provider.Empty{}, src, nil
}
func _intercallenc_type_matrix_963182a3387ab87b(buf []byte, v provider.Matrix) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v[i0])))
		if err != nil {
			return nil, err
		}
		for i1 := range v[i0] {
			buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v[i0][i1])
			if err != nil {
				return nil, err
			}
		}
	}
	return buf, nil
}

func _intercalldec_type_matrix_e9b99b4c3dfe24c3(src []byte) (provider.Matrix, []byte, error) {
	var v provider.Matrix
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([][]int32, int(count0))
	for i2 := range v {
		var count1 uint64
		count1, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
		if err != nil {
			return v, nil, err
		}
		if count1 > uint64(len(src)) {
			return v, nil, _intercallerror_long_e8fb175d020577b4
		}
		v[i2] = make([]int32, int(count1))
		for i3 := range v[i2] {
			v[i2][i3], src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
			if err != nil {
				return v, nil, err
			}
		}
	}
	return v, src, nil
}
func _intercallenc_type_name_bd7f3efdad3b4199(buf []byte, v provider.Name) ([]byte, error) {
	var err error
	buf, err = _intercallenc_string_00f359e600d57533(buf, string(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_name_83b24444a367a371(src []byte) (provider.Name, []byte, error) {
	v, src, err := _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return provider.Name(v), nil, err
	}
	return provider.Name(v), src, nil
}
func _intercallenc_type_names_3a79a20d5bb07688(buf []byte, v provider.Names) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_string_00f359e600d57533(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_type_names_2f8d71a1a91ab970(src []byte) (provider.Names, []byte, error) {
	var v provider.Names
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]string, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_string_e113d3e53c0a20ab(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_type_pixel_0b7c359743d44ca0(buf []byte, v provider.Pixel) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Red)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Green)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Blue)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_pixel_e142b5b3b88abfb8(src []byte) (provider.Pixel, []byte, error) {
	var v provider.Pixel
	var err error
	v.Red, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Green, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Blue, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_type_point_41c85497633e6c1a(buf []byte, v provider.Point) ([]byte, error) {
	var err error
	buf, err = _intercallenc_float64_6a8f51ea7f75bd30(buf, v.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_float64_6a8f51ea7f75bd30(buf, v.Y)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_point_13bb84b3d4b45cd2(src []byte) (provider.Point, []byte, error) {
	var v provider.Point
	var err error
	v.X, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v, nil, err
	}
	v.Y, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_type_user_id_6d1e6a3f9ce24d1b(buf []byte, v provider.UserID) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_user_id_3126e3c36ce2c1e3(src []byte) (provider.UserID, []byte, error) {
	v, src, err := _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return provider.UserID(v), nil, err
	}
	return provider.UserID(v), src, nil
}
func _intercallenc_type_customer_id_26df84587197fe58(buf []byte, v provider.CustomerID) ([]byte, error) {
	var err error
	buf, err = _intercallenc_type_user_id_6d1e6a3f9ce24d1b(buf, provider.UserID(v))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_type_customer_id_cf0fae21aea14a40(src []byte) (provider.CustomerID, []byte, error) {
	v, src, err := _intercalldec_type_user_id_3126e3c36ce2c1e3(src)
	if err != nil {
		return provider.CustomerID(v), nil, err
	}
	return provider.CustomerID(v), src, nil
}
func _intercallenc_list_empty___provider_Empty_a48dcf0f5e4446d3(buf []byte, v []provider.Empty) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_list_empty___provider_Empty_cf559a6833fe610b(src []byte) ([]provider.Empty, []byte, error) {
	var v []provider.Empty
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(_intercallmaxint_a986121adce7d8c5) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]provider.Empty, int(count0))
	return v, src, nil
}
func _intercallenc_list_name___provider_Name_17357768a2f64a7b(buf []byte, v []provider.Name) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_type_name_bd7f3efdad3b4199(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_name___provider_Name_a1234d2a0beddbd3(src []byte) ([]provider.Name, []byte, error) {
	var v []provider.Name
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]provider.Name, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_type_name_83b24444a367a371(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_list_record_origin_record_x_int16_y_int16__value_int64____struct____Origin_struct____X_int16__Y_int16____Value_int64___5e2c30efdb8e24f2(buf []byte, v []struct {
	Origin struct {
		X int16
		Y int16
	}
	Value int64
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_int16_e7f51d89efcdde56(buf, v[i0].Origin.X)
		if err != nil {
			return nil, err
		}
		buf, err = _intercallenc_int16_e7f51d89efcdde56(buf, v[i0].Origin.Y)
		if err != nil {
			return nil, err
		}
		buf, err = _intercallenc_int64_e7f52489efcdea71(buf, v[i0].Value)
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_record_origin_record_x_int16_y_int16__value_int64____struct____Origin_struct____X_int16__Y_int16____Value_int64___eb12766d6451a6ea(src []byte) ([]struct {
	Origin struct {
		X int16
		Y int16
	}
	Value int64
}, []byte, error) {
	var v []struct {
		Origin struct {
			X int16
			Y int16
		}
		Value int64
	}
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]struct {
		Origin struct {
			X int16
			Y int16
		}
		Value int64
	}, int(count0))
	for i1 := range v {
		v[i1].Origin.X, src, err = _intercalldec_int16_b1e233ba3828f2be(src)
		if err != nil {
			return v, nil, err
		}
		v[i1].Origin.Y, src, err = _intercalldec_int16_b1e233ba3828f2be(src)
		if err != nil {
			return v, nil, err
		}
		v[i1].Value, src, err = _intercalldec_int64_b1e23aba3828fe59(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_record_corner_record_inner_record_x_int32_y_int32__label_string__tag_uint16__struct____Corner_struct____Inner_struct____X_int32__Y_int32____Label_string____Tag_uint16___9bb83b93ad77276d(buf []byte, v struct {
	Corner struct {
		Inner struct {
			X int32
			Y int32
		}
		Label string
	}
	Tag uint16
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Corner.Inner.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Corner.Inner.Y)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_string_00f359e600d57533(buf, v.Corner.Label)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint16_849a1e5c3f37fcd5(buf, v.Tag)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_corner_record_inner_record_x_int32_y_int32__label_string__tag_uint16__struct____Corner_struct____Inner_struct____X_int32__Y_int32____Label_string____Tag_uint16___ca1ff8c94c9d7275(src []byte) (struct {
	Corner struct {
		Inner struct {
			X int32
			Y int32
		}
		Label string
	}
	Tag uint16
}, []byte, error) {
	var v struct {
		Corner struct {
			Inner struct {
				X int32
				Y int32
			}
			Label string
		}
		Tag uint16
	}
	var err error
	v.Corner.Inner.X, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Corner.Inner.Y, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Corner.Label, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v, nil, err
	}
	v.Tag, src, err = _intercalldec_uint16_2c3598e3014ca48d(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_corner_point_area_uint64__struct____Corner_provider_Point__Area_uint64___bfda711f4fe264da(buf []byte, v struct {
	Corner provider.Point
	Area   uint64
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_type_point_41c85497633e6c1a(buf, v.Corner)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, v.Area)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_corner_point_area_uint64__struct____Corner_provider_Point__Area_uint64___be1a7ae41a620942(src []byte) (struct {
	Corner provider.Point
	Area   uint64
}, []byte, error) {
	var v struct {
		Corner provider.Point
		Area   uint64
	}
	var err error
	v.Corner, src, err = _intercalldec_type_point_13bb84b3d4b45cd2(src)
	if err != nil {
		return v, nil, err
	}
	v.Area, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_x_int32_y_int32__struct____X_int32__Y_int32___412839956ef1eb69(buf []byte, v struct {
	X int32
	Y int32
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.X)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Y)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_x_int32_y_int32__struct____X_int32__Y_int32___64520c53ce0ee831(src []byte) (struct {
	X int32
	Y int32
}, []byte, error) {
	var v struct {
		X int32
		Y int32
	}
	var err error
	v.X, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Y, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_red_uint8_green_uint8_blue_uint8_alpha_uint8__struct____Red_uint8__Green_uint8__Blue_uint8__Alpha_uint8___56de80a37fd44abb(buf []byte, v struct {
	Red   uint8
	Green uint8
	Blue  uint8
	Alpha uint8
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Red)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Green)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Blue)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint8_77a42def2538a018(buf, v.Alpha)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_red_uint8_green_uint8_blue_uint8_alpha_uint8__struct____Red_uint8__Green_uint8__Blue_uint8__Alpha_uint8___e5aae671ac078523(src []byte) (struct {
	Red   uint8
	Green uint8
	Blue  uint8
	Alpha uint8
}, []byte, error) {
	var v struct {
		Red   uint8
		Green uint8
		Blue  uint8
		Alpha uint8
	}
	var err error
	v.Red, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Green, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Blue, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	v.Alpha, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___5f07b5088bd2f3e3(buf []byte, v struct {
	Width  uint32
	Height uint32
}) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint32_849a205c3f38007b(buf, v.Width)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_uint32_849a205c3f38007b(buf, v.Height)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___3337324db410126b(src []byte) (struct {
	Width  uint32
	Height uint32
}, []byte, error) {
	var v struct {
		Width  uint32
		Height uint32
	}
	var err error
	v.Width, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v, nil, err
	}
	v.Height, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_list_pixel___provider_Pixel_17ad78c08cba3275(buf []byte, v []provider.Pixel) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_type_pixel_0b7c359743d44ca0(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_pixel___provider_Pixel_e61e1cf1ac00bf6d(src []byte) ([]provider.Pixel, []byte, error) {
	var v []provider.Pixel
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]provider.Pixel, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_type_pixel_e142b5b3b88abfb8(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_list_uint8___uint8_f5408e3ade976024(buf []byte, v []uint8) ([]byte, error) {
	var err error
	buf, err = _intercallenc_uint64_849a235c3f380556(buf, uint64(len(v)))
	if err != nil {
		return nil, err
	}
	for i0 := range v {
		buf, err = _intercallenc_uint8_77a42def2538a018(buf, v[i0])
		if err != nil {
			return nil, err
		}
	}
	return buf, nil
}

func _intercalldec_list_uint8___uint8_ed36b3402c96257c(src []byte) ([]uint8, []byte, error) {
	var v []uint8
	var err error
	var count0 uint64
	count0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v, nil, err
	}
	if count0 > uint64(len(src)) {
		return v, nil, _intercallerror_long_e8fb175d020577b4
	}
	v = make([]uint8, int(count0))
	for i1 := range v {
		v[i1], src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
		if err != nil {
			return v, nil, err
		}
	}
	return v, src, nil
}
func _intercallenc_record___provider_Blank_3e81f17b4963a392(buf []byte, v provider.Blank) ([]byte, error) {
	return buf, nil
}

func _intercalldec_record___provider_Blank_9ee301b5e25f52ca(src []byte) (provider.Blank, []byte, error) {
	return provider.Blank{}, src, nil
}
func _intercallenc_record_code_int32_message_string__provider_Failed_e0d658056bc8d2a9(buf []byte, v provider.Failed) ([]byte, error) {
	var err error
	buf, err = _intercallenc_int32_e7f51f89efcde1f4(buf, v.Code)
	if err != nil {
		return nil, err
	}
	buf, err = _intercallenc_string_00f359e600d57533(buf, v.Message)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_code_int32_message_string__provider_Failed_237968242237b041(src []byte) (provider.Failed, []byte, error) {
	var v provider.Failed
	var err error
	v.Code, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v, nil, err
	}
	v.Message, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercallenc_record_point_point__provider_PointFailed_d9f364acee5481cd(buf []byte, v provider.PointFailed) ([]byte, error) {
	var err error
	buf, err = _intercallenc_type_point_41c85497633e6c1a(buf, v.Point)
	if err != nil {
		return nil, err
	}
	return buf, nil
}

func _intercalldec_record_point_point__provider_PointFailed_64d3f8d78b5e4d15(src []byte) (provider.PointFailed, []byte, error) {
	var v provider.PointFailed
	var err error
	v.Point, src, err = _intercalldec_type_point_13bb84b3d4b45cd2(src)
	if err != nil {
		return v, nil, err
	}
	return v, src, nil
}
func _intercalldereq_account_1483128f924072c2(src []byte) (provider.CustomerID, []byte, error) {
	var v0 provider.CustomerID
	var err error
	v0, src, err = _intercalldec_type_customer_id_cf0fae21aea14a40(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_add_785d921dde991182(src []byte) (int8, int16, int32, int64, uint8, uint16, uint32, uint64, []byte, error) {
	var v0 int8
	var v1 int16
	var v2 int32
	var v3 int64
	var v4 uint8
	var v5 uint16
	var v6 uint32
	var v7 uint64
	var err error
	v0, src, err = _intercalldec_int8_8e851e84d785af51(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	v1, src, err = _intercalldec_int16_b1e233ba3828f2be(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	v2, src, err = _intercalldec_int32_b1e235ba3828f5dc(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	v3, src, err = _intercalldec_int64_b1e23aba3828fe59(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	v4, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	v5, src, err = _intercalldec_uint16_2c3598e3014ca48d(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	v6, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	v7, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v0, v1, v2, v3, v4, v5, v6, v7, nil, err
	}
	return v0, v1, v2, v3, v4, v5, v6, v7, src, nil
}

func _intercalldereq_blanks_c14000ba7289c25c(src []byte) (uint64, []byte, error) {
	var v0 uint64
	var err error
	v0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_echo_447474c15333e61e(src []byte) (string, []byte, error) {
	var v0 string
	var err error
	v0, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_fetch_6e77f47583666d7f(src []byte) (provider.UserID, []byte, error) {
	var v0 provider.UserID
	var err error
	v0, src, err = _intercalldec_type_user_id_3126e3c36ce2c1e3(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_find_39fc4bc14cc26380(src []byte) (string, []provider.Name, []byte, error) {
	var v0 string
	var v1 []provider.Name
	var err error
	v0, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_list_name___provider_Name_a1234d2a0beddbd3(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_grid_328841c148e174cd(src []byte) ([]struct {
	Origin struct {
		X int16
		Y int16
	}
	Value int64
}, []byte, error) {
	var v0 []struct {
		Origin struct {
			X int16
			Y int16
		}
		Value int64
	}
	var err error
	v0, src, err = _intercalldec_list_record_origin_record_x_int16_y_int16__value_int64____struct____Origin_struct____X_int16__Y_int16____Value_int64___eb12766d6451a6ea(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_inner_406f4f9f0651d19f(src []byte) (uint64, []byte, error) {
	var v0 uint64
	var err error
	v0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_locate_95d3872621d3f95f(src []byte) (struct {
	Corner struct {
		Inner struct {
			X int32
			Y int32
		}
		Label string
	}
	Tag uint16
}, []byte, error) {
	var v0 struct {
		Corner struct {
			Inner struct {
				X int32
				Y int32
			}
			Label string
		}
		Tag uint16
	}
	var err error
	v0, src, err = _intercalldec_record_corner_record_inner_record_x_int32_y_int32__label_string__tag_uint16__struct____Corner_struct____Inner_struct____X_int32__Y_int32____Label_string____Tag_uint16___ca1ff8c94c9d7275(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_measure_f3006cb324c6a0c3(src []byte) (float32, float64, []byte, error) {
	var v0 float32
	var v1 float64
	var err error
	v0, src, err = _intercalldec_float32_a273938b3b463041(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_notify_30d61072949dba4a(src []byte) (string, []byte, error) {
	var v0 string
	var err error
	v0, src, err = _intercalldec_string_e113d3e53c0a20ab(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_outer_68a63ab035d54122(src []byte) (uint64, []byte, error) {
	var v0 uint64
	var err error
	v0, src, err = _intercalldec_uint64_2c359de3014cad0e(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_paint_793e81eb864e04e3(src []byte) (struct {
	X int32
	Y int32
}, struct {
	Red   uint8
	Green uint8
	Blue  uint8
	Alpha uint8
}, []byte, error) {
	var v0 struct {
		X int32
		Y int32
	}
	var v1 struct {
		Red   uint8
		Green uint8
		Blue  uint8
		Alpha uint8
	}
	var err error
	v0, src, err = _intercalldec_record_x_int32_y_int32__struct____X_int32__Y_int32___64520c53ce0ee831(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_record_red_uint8_green_uint8_blue_uint8_alpha_uint8__struct____Red_uint8__Green_uint8__Blue_uint8__Alpha_uint8___e5aae671ac078523(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_ping_b41a89c1922b222d(src []byte) ([]byte, error) {
	return src, nil
}

func _intercalldereq_render_a3c63deecf530e3d(src []byte) ([]provider.Pixel, uint16, []byte, error) {
	var v0 []provider.Pixel
	var v1 uint16
	var err error
	v0, src, err = _intercalldec_list_pixel___provider_Pixel_e61e1cf1ac00bf6d(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_uint16_2c3598e3014ca48d(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_sample_5f17e8dec708cf23(src []byte) ([]byte, uint8, []byte, error) {
	var v0 []byte
	var v1 uint8
	var err error
	v0, src, err = _intercalldec_bytes_dc8f190227fa8a41(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_uint8_ebdba4a25c65fcd0(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_scale_e8f47fd3d388e7d9(src []byte) (float64, provider.Point, []byte, error) {
	var v0 float64
	var v1 provider.Point
	var err error
	v0, src, err = _intercalldec_float64_a273968b3b4635b8(src)
	if err != nil {
		return v0, v1, nil, err
	}
	v1, src, err = _intercalldec_type_point_13bb84b3d4b45cd2(src)
	if err != nil {
		return v0, v1, nil, err
	}
	return v0, v1, src, nil
}

func _intercalldereq_stamp_670d1dd389f6cd9e(src []byte) ([]byte, error) {
	return src, nil
}

func _intercalldereq_tiny_d8aa4dc1a76baf97(src []byte) (provider.Empty, []byte, error) {
	var v0 provider.Empty
	var err error
	v0, src, err = _intercalldec_type_empty_ebbde05522390e0b(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_transform_7d61bc2871120697(src []byte) (provider.Matrix, []byte, error) {
	var v0 provider.Matrix
	var err error
	v0, src, err = _intercalldec_type_matrix_e9b99b4c3dfe24c3(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_wait_bc0cb9c19677975e(src []byte) (uint32, []byte, error) {
	var v0 uint32
	var err error
	v0, src, err = _intercalldec_uint32_2c359ae3014ca813(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercalldereq_wave_bc0cbcc196779c26(src []byte) ([]uint8, []byte, error) {
	var v0 []uint8
	var err error
	v0, src, err = _intercalldec_list_uint8___uint8_ed36b3402c96257c(src)
	if err != nil {
		return v0, nil, err
	}
	return v0, src, nil
}

func _intercallmatch_exc_6eefd8396f76a36d(err error) (uint64, []byte) {
	var match int
	var excKey uint64
	var excPayload []byte
	var encErr error
	if e, ok := err.(*provider.Blank); ok && e != nil {
		match++
		excKey = 0xc1ecfa6ae0f8e375
		excPayload, encErr = _intercallenc_record___provider_Blank_3e81f17b4963a392(nil, *e)
	}
	if err == error(provider.ErrDenied) {
		match++
		excKey = 0x7fbdf637a78620b0
	}
	if e, ok := err.(*provider.Failed); ok && e != nil {
		match++
		excKey = 0x583fb304d69368ca
		excPayload, encErr = _intercallenc_record_code_int32_message_string__provider_Failed_e0d658056bc8d2a9(nil, *e)
	}
	if e, ok := err.(*provider.PointFailed); ok && e != nil {
		match++
		excKey = 0xdc62e1adbe06b30b
		excPayload, encErr = _intercallenc_record_point_point__provider_PointFailed_d9f364acee5481cd(nil, *e)
	}
	if match != 1 || encErr != nil {
		return 0x1aaec22e85996f50, nil
	}
	return excKey, excPayload
}

func _intercalldispatch_6ba7a6d72caedc56(_intercallctx_01508600011dfaaf context.Context, _intercallkey_016b85000134c0a5 uint64, _intercallpayload_31bab4d98281f99a []byte) (uint64, []byte) {
	switch _intercallkey_016b85000134c0a5 {
	case 0x790f3b3d0f2c48ce:
		v0, rest, err := _intercalldereq_account_1483128f924072c2(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Account(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_type_user_id_6d1e6a3f9ce24d1b(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x8425decb5e996afe:
		v0, v1, v2, v3, v4, v5, v6, v7, rest, err := _intercalldereq_add_785d921dde991182(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Add(_intercallctx_01508600011dfaaf, v0, v1, v2, v3, v4, v5, v6, v7)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_int64_e7f52489efcdea71(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xf7f7406372c28a90:
		v0, rest, err := _intercalldereq_blanks_c14000ba7289c25c(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Blanks(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_list_empty___provider_Empty_a48dcf0f5e4446d3(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x159eb91a98f8f42:
		v0, rest, err := _intercalldereq_echo_447474c15333e61e(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Echo(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_string_00f359e600d57533(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xb50b5c7d5249d7a3:
		v0, rest, err := _intercalldereq_fetch_6e77f47583666d7f(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Fetch(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_type_blob_e1acc4fdc2289b89(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xfa48ba91a602db6c:
		v0, v1, rest, err := _intercalldereq_find_39fc4bc14cc26380(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Find(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_type_names_3a79a20d5bb07688(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xef6e78919f3e63c1:
		v0, rest, err := _intercalldereq_grid_328841c148e174cd(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Grid(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_uint64_849a235c3f380556(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x11fb9f647235d4f3:
		v0, rest, err := _intercalldereq_inner_406f4f9f0651d19f(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Inner(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_uint64_849a235c3f380556(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x1ac8478033777d33:
		v0, rest, err := _intercalldereq_locate_95d3872621d3f95f(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Locate(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_record_corner_point_area_uint64__struct____Corner_provider_Point__Area_uint64___bfda711f4fe264da(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x95b3ff87ea2bd3f:
		v0, v1, rest, err := _intercalldereq_measure_f3006cb324c6a0c3(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Measure(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_float64_6a8f51ea7f75bd30(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x176dc8d164d61d5e:
		v0, rest, err := _intercalldereq_notify_30d61072949dba4a(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		err = provider.Notify(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		return 0, nil
	case 0x456baa2f902f936e:
		v0, rest, err := _intercalldereq_outer_68a63ab035d54122(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Outer(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_uint64_849a235c3f380556(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x52095929e015a29f:
		v0, v1, rest, err := _intercalldereq_paint_793e81eb864e04e3(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Paint(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_record_width_uint32_height_uint32__struct____Width_uint32__Height_uint32___5f07b5088bd2f3e3(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xa3aa209174f340d1:
		rest, err := _intercalldereq_ping_b41a89c1922b222d(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		err = provider.Ping(_intercallctx_01508600011dfaaf)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		return 0, nil
	case 0x7bbe409a86d47581:
		v0, v1, rest, err := _intercalldereq_render_a3c63deecf530e3d(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Render(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_list_pixel___provider_Pixel_17ad78c08cba3275(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x2549b9c663851f:
		v0, v1, rest, err := _intercalldereq_sample_5f17e8dec708cf23(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Sample(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_bytes_6b87e24ef38333c9(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x9575f710f1aef4e5:
		v0, v1, rest, err := _intercalldereq_scale_e8f47fd3d388e7d9(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Scale(_intercallctx_01508600011dfaaf, v0, v1)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_type_point_41c85497633e6c1a(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0xe1bf6d111c6bae5a:
		rest, err := _intercalldereq_stamp_670d1dd389f6cd9e(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Stamp(_intercallctx_01508600011dfaaf)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_type_empty_d7948148fc4b8663(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x7f875c91600f848b:
		v0, rest, err := _intercalldereq_tiny_d8aa4dc1a76baf97(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Tiny(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_uint32_849a205c3f38007b(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x3253bdb7662c67bb:
		v0, rest, err := _intercalldereq_transform_7d61bc2871120697(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Transform(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_type_matrix_963182a3387ab87b(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x6650009151fef422:
		v0, rest, err := _intercalldereq_wait_bc0cb9c19677975e(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Wait(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_uint32_849a205c3f38007b(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	case 0x664ffb9151feebb2:
		v0, rest, err := _intercalldereq_wave_bc0cbcc196779c26(_intercallpayload_31bab4d98281f99a)
		if err != nil || len(rest) != 0 {
			return 0x3f5fc972f8477b07, nil
		}
		out, err := provider.Wave(_intercallctx_01508600011dfaaf, v0)
		if err != nil {
			return _intercallmatch_exc_6eefd8396f76a36d(err)
		}
		enc, err := _intercallenc_uint32_849a205c3f38007b(nil, out)
		if err != nil {
			return 0x1aaec22e85996f50, nil
		}
		return 0, enc
	default:
		return 0x970e76fcc5e2dacb, nil
	}
}

var _intercallbinding_47f982b7aff8567b = func() intercall.ExportBinding {
	b, err := intercall.NewExportBinding(_intercalldispatch_6ba7a6d72caedc56)
	if err != nil {
		panic(err)
	}
	return b
}()

// ExportBinding returns the package's immutable export binding.
func ExportBinding() intercall.ExportBinding {
	return _intercallbinding_47f982b7aff8567b
}
