package integration

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/cerasos/intercall/internal/syntax"
	"github.com/cerasos/intercall/internal/tool"
)

// This file pins the checked-in generated fixtures to the generator:
// both bindings and the owned interface are regenerated through the
// complete intercall-go pipeline into temporary directories and
// compared byte for byte against the checked-in files, and repeated
// generation is proven deterministic. Validation never edits the
// checked fixtures.

// Fixture paths, relative to the package directory that go test runs
// in (internal/integration).
const (
	fixtureProviderPattern = "./internal/integration/fixtures/provider"
	fixtureExportOutDir    = "./internal/integration/fixtures/e2eexport"
	fixtureExportOutPath   = "github.com/cerasos/intercall/internal/integration/fixtures/e2eexport"
	fixtureExportPackage   = "e2eexport"
	fixtureImportPackage   = "e2eimport"
	fixtureInterfacePath   = "fixtures/interface/e2e.intercall"
	fixtureExportGenPath   = "fixtures/e2eexport/binding_gen.go"
	fixtureImportGenPath   = "fixtures/e2eimport/binding_gen.go"
)

// moduleRoot returns the absolute module root, the discovery base of
// the export pipeline.
func moduleRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("resolving the module root: %v", err)
	}
	return root
}

// discoverEnv makes one discovery pass hermetic, exactly like the CLI
// and the tool tests: the explicit toolchain on PATH, ambient GOFLAGS
// and GOENV cleared, and GOWORK off.
func discoverEnv() []string {
	env := append([]string{}, os.Environ()...)
	env = append(env,
		"GOFLAGS=",
		"GOENV=off",
		"GOWORK=off",
		"PATH=/usr/local/go/bin"+string(os.PathListSeparator)+os.Getenv("PATH"),
	)
	return env
}

// generateExportFixture runs the complete export pipeline over the
// fixture provider: discovery in the active module, the export model
// with its importability checks, and the emitter. The result is the
// byte-exact content behind the ownership lines of the checked export
// binding and the byte-exact canonical interface body of the owned
// interface.
func generateExportFixture(t *testing.T) (goFile, body []byte) {
	t.Helper()
	res, err := tool.Discover(tool.DiscoverConfig{
		Dir:      moduleRoot(t),
		Env:      discoverEnv(),
		Patterns: []string{fixtureProviderPattern},
		OutDir:   fixtureExportOutDir,
	})
	if err != nil {
		t.Fatalf("discover: %v", err)
	}
	model, err := tool.MapExport(res, fixtureExportOutPath)
	if err != nil {
		t.Fatalf("MapExport: %v", err)
	}
	goFile, body, err = tool.GenerateExport(model, fixtureExportPackage)
	if err != nil {
		t.Fatalf("GenerateExport: %v", err)
	}
	return goFile, body
}

// composeOwnedInterface assembles one complete owned interface file
// exactly as the artifact layer does: the ownership marker with the
// artifact stamp of the canonical body, one blank line, and the body.
func composeOwnedInterface(body []byte) []byte {
	var b bytes.Buffer
	b.WriteString("/* Code generated by intercall-go; artifact sha256:")
	b.WriteString(tool.ArtifactStamp(body))
	b.WriteString("; DO NOT EDIT. */\n\n")
	b.Write(body)
	return b.Bytes()
}

// TestCheckedInGeneratedFixturesAreCurrent regenerates the export
// binding and owned interface from the provider package and the import
// binding from the exact checked interface bytes, staging every
// artifact into temporary directories, and verifies the checked-in
// files are byte-identical to the staged artifacts. The canonical body
// must also survive the parse-document-validate-format round trip.
func TestCheckedInGeneratedFixturesAreCurrent(t *testing.T) {
	goFile, body := generateExportFixture(t)

	dir := t.TempDir()
	if err := tool.WriteArtifacts(tool.WriteConfig{
		Mode:          tool.ExportMode,
		OutDir:        dir,
		Package:       fixtureExportPackage,
		InterfacePath: filepath.Join(dir, "e2e.intercall"),
		GoFile:        goFile,
		InterfaceBody: body,
	}); err != nil {
		t.Fatalf("staging the export artifacts: %v", err)
	}
	written, err := os.ReadFile(filepath.Join(dir, "binding_gen.go"))
	if err != nil {
		t.Fatalf("reading the staged export binding: %v", err)
	}
	checked, err := os.ReadFile(fixtureExportGenPath)
	if err != nil {
		t.Fatalf("reading %s: %v", fixtureExportGenPath, err)
	}
	if !bytes.Equal(written, checked) {
		t.Fatalf("%s is stale: the staged artifact (%d bytes) differs from the checked-in file (%d bytes); regenerate it with intercall-go", fixtureExportGenPath, len(written), len(checked))
	}
	writtenIntf, err := os.ReadFile(filepath.Join(dir, "e2e.intercall"))
	if err != nil {
		t.Fatalf("reading the staged interface: %v", err)
	}
	checkedIntf, err := os.ReadFile(fixtureInterfacePath)
	if err != nil {
		t.Fatalf("reading %s: %v", fixtureInterfacePath, err)
	}
	if !bytes.Equal(writtenIntf, checkedIntf) {
		t.Fatalf("%s is stale: the staged interface (%d bytes) differs from the checked-in file (%d bytes); regenerate it with intercall-go", fixtureInterfacePath, len(writtenIntf), len(checkedIntf))
	}
	if want := composeOwnedInterface(body); !bytes.Equal(checkedIntf, want) {
		t.Fatal("the checked-in interface does not match the ownership marker, blank line, and canonical body form")
	}

	// The canonical body is canonical: it parses, attaches its
	// documentation, validates, and reformats to the identical bytes.
	f, err := syntax.Parse("e2e.intercall", body)
	if err != nil {
		t.Fatalf("parsing the canonical interface body: %v", err)
	}
	syntax.AttachDocs(f)
	if err := syntax.Validate(f); err != nil {
		t.Fatalf("validating the canonical interface body: %v", err)
	}
	if formatted := syntax.Format(f); !bytes.Equal(formatted, body) {
		t.Fatal("the canonical interface body does not survive the parse-validate-format round trip")
	}

	// The import side regenerates from the exact bytes of the checked
	// interface file, discarding the unattached ownership marker.
	goFile2, body2, err := tool.GenerateImport("e2e.intercall", checkedIntf, nil, fixtureImportPackage)
	if err != nil {
		t.Fatalf("GenerateImport: %v", err)
	}
	if !bytes.Equal(body2, body) {
		t.Fatal("the import pipeline recovered a different canonical body from the owned interface")
	}
	dir2 := t.TempDir()
	if err := tool.WriteArtifacts(tool.WriteConfig{
		Mode:          tool.ImportMode,
		OutDir:        dir2,
		Package:       fixtureImportPackage,
		GoFile:        goFile2,
		InterfaceBody: body2,
	}); err != nil {
		t.Fatalf("staging the import artifacts: %v", err)
	}
	written2, err := os.ReadFile(filepath.Join(dir2, "binding_gen.go"))
	if err != nil {
		t.Fatalf("reading the staged import binding: %v", err)
	}
	checked2, err := os.ReadFile(fixtureImportGenPath)
	if err != nil {
		t.Fatalf("reading %s: %v", fixtureImportGenPath, err)
	}
	if !bytes.Equal(written2, checked2) {
		t.Fatalf("%s is stale: the staged artifact (%d bytes) differs from the checked-in file (%d bytes); regenerate it with intercall-go", fixtureImportGenPath, len(written2), len(checked2))
	}
}

// TestGeneratedOutputDeterminism verifies that both emitters are
// deterministic over the fixture: two complete export pipeline runs and
// two import runs over the same input produce byte-identical output,
// and a different interface input produces different import bytes.
func TestGeneratedOutputDeterminism(t *testing.T) {
	first, firstBody := generateExportFixture(t)
	second, secondBody := generateExportFixture(t)
	if !bytes.Equal(first, second) || !bytes.Equal(firstBody, secondBody) {
		t.Fatal("running the export pipeline twice produced different bytes")
	}

	checked, err := os.ReadFile(fixtureInterfacePath)
	if err != nil {
		t.Fatalf("reading %s: %v", fixtureInterfacePath, err)
	}
	importOnce := func(src []byte) []byte {
		t.Helper()
		goFile, _, err := tool.GenerateImport("e2e.intercall", src, nil, fixtureImportPackage)
		if err != nil {
			t.Fatalf("GenerateImport: %v", err)
		}
		return goFile
	}
	a := importOnce(checked)
	b := importOnce(checked)
	if !bytes.Equal(a, b) {
		t.Fatal("importing the interface twice produced different bytes")
	}

	// A different interface input produces different bytes, proving the
	// comparison exercises the input rather than a cached result.
	changed := bytes.Join([][]byte{checked, []byte("procedure extra {};\n")}, nil)
	c := importOnce(changed)
	if bytes.Equal(a, c) {
		t.Fatal("a different interface produced identical import bytes")
	}
}
