package tool

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/cerasos/intercall/internal/syntax"
)

// This file implements SPEC.md "One-file ownership and safe
// replacement": the exact ownership lines and lowercase 64-hex-digit
// SHA-256 artifact stamps, package-name resolution, non-following
// target-leaf checks, output-directory Go collision checks under host
// filename equivalence, in-memory content validation, same-filesystem
// temp staging and rename replacement, the interrupted two-target
// export repair, and deterministic bytes.
//
// Every binding is one file named binding_gen.go whose first two lines
// are the exact generated-file marker and the binding line
// "// intercall-go binding: <mode> sha256:<artifact-id>", where <mode>
// is "import" or "export". The exported interface starts with the
// marker "/* Code generated by intercall-go; artifact
// sha256:<artifact-id>; DO NOT EDIT. */", one blank line, and the
// canonical interface body. The artifact-id is the SHA-256 digest of
// the canonical interface body, never of the ownership lines. The
// write phase never deletes a path and never truncates a target: it
// stages temporary files in the destination directories and replaces
// owned targets by rename.

// bindingFile is the one generated binding filename of every binding.
// File partitioning is not a configuration or generator decision.
const bindingFile = "binding_gen.go"

// artifactStampLen is the exact length of a lowercase 64-hex-digit
// SHA-256 digest.
const artifactStampLen = 64

// bindingOwnershipPrefix is the exact prefix of a binding file's second
// line, before the binding kind.
const bindingOwnershipPrefix = "// intercall-go binding: "

// interfaceMarkerPrefix and interfaceMarkerSuffix are the exact parts
// of the exported interface's single-line ownership marker around the
// artifact stamp.
const (
	interfaceMarkerPrefix = "/* Code generated by intercall-go; artifact sha256:"
	interfaceMarkerSuffix = "; DO NOT EDIT. */"
)

// ArtifactMode is the binding kind recorded in a generated artifact's
// ownership lines (SPEC.md "One-file ownership and safe replacement":
// "The second line says export for an export binding"). It is the
// "mode" that must match the invocation before an existing
// binding_gen.go is replaceable.
type ArtifactMode int

const (
	// ImportMode writes an import binding; its ownership line says
	// "import".
	ImportMode ArtifactMode = iota
	// ExportMode writes an export binding and its owned interface
	// file; its ownership line says "export".
	ExportMode
)

// String renders the mode exactly as it appears in the ownership line.
func (m ArtifactMode) String() string {
	switch m {
	case ImportMode:
		return "import"
	case ExportMode:
		return "export"
	}
	return fmt.Sprintf("ArtifactMode(%d)", int(m))
}

// validMode reports whether m is one of the two defined modes.
func validMode(m ArtifactMode) bool { return m == ImportMode || m == ExportMode }

// ArtifactStamp returns the exact artifact stamp of one canonical
// interface body: the lowercase 64-hex-digit SHA-256 digest of the body
// bytes. The stamp hashes the body, never the ownership lines, and is a
// local update stamp only; the runtime does not store, compare, or
// exchange it.
func ArtifactStamp(body []byte) string {
	sum := sha256.Sum256(body)
	return hex.EncodeToString(sum[:])
}

// validStamp reports whether stamp has the exact valid syntax of an
// artifact stamp: 64 lowercase hexadecimal digits.
func validStamp(stamp string) bool {
	if len(stamp) != artifactStampLen {
		return false
	}
	for i := 0; i < len(stamp); i++ {
		c := stamp[i]
		if !('0' <= c && c <= '9' || 'a' <= c && c <= 'f') {
			return false
		}
	}
	return true
}

// bindingOwnership is the parsed ownership of an existing binding file.
type bindingOwnership struct {
	mode  ArtifactMode
	stamp string
}

// parseBindingOwnership parses the exact two ownership lines of one
// binding file: the standard generated-file marker followed by the
// binding line "// intercall-go binding: <mode> sha256:<stamp>". ok is
// false unless the first two lines and the artifact stamp have the
// exact valid form. A trailing '\r' is stripped from each line, so a
// CRLF-owned file is recognized.
func parseBindingOwnership(src []byte) (bo bindingOwnership, ok bool) {
	line1, rest, has1 := cutLine(src)
	if !has1 || strings.TrimSuffix(line1, "\r") != intercallGeneratedMarker {
		return bindingOwnership{}, false
	}
	line2, _, has2 := cutLine(rest)
	if !has2 {
		return bindingOwnership{}, false
	}
	line2 = strings.TrimSuffix(line2, "\r")
	for _, mode := range []ArtifactMode{ImportMode, ExportMode} {
		prefix := bindingOwnershipPrefix + mode.String() + " sha256:"
		if !strings.HasPrefix(line2, prefix) {
			continue
		}
		stamp := line2[len(prefix):]
		if !validStamp(stamp) {
			return bindingOwnership{}, false
		}
		return bindingOwnership{mode: mode, stamp: stamp}, true
	}
	return bindingOwnership{}, false
}

// interfaceOwnership is the parsed ownership of an existing exported
// interface file.
type interfaceOwnership struct {
	stamp string
	body  []byte
}

// parseInterfaceOwnership parses the exact ownership form of one
// exported interface file: the marker line
// "/* Code generated by intercall-go; artifact sha256:<stamp>; DO NOT
// EDIT. */", one blank line, and the canonical interface body. ok is
// false unless the marker line and the blank line are exact and the
// stamp is the SHA-256 digest of the body bytes, so an interface target
// is replaceable only when its stamp matches its canonical body.
func parseInterfaceOwnership(src []byte) (io interfaceOwnership, ok bool) {
	line1, rest, has1 := cutLine(src)
	if !has1 {
		return interfaceOwnership{}, false
	}
	line1 = strings.TrimSuffix(line1, "\r")
	if !strings.HasPrefix(line1, interfaceMarkerPrefix) || !strings.HasSuffix(line1, interfaceMarkerSuffix) {
		return interfaceOwnership{}, false
	}
	stamp := line1[len(interfaceMarkerPrefix) : len(line1)-len(interfaceMarkerSuffix)]
	if !validStamp(stamp) {
		return interfaceOwnership{}, false
	}
	// The ownership form is the marker line followed by one blank line
	// and the canonical body; the blank line leaves the marker
	// semantically unattached when the file is imported.
	if len(rest) == 0 || rest[0] != '\n' {
		return interfaceOwnership{}, false
	}
	body := rest[1:]
	if ArtifactStamp(body) != stamp {
		return interfaceOwnership{}, false
	}
	return interfaceOwnership{stamp: stamp, body: body}, true
}

// cutLine splits src at its first '\n'. ok is false when src has no
// line terminator.
func cutLine(src []byte) (line string, rest []byte, ok bool) {
	i := bytes.IndexByte(src, '\n')
	if i < 0 {
		return string(src), nil, false
	}
	return string(src[:i]), src[i+1:], true
}

// bindingPackage extracts the package clause of one binding file. An
// existing binding is replaceable only when it parses as Go.
func bindingPackage(src []byte, logical string) (string, error) {
	fset := token.NewFileSet()
	af, err := parser.ParseFile(fset, logical, src, parser.SkipObjectResolution)
	if err != nil {
		return "", &Error{
			Filename: logical,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("%s is not replaceable: its Go source does not parse", logical),
		}
	}
	if af.Name == nil {
		return "", &Error{
			Filename: logical,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("%s is not replaceable: it has no package clause", logical),
		}
	}
	return af.Name.Name, nil
}

// outputPackageBase returns the base name used for a new output's
// package: the base name of the resolved output directory when it
// resolves, and otherwise the base name of the cleaned operand. A
// degenerate base ("..", ".", or the separator) resolves through the
// working directory.
func outputPackageBase(outDir string) string {
	resolved := outDir
	if r, err := filepath.EvalSymlinks(outDir); err == nil {
		resolved = r
	}
	base := filepath.Base(resolved)
	if base == "." || base == ".." || base == string(filepath.Separator) {
		if abs, err := filepath.Abs(resolved); err == nil {
			base = filepath.Base(abs)
		}
	}
	return base
}

// ResolvePackageName resolves the generated package name of one
// artifact write (SPEC.md "Commands"): the explicit --package name when
// given, an existing owned binding's package clause when no explicit
// name is given, and otherwise the output directory's base name. The
// tool never sanitizes a package name.
//
// An explicit name must be valid and, when an owned binding already
// exists in the output directory, must equal that binding's package
// clause. An existing binding of the other mode is a collision. The
// output directory is not created and no file is written.
func ResolvePackageName(mode ArtifactMode, outDir, explicit string) (string, error) {
	if !validMode(mode) {
		return "", &Error{Pos: Position{Line: 1, Column: 1}, Msg: "invalid artifact mode"}
	}
	if outDir == "" {
		return "", &Error{Pos: Position{Line: 1, Column: 1}, Msg: "no output directory"}
	}
	if explicit != "" {
		if err := ValidGoPackageName(explicit); err != nil {
			return "", err
		}
	}

	resolvedOut := outDir
	if r, err := filepath.EvalSymlinks(outDir); err == nil {
		resolvedOut = r
	}
	binding := filepath.Join(resolvedOut, bindingFile)
	logical := filepath.Join(outDir, bindingFile)
	info, err := os.Lstat(binding)
	switch {
	case err == nil:
		if !info.Mode().IsRegular() {
			return "", &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("%s exists and is not a regular file; a symlink, directory, device, or other nonregular target leaf is an error", logical),
			}
		}
		src, err := os.ReadFile(binding)
		if err != nil {
			return "", operandError(logical, "reading", err)
		}
		bo, ok := parseBindingOwnership(src)
		if !ok {
			return "", &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("%s is not replaceable: its first two lines and artifact stamp do not have the exact ownership form of a generated binding", logical),
			}
		}
		if bo.mode != mode {
			return "", &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("%s is a %s binding, but this invocation writes a %s binding", logical, bo.mode, mode),
			}
		}
		pkg, err := bindingPackage(src, logical)
		if err != nil {
			return "", err
		}
		if explicit != "" && pkg != explicit {
			return "", &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("the existing %s declares package %q, but the explicit package name is %q; an explicit name must equal an existing owned binding's package name", bindingFile, pkg, explicit),
			}
		}
		if err := ValidGoPackageName(pkg); err != nil {
			return "", &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("the existing %s declares package %q: %v", bindingFile, pkg, err),
			}
		}
		if explicit != "" {
			return explicit, nil
		}
		return pkg, nil
	case errors.Is(err, fs.ErrNotExist):
		if explicit != "" {
			return explicit, nil
		}
		name := outputPackageBase(outDir)
		if err := ValidGoPackageName(name); err != nil {
			return "", &Error{
				Filename: outDir,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("the output directory's base name %q is not a valid package name: %v", name, err),
			}
		}
		return name, nil
	default:
		return "", operandError(logical, "inspecting", err)
	}
}

// WriteConfig describes one artifact write: the complete generated
// bytes of one binding and the canonical interface body the binding
// represents.
//
// Mode is the binding kind recorded in the ownership lines. OutDir is
// the --out directory, which the write creates if necessary, and
// Package the resolved package name from ResolvePackageName.
// InterfacePath is the export interface target; it is unused for
// import. GoFile is the complete generated binding file after the two
// ownership lines: its package clause and body, which the write
// formats and parses. InterfaceBody is the byte-exact canonical
// interface body; its SHA-256 digest is the artifact stamp recorded in
// both targets, and for export the write composes and reparses the
// owned interface file from it.
type WriteConfig struct {
	Mode          ArtifactMode
	OutDir        string
	Package       string
	InterfacePath string // export only
	GoFile        []byte
	InterfaceBody []byte
}

// WriteArtifacts writes one validated, stamped artifact pair safely
// and deterministically, in the exact order of SPEC.md "One-file
// ownership and safe replacement": in-memory content validation first
// (any validation error emits no generated file and creates no
// directory), then output-directory creation, the interface target's
// parent existence, host resolution of both target parents,
// non-following leaf checks, the output-directory scan, ownership
// checks, and finally same-filesystem staging and rename replacement.
// The write never deletes a path and never truncates a target; an
// unchanged target is not replaced.
func WriteArtifacts(cfg WriteConfig) error {
	w := &artifactWriter{cfg: cfg, rename: os.Rename}
	return w.run()
}

// artifactWriter is one artifact write in progress.
type artifactWriter struct {
	cfg    WriteConfig
	rename func(oldpath, newpath string) error

	outResolved  string              // resolved output directory
	intfResolved string              // resolved interface target (export)
	foldOut      func(string) string // host case folding of the output directory; nil = exact
	foldIntf     func(string) string // host case folding of the interface parent; nil = exact

	stamp         string // artifact stamp of the new interface body
	formatted     []byte // formatted complete binding bytes
	interfaceFile []byte // complete owned interface bytes (export)
}

// bindingTarget returns the physical binding path in the resolved
// output directory.
func (w *artifactWriter) bindingTarget() string {
	return filepath.Join(w.outResolved, bindingFile)
}

// run performs the complete ordered write.
func (w *artifactWriter) run() error {
	if err := w.validateConfig(); err != nil {
		return err
	}
	if err := w.validateContent(); err != nil {
		return err
	}

	// Output-directory creation, then the interface target's parent
	// must exist; both parents are then resolved through the host
	// filesystem and the write operates on the resolved directories.
	if err := os.MkdirAll(w.cfg.OutDir, 0o777); err != nil {
		return operandError(w.cfg.OutDir, "creating output directory", err)
	}
	if w.cfg.Mode == ExportMode {
		if err := w.checkInterfaceParent(); err != nil {
			return err
		}
	}
	if err := w.resolveParents(); err != nil {
		return err
	}
	w.foldOut = hostFold(w.outResolved)
	if w.cfg.Mode == ExportMode {
		w.foldIntf = hostFold(filepath.Dir(w.intfResolved))
	}

	// Ownership checks finish before any target-file creation or
	// replacement.
	if err := w.checkLeaves(); err != nil {
		return err
	}
	if w.cfg.Mode == ExportMode {
		if err := w.checkInterfaceName(); err != nil {
			return err
		}
	}
	if err := w.scanOutDir(); err != nil {
		return err
	}
	existing, err := w.readExisting()
	if err != nil {
		return err
	}
	return w.commit(existing)
}

// validateConfig checks the write configuration. The checks run before
// anything is created.
func (w *artifactWriter) validateConfig() error {
	bad := func(format string, args ...any) error {
		return &Error{Pos: Position{Line: 1, Column: 1}, Msg: fmt.Sprintf(format, args...)}
	}
	if !validMode(w.cfg.Mode) {
		return bad("invalid artifact mode")
	}
	if w.cfg.OutDir == "" {
		return bad("no output directory")
	}
	if w.cfg.Package == "" {
		return bad("no package name; resolve it with ResolvePackageName first")
	}
	if err := ValidGoPackageName(w.cfg.Package); err != nil {
		return err
	}
	if w.cfg.Mode == ExportMode && w.cfg.InterfacePath == "" {
		return bad("export requires an interface target")
	}
	if len(w.cfg.GoFile) == 0 {
		return bad("no generated binding bytes")
	}
	return nil
}

// validateContent composes the complete binding and interface bytes and
// validates them in memory: the binding is formatted with go/format and
// parsed, its package clause must match the resolved package name, and
// for export the owned interface file is composed and reparsed. Every
// check finishes before the output directory is created (SPEC.md
// "Diagnostics": source validation and generated-content validation
// finish before output-directory creation).
func (w *artifactWriter) validateContent() error {
	w.stamp = ArtifactStamp(w.cfg.InterfaceBody)

	var b bytes.Buffer
	b.WriteString(intercallGeneratedMarker)
	b.WriteByte('\n')
	b.WriteString(bindingOwnershipPrefix)
	b.WriteString(w.cfg.Mode.String())
	b.WriteString(" sha256:")
	b.WriteString(w.stamp)
	b.WriteByte('\n')
	b.WriteByte('\n')
	b.Write(w.cfg.GoFile)
	composed := b.Bytes()

	formatted, err := format.Source(composed)
	if err != nil {
		return &Error{
			Pos: Position{Line: 1, Column: 1},
			Msg: fmt.Sprintf("the generated binding is not valid Go: %v", err),
		}
	}
	fset := token.NewFileSet()
	logical := filepath.Join(w.cfg.OutDir, bindingFile)
	af, err := parser.ParseFile(fset, logical, formatted, parser.SkipObjectResolution)
	if err != nil {
		return &Error{
			Filename: logical,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("the generated binding does not parse: %v", err),
		}
	}
	if af.Name == nil || af.Name.Name != w.cfg.Package {
		got := "<none>"
		if af.Name != nil {
			got = af.Name.Name
		}
		return &Error{
			Filename: logical,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("the generated binding declares package %q, but the resolved package name is %q", got, w.cfg.Package),
		}
	}
	w.formatted = formatted

	if w.cfg.Mode == ExportMode {
		var ib bytes.Buffer
		ib.WriteString(interfaceMarkerPrefix)
		ib.WriteString(w.stamp)
		ib.WriteString(interfaceMarkerSuffix)
		ib.WriteByte('\n')
		ib.WriteByte('\n')
		ib.Write(w.cfg.InterfaceBody)
		w.interfaceFile = ib.Bytes()
		if _, err := syntax.Parse(w.cfg.InterfacePath, w.interfaceFile); err != nil {
			return err
		}
	}
	return nil
}

// checkInterfaceParent requires the interface target's parent to exist
// after the output directory was created (SPEC.md "One-file ownership
// and safe replacement": "It creates --out if necessary; after that,
// the interface target's parent must exist").
func (w *artifactWriter) checkInterfaceParent() error {
	parent := filepath.Dir(w.cfg.InterfacePath)
	info, err := os.Stat(parent)
	if err != nil {
		return &Error{
			Filename: w.cfg.InterfacePath,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("the interface target's parent directory %q does not exist; only the output directory is created", parent),
		}
	}
	if !info.IsDir() {
		return &Error{
			Filename: w.cfg.InterfacePath,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("the interface target's parent %q is not a directory", parent),
		}
	}
	return nil
}

// resolveParents resolves both target parents through the host
// filesystem; every later operation uses the resolved directories.
func (w *artifactWriter) resolveParents() error {
	resolved, err := filepath.EvalSymlinks(w.cfg.OutDir)
	if err != nil {
		return operandError(w.cfg.OutDir, "resolving output directory", err)
	}
	w.outResolved = resolved
	if w.cfg.Mode == ExportMode {
		parent := filepath.Dir(w.cfg.InterfacePath)
		rp, err := filepath.EvalSymlinks(parent)
		if err != nil {
			return operandError(parent, "resolving interface target directory", err)
		}
		w.intfResolved = filepath.Join(rp, filepath.Base(w.cfg.InterfacePath))
	}
	return nil
}

// checkLeaves inspects both target leaves with non-following file
// status: a symlink, directory, device, or other nonregular leaf is an
// error (SPEC.md "One-file ownership and safe replacement").
func (w *artifactWriter) checkLeaves() error {
	if err := w.checkLeaf(w.bindingTarget(), filepath.Join(w.cfg.OutDir, bindingFile)); err != nil {
		return err
	}
	if w.cfg.Mode == ExportMode {
		if err := w.checkLeaf(w.intfResolved, w.cfg.InterfacePath); err != nil {
			return err
		}
	}
	return nil
}

// checkLeaf inspects one target leaf with non-following file status.
func (w *artifactWriter) checkLeaf(path, logical string) error {
	info, err := os.Lstat(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		return operandError(logical, "inspecting", err)
	}
	if info.Mode().IsRegular() {
		return nil
	}
	return &Error{
		Filename: logical,
		Pos:      Position{Line: 1, Column: 1},
		Msg:      fmt.Sprintf("%s exists and is a %s; a symlink, directory, device, or other nonregular target leaf is an error", logical, leafKind(info.Mode())),
	}
}

// leafKind names one nonregular file mode for diagnostics.
func leafKind(m os.FileMode) string {
	switch {
	case m&os.ModeSymlink != 0:
		return "symbolic link"
	case m.IsDir():
		return "directory"
	case m&os.ModeDevice != 0:
		return "device"
	case m&os.ModeNamedPipe != 0:
		return "named pipe"
	case m&os.ModeSocket != 0:
		return "socket"
	}
	return "nonregular file"
}

// checkInterfaceName enforces the interface target's filename rules:
// it must not have a ".go" filename, and it must not be the generated
// Go target under the host filesystem's filename equivalence (SPEC.md
// "One-file ownership and safe replacement").
func (w *artifactWriter) checkInterfaceName() error {
	leaf := filepath.Base(w.cfg.InterfacePath)
	if isGoFileName(w.foldIntf, leaf) {
		return &Error{
			Filename: w.cfg.InterfacePath,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("the interface target %q must not have a .go filename", leaf),
		}
	}
	if isBindingTargetName(w.foldIntf, leaf) {
		return &Error{
			Filename: w.cfg.InterfacePath,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("the interface target %q is the generated Go target under this filesystem's filename equivalence", leaf),
		}
	}
	return nil
}

// scanOutDir rejects every Go entry of the output directory except the
// generated binding: the directory may contain no Go file or Go-named
// nonregular entry other than binding_gen.go (SPEC.md "One-file
// ownership and safe replacement"). Non-Go entries are always
// preserved.
func (w *artifactWriter) scanOutDir() error {
	entries, err := os.ReadDir(w.outResolved)
	if err != nil {
		return operandError(w.cfg.OutDir, "reading output directory", err)
	}
	for _, e := range entries {
		name := e.Name()
		if isBindingTargetName(w.foldOut, name) {
			continue // the owned generated target; the leaf check handles it
		}
		if !isGoFileName(w.foldOut, name) {
			continue // a non-Go entry: always preserved
		}
		info, err := e.Info()
		if err != nil {
			return operandError(filepath.Join(w.cfg.OutDir, name), "inspecting", err)
		}
		kind := "Go file"
		if !info.Mode().IsRegular() {
			kind = "Go-named nonregular entry"
		}
		logical := filepath.Join(w.cfg.OutDir, name)
		return &Error{
			Filename: logical,
			Pos:      Position{Line: 1, Column: 1},
			Msg:      fmt.Sprintf("%s is a %s; the output directory may contain no Go file or Go-named nonregular entry except %s", logical, kind, bindingFile),
		}
	}
	return nil
}

// existingTargets records the ownership facts of the existing binding
// and interface targets.
type existingTargets struct {
	binding       *existingBinding
	interfaceFile *existingInterface
}

// existingBinding is one replaceable existing binding: its recorded
// stamp and its exact bytes.
type existingBinding struct {
	stamp string
	bytes []byte
}

// existingInterface is one replaceable existing interface target: its
// recorded stamp and its exact bytes.
type existingInterface struct {
	stamp string
	bytes []byte
}

// readExisting performs every ownership check of the existing targets:
// an existing binding_gen.go is replaceable only when its two ownership
// lines and artifact stamp have valid syntax and its mode and package
// match this invocation, and an existing interface target only when it
// is a regular nonsymlink file with a valid ownership line and its
// stamp matches its canonical body. Every other collision is an error.
func (w *artifactWriter) readExisting() (*existingTargets, error) {
	ex := &existingTargets{}
	logical := filepath.Join(w.cfg.OutDir, bindingFile)
	if info, err := os.Lstat(w.bindingTarget()); err == nil {
		if !info.Mode().IsRegular() {
			return nil, fmt.Errorf("internal error: nonregular binding leaf reached the ownership check")
		}
		src, err := os.ReadFile(w.bindingTarget())
		if err != nil {
			return nil, operandError(logical, "reading", err)
		}
		bo, ok := parseBindingOwnership(src)
		if !ok {
			return nil, &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("%s is not replaceable: its first two lines and artifact stamp do not have the exact ownership form of a generated binding", logical),
			}
		}
		if bo.mode != w.cfg.Mode {
			return nil, &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("%s is a %s binding, but this invocation writes a %s binding", logical, bo.mode, w.cfg.Mode),
			}
		}
		pkg, err := bindingPackage(src, logical)
		if err != nil {
			return nil, err
		}
		if pkg != w.cfg.Package {
			return nil, &Error{
				Filename: logical,
				Pos:      Position{Line: 1, Column: 1},
				Msg:      fmt.Sprintf("%s declares package %q, but this invocation's package is %q; its mode and package must match the invocation", logical, pkg, w.cfg.Package),
			}
		}
		ex.binding = &existingBinding{stamp: bo.stamp, bytes: src}
	} else if !errors.Is(err, fs.ErrNotExist) {
		return nil, operandError(logical, "inspecting", err)
	}

	if w.cfg.Mode == ExportMode {
		if info, err := os.Lstat(w.intfResolved); err == nil {
			if !info.Mode().IsRegular() {
				return nil, fmt.Errorf("internal error: nonregular interface leaf reached the ownership check")
			}
			src, err := os.ReadFile(w.intfResolved)
			if err != nil {
				return nil, operandError(w.cfg.InterfacePath, "reading", err)
			}
			io, ok := parseInterfaceOwnership(src)
			if !ok {
				return nil, &Error{
					Filename: w.cfg.InterfacePath,
					Pos:      Position{Line: 1, Column: 1},
					Msg:      fmt.Sprintf("%s is not replaceable: it does not carry the exact ownership marker of an exported interface, or its stamp does not match its canonical body", w.cfg.InterfacePath),
				}
			}
			ex.interfaceFile = &existingInterface{stamp: io.stamp, bytes: src}
		} else if !errors.Is(err, fs.ErrNotExist) {
			return nil, operandError(w.cfg.InterfacePath, "inspecting", err)
		}
	}
	return ex, nil
}

// commit stages temporary files in the destination directories and
// replaces exactly the targets that need replacement. Export compares
// the valid existing binding and interface stamps: different stamps,
// or exactly one missing owned target, mean a prior update was
// interrupted and the next successful invocation deterministically
// repairs both targets; in the normal state an unchanged target is not
// replaced. The binding is replaced before the interface. Targets are
// replaced by rename, never by truncation or deletion.
func (w *artifactWriter) commit(ex *existingTargets) error {
	replaceBinding, replaceInterface := true, false
	if w.cfg.Mode == ExportMode {
		if ex.binding != nil && ex.interfaceFile != nil && ex.binding.stamp == ex.interfaceFile.stamp {
			// The normal state: both targets are owned and their
			// stamps agree. Replace only targets whose bytes changed.
			replaceBinding = !bytes.Equal(ex.binding.bytes, w.formatted)
			replaceInterface = !bytes.Equal(ex.interfaceFile.bytes, w.interfaceFile)
		} else {
			// A fresh write, a differing stamp pair, or exactly one
			// missing owned target: repair both.
			replaceBinding, replaceInterface = true, true
		}
	} else if ex.binding != nil && bytes.Equal(ex.binding.bytes, w.formatted) {
		replaceBinding = false
	}

	var bindingTmp, intfTmp string
	cleanup := func() {
		if bindingTmp != "" {
			os.Remove(bindingTmp)
		}
		if intfTmp != "" {
			os.Remove(intfTmp)
		}
	}
	if replaceBinding {
		tmp, err := stageFile(w.outResolved, filepath.Join(w.cfg.OutDir, bindingFile), bindingFile, w.formatted)
		if err != nil {
			return err
		}
		bindingTmp = tmp
	}
	if replaceInterface {
		tmp, err := stageFile(filepath.Dir(w.intfResolved), w.cfg.InterfacePath, filepath.Base(w.intfResolved), w.interfaceFile)
		if err != nil {
			cleanup()
			return err
		}
		intfTmp = tmp
	}

	if replaceBinding {
		if err := w.rename(bindingTmp, w.bindingTarget()); err != nil {
			cleanup()
			return renameError(filepath.Join(w.cfg.OutDir, bindingFile), err)
		}
		bindingTmp = ""
	}
	if replaceInterface {
		if err := w.rename(intfTmp, w.intfResolved); err != nil {
			cleanup()
			return renameError(w.cfg.InterfacePath, err)
		}
		intfTmp = ""
	}
	return nil
}

// stageFile writes content to a temporary file in dir, the same
// filesystem as the target, and returns its path. The caller renames
// the staged file over the target. A failure reports at line 1,
// column 1 of the logical target with only the underlying cause: no
// staging path, resolved physical directory, or absolute internal
// path ever appears in a diagnostic (SPEC.md "Diagnostics": "It
// never reports a staging path").
func stageFile(dir, logical, targetName string, content []byte) (string, error) {
	f, err := os.CreateTemp(dir, "."+targetName+".tmp-*")
	if err != nil {
		return "", operandError(logical, "staging", err)
	}
	tmp := f.Name()
	fail := func(err error) (string, error) {
		f.Close()
		os.Remove(tmp)
		return "", err
	}
	if _, err := f.Write(content); err != nil {
		return fail(operandError(logical, "staging", err))
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return "", operandError(logical, "staging", err)
	}
	if err := os.Chmod(tmp, 0o644); err != nil {
		os.Remove(tmp)
		return "", operandError(logical, "staging", err)
	}
	return tmp, nil
}

// renameError reports a failed target replacement: the host could not
// replace the existing file by rename, and the command fails without
// first deleting it. The diagnostic names the logical target and the
// underlying cause only, never the staging path.
func renameError(target string, err error) error {
	return &Error{
		Filename: target,
		Pos:      Position{Line: 1, Column: 1},
		Msg:      fmt.Sprintf("replacing %s: %s; the existing file was not deleted", target, pathErrorCause(err)),
	}
}

// pathErrorCause returns the underlying cause of one filesystem error
// without the operand paths that triggered it: a *fs.PathError or
// *os.LinkError contributes only its Err text, so a diagnostic never
// embeds a staging path, a resolved physical directory, or another
// internal path.
func pathErrorCause(err error) string {
	if pe, ok := err.(*fs.PathError); ok && pe.Err != nil {
		return pe.Err.Error()
	}
	if le, ok := err.(*os.LinkError); ok && le.Err != nil {
		return le.Err.Error()
	}
	return err.Error()
}

// operandError converts one operational filesystem failure into a
// diagnostic without a source span: it reports at line 1, column 1 of
// the relevant logical operand (SPEC.md "Diagnostics") and carries
// only the underlying cause of the wrapped error, never the staging
// path or the resolved physical directory the operation used.
func operandError(filename, op string, err error) error {
	return &Error{
		Filename: filename,
		Pos:      Position{Line: 1, Column: 1},
		Msg:      fmt.Sprintf("%s %s: %s", op, filename, pathErrorCause(err)),
	}
}

// hostFold returns the case-folding function of the filesystem of dir,
// or nil when names differing only in case are distinct files. The
// result models the host filesystem's filename equivalence used by the
// interface-target and output-directory checks (SPEC.md "One-file
// ownership and safe replacement"): a probe file with a mixed-case
// name is created and its case-folded variant is looked up with
// non-following status. Windows filesystems fold case, so the probe is
// skipped there.
func hostFold(dir string) func(string) string {
	if runtime.GOOS == "windows" {
		return strings.ToLower
	}
	probe, err := os.CreateTemp(dir, "InterCallCaseProbe")
	if err != nil {
		return nil // an unwritable directory fails staging later
	}
	name := filepath.Base(probe.Name())
	probe.Close()
	os.Remove(probe.Name())
	if _, err := os.Lstat(filepath.Join(dir, strings.ToLower(name))); err == nil {
		return strings.ToLower
	}
	return nil
}

// isBindingTargetName reports whether name is the generated Go target
// name binding_gen.go under host filename equivalence.
func isBindingTargetName(fold func(string) string, name string) bool {
	if name == bindingFile {
		return true
	}
	return fold != nil && fold(name) == bindingFile
}

// isGoFileName reports whether name is a Go filename under host
// filename equivalence: the exact ".go" suffix, or the same suffix
// after case folding on a host that does not distinguish case.
func isGoFileName(fold func(string) string, name string) bool {
	if strings.HasSuffix(name, ".go") {
		return true
	}
	return fold != nil && strings.HasSuffix(fold(name), ".go")
}
