package tool

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// This file tests package discovery, procedure selection, and procedure
// signatures (SPEC.md "Package discovery and selection" and "Procedure
// signatures and wire values"). Fixtures are temporary modules and
// workspaces created at test runtime under t.TempDir; tests never write
// into the repository and clean up after themselves.

// procFixture is the main single-module fixture. It exercises overlap
// deduplication, explicit versus dependency packages, main and
// test-only packages, generated files, build-tag variants, test files,
// internal visibility, provider/output import cycles, selector
// resolution, and every signature form.
var procFixture = map[string]string{
	"go.mod": "module example.com/proc\n\ngo 1.26.5\n",
	"proc.go": `// Package proc is the discovery fixture root.
package proc

import (
	"context"

	"example.com/proc/dep"
)

// DepUse keeps the dependency import alive.
var DepUse = dep.DepProc

// User is the data result of FindUser.
type User struct {
	ID string
}

// FindUser finds a user by name.
// @intercall procedure find_user
// @intercall param userID user_id
// @param userID the user to find
// @return the matching user
func FindUser(ctx context.Context, userID string) (User, error) {
	return User{}, nil
}

// Ping checks liveness.
// @intercall procedure ping
func Ping(ctx context.Context) error { return nil }

// @intercall procedure lookup_user
func LookupUser(ctx context.Context, id string) error { return nil }

// Untagged is exported but has no procedure directive.
func Untagged(ctx context.Context) error { return nil }

// unexported has no directive and is not exported.
func unexported(ctx context.Context) error { return nil }

// Helper carries a method that must never be selectable.
type Helper struct{}

// Do is a method, not an eligible function.
func (h Helper) Do(ctx context.Context) error { return nil }
`,
	"dep/dep.go": `// Package dep is a dependency of the fixture root.
package dep

import "context"

// @intercall procedure dep_proc
func DepProc(ctx context.Context) error { return nil }
`,
	"out/out.go": `// Package out is the output-package target.
package out

// Helper is an ordinary function.
func Helper() {}
`,
	"cyc/cyc.go": `// Package cyc imports the output package.
package cyc

import (
	"context"

	"example.com/proc/out"
)

// UseOut keeps the import alive.
var UseOut = out.Helper

// @intercall procedure cyc_proc
func CycProc(ctx context.Context) error { return nil }
`,
	"sub/sub.go": `// Package sub is the internal-visibility root.
package sub

// Sub is an ordinary function.
func Sub() {}
`,
	"sub/internal/hidden/hidden.go": `// Package hidden is internal to example.com/proc/sub.
package hidden

import "context"

// @intercall procedure hidden_proc
func HiddenProc(ctx context.Context) error { return nil }
`,
	"gen/gen.go": `// Code generated by fixture; DO NOT EDIT.

// Package gen has a generated file.
package gen

import "context"

// @intercall procedure gen_proc
func GenProc(ctx context.Context) error { return nil }
`,
	"gen/hand.go": `// Package gen is shared with the generated fixture file.
package gen

import "context"

// @intercall procedure hand_proc
func HandProc(ctx context.Context) error { return nil }
`,
	"withtests/withtests.go": `// Package withtests has a regular and a test file.
package withtests

import "context"

// @intercall procedure real_proc
func Real(ctx context.Context) error { return nil }
`,
	"withtests/withtests_test.go": `// Package withtests holds a tagged test-only function.
package withtests

import "context"

// @intercall procedure test_only
func TestOnly(ctx context.Context) error { return nil }
`,
	"variant/variant.go": `// Package variant has a tagged variant-excluded file.
package variant

import "context"

// @intercall procedure variant_proc
func Variant(ctx context.Context) error { return nil }
`,
	"variant/never.go": `//go:build never

// Package variant holds the never-built file.
package variant

import "context"

// @intercall procedure never_proc
func NeverProc(ctx context.Context) error { return nil }
`,
	"testonly/testonly_test.go": `// Package testonly has only a test file.
package testonly

import "context"

// @intercall procedure test_only_proc
func TestOnlyProc(ctx context.Context) error { return nil }
`,
	"cmd/cmd.go": `// Package main is not importable.
package main

import "context"

// @intercall procedure main_proc
func MainProc(ctx context.Context) error { return nil }
`,
	"unexp/unexp.go": `// Package unexp tags an unexported function.
package unexp

import "context"

// @intercall procedure hidden
func hidden(ctx context.Context) error { return nil }
`,
	"badtype/badtype.go": `// Package badtype does not type-check.
package badtype

var X = undefinedName
`,
	"badsig/badsig.go": `// Package badsig holds every signature form.
package badsig

import "context"

// ACtx is an alias of context.Context.
type ACtx = context.Context

// Ctx is a defined lookalike of context.Context.
type Ctx context.Context

// AE is an alias of the predeclared error.
type AE = error

// E is a defined lookalike of the predeclared error.
type E error

// @intercall procedure alias_ctx
func AliasCtx(ctx ACtx, x int) error { return nil }

// @intercall procedure alias_err
func AliasErr(ctx context.Context, x int) AE { return nil }

// @intercall procedure named_results
func NamedRes(ctx context.Context, x int) (user int, err error) { return 0, nil }

// @intercall procedure anon_err
func AnonErr(ctx context.Context, x int) interface{ Error() string } { return nil }

// @intercall procedure bad_return
func BadRet(ctx context.Context, x int) (int, string) { return 0, "" }

// @intercall procedure blank_param
func Blank(ctx context.Context, _ int) error { return nil }

// @intercall procedure defined_ctx
func DefCtx(ctx Ctx, x int) error { return nil }

// @intercall procedure defined_err
func DefErr(ctx context.Context, x int) E { return nil }

// @intercall procedure generic_proc
func Gen[T any](ctx context.Context, x T) error { return nil }

// @intercall procedure no_context
func NoCtx(x int) error { return nil }

// @intercall procedure no_error
func NoErr(ctx context.Context) int { return 0 }

// @intercall procedure no_results
func NoResults(ctx context.Context, x int) {}

// @intercall procedure triple_result
func Triple(ctx context.Context, a int, b string) (int, string, error) { return 0, "", nil }

// @intercall procedure unnamed_param
func Unnamed(context.Context, int) error { return nil }

// @intercall procedure variadic_proc
func Var(ctx context.Context, xs ...int) error { return nil }
`,
}

// wsFixture is the workspace fixture: two modules under one go.work.
var wsFixture = map[string]string{
	"go.work":  "go 1.26.5\n\nuse (\n\t./a\n\t./b\n)\n",
	"a/go.mod": "module example.com/wa\n\ngo 1.26.5\n",
	"a/a.go": `// Package a is the first workspace module.
package a

import "context"

// @intercall procedure a_proc
func AProc(ctx context.Context) error { return nil }
`,
	"a/internal/ai/ai.go": `// Package ai is internal to module wa.
package ai

import "context"

// @intercall procedure ai_proc
func AIProc(ctx context.Context) error { return nil }
`,
	"b/go.mod": "module example.com/wb\n\ngo 1.26.5\n",
	"b/b.go": `// Package b is the second workspace module.
package b

import "context"

// @intercall procedure b_proc
func BProc(ctx context.Context) error { return nil }
`,
	"b/out/out.go": `// Package out is the workspace output package.
package out

// Helper is an ordinary function.
func Helper() {}
`,
}

// writeFixture writes one map of relative paths to a fresh temporary
// directory and returns it.
func writeFixture(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("creating fixture directory: %v", err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("writing fixture file: %v", err)
		}
	}
	return dir
}

// discoverEnv builds the discovery environment: the current environment
// with the explicit toolchain on PATH, ambient GOFLAGS and GOENV cleared,
// and GOWORK set to gowork ("off" for module fixtures, the absolute
// go.work path for workspace fixtures).
func discoverEnv(gowork string) []string {
	env := append([]string{}, os.Environ()...)
	env = append(env,
		"GOFLAGS=",
		"GOENV=off",
		"GOWORK="+gowork,
		"PATH=/usr/local/go/bin"+string(os.PathListSeparator)+os.Getenv("PATH"),
	)
	return env
}

// discover runs one discovery pass with the module-mode environment.
func discover(t *testing.T, dir string, patterns []string, includes, excludes []string, outDir string) (*DiscoverResult, error) {
	t.Helper()
	return Discover(DiscoverConfig{
		Dir:      dir,
		Env:      discoverEnv("off"),
		Patterns: patterns,
		Includes: includes,
		Excludes: excludes,
		OutDir:   outDir,
	})
}

// wantProviders asserts the exact provider list of a discovery result.
func wantProviders(t *testing.T, res *DiscoverResult, want ...string) {
	t.Helper()
	var got []string
	for _, p := range res.Providers {
		got = append(got, p.Pkg.Path+"."+p.Name)
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("providers = %v, want %v", got, want)
	}
}

// wantErr fails the test unless err is non-nil and its message contains
// all substrings.
func wantErr(t *testing.T, err error, contains ...string) {
	t.Helper()
	if err == nil {
		t.Fatal("discovery succeeded, want an error")
	}
	for _, s := range contains {
		if !strings.Contains(err.Error(), s) {
			t.Errorf("error = %q, want it to contain %q", err.Error(), s)
		}
	}
}

// TestPackageDiscovery covers operand handling, package identity,
// deduplication, exclusion of tests, variants, generated files, and
// main packages, package diagnostics, and output-package importability.
func TestPackageDiscovery(t *testing.T) {
	dir := writeFixture(t, procFixture)

	t.Run("OverlapDedup", func(t *testing.T) {
		// The same package reached by a relative pattern, a canonical
		// import path, and a wildcard deduplicates to one explicit
		// package.
		res, err := discover(t, dir, []string{".", "example.com/proc", "./dep", "example.com/proc/dep"}, nil, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		var paths []string
		for _, p := range res.Packages {
			paths = append(paths, p.Path)
		}
		want := []string{"example.com/proc", "example.com/proc/dep"}
		if !reflect.DeepEqual(paths, want) {
			t.Errorf("explicit packages = %v, want %v", paths, want)
		}
		wantProviders(t, res, "example.com/proc.FindUser", "example.com/proc.LookupUser", "example.com/proc.Ping", "example.com/proc/dep.DepProc")
	})

	t.Run("UnmatchedPattern", func(t *testing.T) {
		_, err := discover(t, dir, []string{".", "./nomatch"}, nil, nil, "out")
		wantErr(t, err, "./nomatch", "directory not found")
	})

	t.Run("ExplicitVsDependency", func(t *testing.T) {
		// dep is loaded for type checking only; its tagged function is
		// not eligible.
		res, err := discover(t, dir, []string{"."}, nil, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		var paths []string
		for _, p := range res.Packages {
			paths = append(paths, p.Path)
		}
		if !reflect.DeepEqual(paths, []string{"example.com/proc"}) {
			t.Errorf("explicit packages = %v", paths)
		}
		wantProviders(t, res, "example.com/proc.FindUser", "example.com/proc.LookupUser", "example.com/proc.Ping")
	})

	t.Run("MainRejected", func(t *testing.T) {
		_, err := discover(t, dir, []string{"./cmd"}, nil, nil, "out")
		wantErr(t, err, "example.com/proc/cmd", "main", "not importable")
	})

	t.Run("TestFilesExcluded", func(t *testing.T) {
		res, err := discover(t, dir, []string{"./withtests"}, nil, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res, "example.com/proc/withtests.Real")
	})

	t.Run("VariantExcluded", func(t *testing.T) {
		res, err := discover(t, dir, []string{"./variant"}, nil, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res, "example.com/proc/variant.Variant")
	})

	t.Run("GeneratedExcluded", func(t *testing.T) {
		res, err := discover(t, dir, []string{"./gen"}, nil, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res, "example.com/proc/gen.HandProc")
	})

	t.Run("FileOperandRejected", func(t *testing.T) {
		_, err := discover(t, dir, []string{"example.com/proc/proc.go"}, nil, nil, "out")
		wantErr(t, err, "file operands are not supported")
		_, err = discover(t, dir, []string{"file=" + filepath.Join(dir, "proc.go")}, nil, nil, "out")
		wantErr(t, err, "file operands are not supported")
	})

	t.Run("NoImplicitScan", func(t *testing.T) {
		_, err := discover(t, dir, nil, nil, nil, "out")
		wantErr(t, err, "at least one package pattern")
	})

	t.Run("TaggedUnexportedRejected", func(t *testing.T) {
		_, err := discover(t, dir, []string{"./unexp"}, nil, nil, "out")
		wantErr(t, err, "applies only to an exported function")
	})

	t.Run("TypeErrorRejected", func(t *testing.T) {
		_, err := discover(t, dir, []string{"./badtype"}, nil, nil, "out")
		wantErr(t, err, "undefinedName")
	})

	t.Run("TestOnlyPackageRejected", func(t *testing.T) {
		// A wildcard match of a directory whose only Go file is a test
		// file yields a package with no compiled files, which is not
		// importable.
		only := writeFixture(t, map[string]string{
			"go.mod":      "module example.com/only\n\ngo 1.26.5\n",
			"x/x_test.go": "package x\n\nimport \"testing\"\n\nfunc TestX(t *testing.T) {}\n",
		})
		_, err := discover(t, only, []string{"./..."}, nil, nil, "out")
		wantErr(t, err, "example.com/only/x", "no Go files", "not importable")
	})

	t.Run("EmptyModuleWildcardRejected", func(t *testing.T) {
		// A wildcard that matches nothing in an empty module returns no
		// packages at all; the pattern must still match a package.
		empty := writeFixture(t, map[string]string{
			"go.mod": "module example.com/empty\n\ngo 1.26.5\n",
		})
		_, err := discover(t, empty, []string{"./..."}, nil, nil, "out")
		wantErr(t, err, "no package matched")
	})

	t.Run("ImportCycle", func(t *testing.T) {
		cyc := writeFixture(t, map[string]string{
			"go.mod": "module example.com/cycle\n\ngo 1.26.5\n",
			"a/a.go": `package a

import "example.com/cycle/b"

var Use = b.B

var A = 1
`,
			"b/b.go": `package b

import "example.com/cycle/a"

var Use = a.A

var B = 1
`,
		})
		_, err := discover(t, cyc, []string{"./..."}, nil, nil, "out")
		wantErr(t, err, "import cycle")
	})

	t.Run("InternalVisibility", func(t *testing.T) {
		// The output package inside the internal root is allowed...
		res, err := discover(t, dir, []string{"./sub/internal/hidden"}, nil, nil, "sub")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res, "example.com/proc/sub/internal/hidden.HiddenProc")
		// ...but an output package outside the root is not.
		_, err = discover(t, dir, []string{"./sub/internal/hidden"}, nil, nil, "out")
		wantErr(t, err, "internal", "not visible", "example.com/proc/out")
	})

	t.Run("ProviderOutputCycle", func(t *testing.T) {
		_, err := discover(t, dir, []string{"./cyc"}, nil, nil, "out")
		wantErr(t, err, "import cycle", "example.com/proc/out")
	})

	t.Run("SelfImport", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, nil, nil, ".")
		wantErr(t, err, "own package")
	})

	t.Run("OutDirUnresolved", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, nil, nil, "missing")
		wantErr(t, err, "output directory", "missing")
	})

	t.Run("OutDirTestOnly", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, nil, nil, "testonly")
		wantErr(t, err, "no Go files", "not importable")
	})

	t.Run("OutDirMain", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, nil, nil, "cmd")
		wantErr(t, err, "main package", "not importable")
	})
}

// TestPackageDiscoveryWorkspace covers active workspaces: packages from
// several modules are eligible, the output package may live in another
// workspace module, and internal visibility and out-of-workspace
// resolution are enforced.
func TestPackageDiscoveryWorkspace(t *testing.T) {
	dir := writeFixture(t, wsFixture)
	env := discoverEnv(filepath.Join(dir, "go.work"))

	t.Run("CrossModuleEligible", func(t *testing.T) {
		res, err := Discover(DiscoverConfig{
			Dir:      dir,
			Env:      env,
			Patterns: []string{"./a/...", "./b/..."},
			Excludes: []string{"example.com/wa/internal/ai.AIProc"},
			OutDir:   "b/out",
		})
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res,
			"example.com/wa.AProc",
			"example.com/wb.BProc",
		)
	})

	t.Run("CrossModuleInternalHidden", func(t *testing.T) {
		// The output package lives in module wb; module wa's internal
		// package is not visible from it.
		_, err := Discover(DiscoverConfig{
			Dir:      dir,
			Env:      env,
			Patterns: []string{"./a/..."},
			OutDir:   "b/out",
		})
		wantErr(t, err, "internal", "not visible", "example.com/wb/out")
	})

	t.Run("OutDirOutsideWorkspace", func(t *testing.T) {
		outside := writeFixture(t, map[string]string{
			"go.mod": "module example.com/elsewhere\n\ngo 1.26.5\n",
			"o.go":   "package elsewhere\n",
		})
		_, err := Discover(DiscoverConfig{
			Dir:      dir,
			Env:      env,
			Patterns: []string{"./b/..."},
			OutDir:   outside,
		})
		wantErr(t, err, "output directory", "go.work")
	})
}

// TestProcedureSelection covers the include and exclude filters: exact
// grammar, resolution categories, duplicates, exclusion precedence, and
// deterministic order.
func TestProcedureSelection(t *testing.T) {
	dir := writeFixture(t, procFixture)

	t.Run("NoIncludeSelectsAll", func(t *testing.T) {
		res, err := discover(t, dir, []string{"."}, nil, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		// Deterministic order: package path, then symbol.
		wantProviders(t, res, "example.com/proc.FindUser", "example.com/proc.LookupUser", "example.com/proc.Ping")
	})

	t.Run("IncludeRestricts", func(t *testing.T) {
		res, err := discover(t, dir, []string{"."}, []string{"example.com/proc.Ping"}, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res, "example.com/proc.Ping")
	})

	t.Run("ExcludeRemoves", func(t *testing.T) {
		res, err := discover(t, dir, []string{"."}, nil, []string{"example.com/proc.Ping"}, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res, "example.com/proc.FindUser", "example.com/proc.LookupUser")
	})

	t.Run("ExclusionWins", func(t *testing.T) {
		res, err := discover(t, dir, []string{"."},
			[]string{"example.com/proc.Ping"}, []string{"example.com/proc.Ping"}, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res)
	})

	t.Run("Malformed", func(t *testing.T) {
		for _, filter := range []string{"", "Ping", ".Ping", "example.com/proc.", "a/b//c.Fn"} {
			_, err := discover(t, dir, []string{"."}, []string{filter}, nil, "out")
			wantErr(t, err, "malformed selector", filter)
		}
	})

	t.Run("UnknownPackage", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, []string{"example.com/nope.Ping"}, nil, "out")
		wantErr(t, err, "unknown selector", "example.com/nope")
	})

	t.Run("DependencyPackage", func(t *testing.T) {
		// dep is a dependency here, not an explicit package.
		_, err := discover(t, dir, []string{"."}, []string{"example.com/proc/dep.DepProc"}, nil, "out")
		wantErr(t, err, "unknown selector", "example.com/proc/dep")
	})

	t.Run("UnexportedSelector", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, []string{"example.com/proc.unexported"}, nil, "out")
		wantErr(t, err, "unexported selector")
	})

	t.Run("UntaggedSelector", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, []string{"example.com/proc.Untagged"}, nil, "out")
		wantErr(t, err, "untagged selector")
	})

	t.Run("GeneratedSelector", func(t *testing.T) {
		_, err := discover(t, dir, []string{"./gen"}, []string{"example.com/proc/gen.GenProc"}, nil, "out")
		wantErr(t, err, "untagged selector", "generated file")
	})

	t.Run("MethodSelector", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."}, []string{"example.com/proc.Do"}, nil, "out")
		wantErr(t, err, "method selector")
	})

	t.Run("GenericSelector", func(t *testing.T) {
		_, err := discover(t, dir, []string{"./badsig"}, []string{"example.com/proc/badsig.Gen"}, nil, "out")
		wantErr(t, err, "generic")
	})

	t.Run("Duplicate", func(t *testing.T) {
		_, err := discover(t, dir, []string{"."},
			[]string{"example.com/proc.Ping", "example.com/proc.Ping"}, nil, "out")
		wantErr(t, err, "duplicate selector", "example.com/proc.Ping")
		_, err = discover(t, dir, []string{"."},
			nil, []string{"example.com/proc.Ping", "example.com/proc.Ping"}, "out")
		wantErr(t, err, "duplicate selector", "example.com/proc.Ping")
	})

	t.Run("ExcludesSkipSignatureChecks", func(t *testing.T) {
		// Excluding every invalid signature leaves only the valid
		// functions of badsig selected.
		res, err := discover(t, dir, []string{"./badsig"}, nil, []string{
			"example.com/proc/badsig.AnonErr",
			"example.com/proc/badsig.BadRet",
			"example.com/proc/badsig.Blank",
			"example.com/proc/badsig.DefCtx",
			"example.com/proc/badsig.DefErr",
			"example.com/proc/badsig.Gen",
			"example.com/proc/badsig.NoCtx",
			"example.com/proc/badsig.NoErr",
			"example.com/proc/badsig.NoResults",
			"example.com/proc/badsig.Triple",
			"example.com/proc/badsig.Unnamed",
			"example.com/proc/badsig.Var",
		}, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		wantProviders(t, res,
			"example.com/proc/badsig.AliasCtx",
			"example.com/proc/badsig.AliasErr",
			"example.com/proc/badsig.NamedRes",
		)
	})
}

// TestProcedureSignatures covers the exact provider signature: the
// context.Context identity, the predeclared error identity, named wire
// parameters, result arity, and the rejection of methods, generics, and
// variadics.
func TestProcedureSignatures(t *testing.T) {
	dir := writeFixture(t, procFixture)

	// one runs discovery of badsig with exactly one include filter and
	// returns the error.
	one := func(t *testing.T, include string) (*DiscoverResult, error) {
		t.Helper()
		return discover(t, dir, []string{"./badsig"}, []string{"example.com/proc/badsig." + include}, nil, "out")
	}

	t.Run("ValidAliasContext", func(t *testing.T) {
		res, err := one(t, "AliasCtx")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		p := res.Providers[0]
		if !reflect.DeepEqual(p.Params, []string{"x"}) {
			t.Errorf("params = %v, want [x]", p.Params)
		}
		if p.DataResult {
			t.Error("DataResult = true, want false")
		}
	})

	t.Run("ValidAliasError", func(t *testing.T) {
		res, err := one(t, "AliasErr")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		if res.Providers[0].DataResult {
			t.Error("DataResult = true, want false")
		}
	})

	t.Run("ValidNamedResults", func(t *testing.T) {
		res, err := one(t, "NamedRes")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		if !res.Providers[0].DataResult {
			t.Error("DataResult = false, want true")
		}
	})

	t.Run("DefinedContextRejected", func(t *testing.T) {
		_, err := one(t, "DefCtx")
		wantErr(t, err, "exact type identity context.Context")
	})

	t.Run("DefinedErrorRejected", func(t *testing.T) {
		_, err := one(t, "DefErr")
		wantErr(t, err, "predeclared error")
	})

	t.Run("AnonymousErrorRejected", func(t *testing.T) {
		_, err := one(t, "AnonErr")
		wantErr(t, err, "predeclared error")
	})

	t.Run("MissingContext", func(t *testing.T) {
		_, err := one(t, "NoCtx")
		wantErr(t, err, "context.Context")
	})

	t.Run("UnnamedParam", func(t *testing.T) {
		_, err := one(t, "Unnamed")
		wantErr(t, err, "must have a name")
	})

	t.Run("BlankParam", func(t *testing.T) {
		_, err := one(t, "Blank")
		wantErr(t, err, "blank identifier")
	})

	t.Run("VariadicRejected", func(t *testing.T) {
		_, err := one(t, "Var")
		wantErr(t, err, "variadic")
	})

	t.Run("ResultArity", func(t *testing.T) {
		_, err := one(t, "NoErr")
		wantErr(t, err, "predeclared error")
		_, err = one(t, "NoResults")
		wantErr(t, err, "must return error")
		_, err = one(t, "Triple")
		wantErr(t, err, "at most one data result")
		_, err = one(t, "BadRet")
		wantErr(t, err, "predeclared error")
	})

	t.Run("GenericRejectedWithoutFilters", func(t *testing.T) {
		// A tagged generic function is eligible, so without filters it
		// is selected and rejected by the signature check.
		only := writeFixture(t, map[string]string{
			"go.mod": "module example.com/genselect\n\ngo 1.26.5\n",
			"gen.go": `package genselect

import "context"

// @intercall procedure gen_proc
func Gen[T any](ctx context.Context, x T) error { return nil }
`,
		})
		_, err := discover(t, only, []string{"."}, nil, nil, ".")
		wantErr(t, err, "generic", "rejected")
	})

	t.Run("ProviderRecords", func(t *testing.T) {
		// The provider records retain the function declaration, the
		// document with its directives, and the wire parameters.
		res, err := discover(t, dir, []string{"."}, []string{"example.com/proc.FindUser"}, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		p := res.Providers[0]
		if p.Name != "FindUser" || p.Func == nil {
			t.Fatalf("provider record = %+v", p)
		}
		if p.Doc == nil || !hasDirective(p.Doc.Doc, ProcedureDir) {
			t.Error("provider lost its procedure directive")
		}
		if !reflect.DeepEqual(p.Params, []string{"userID"}) {
			t.Errorf("params = %v, want [userID]", p.Params)
		}
		if !p.DataResult {
			t.Error("DataResult = false, want true")
		}
	})
}
