package tool

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"

	"github.com/cerasos/intercall/internal/syntax"
)

// This file tests the trusted generated-type semantic recovery of
// SPEC.md "Safe import and re-export metadata": decoding and validating
// the one `_intercallSemantic` constant of an intercall-generated file,
// finding the semantic declaration of a generated type, projecting the
// generated Go type back to its documentation-free wire structure, and
// recovering the declaration and its complete nested documentation tree
// without rescanning decoded documentation as Go directives.
//
// The fixture bodies are rendered through the canonical interface
// formatter, so the constants always encode byte-exact canonical
// interfaces; every variant that violates a consumer requirement is
// derived from the same fixture.

// markedTemplate is the generated import-binding fixture: the exact
// trust-boundary marker, two generated types with their machine lines
// and intercall field tags, and the semantic constant.
const markedTemplate = "// Code generated by intercall-go; DO NOT EDIT.\n" +
	"\n" +
	"// Package imp is a generated import binding.\n" +
	"package imp\n" +
	"\n" +
	"// @intercall type user_id\n" +
	"type UserID struct {\n" +
	"\tName string `intercall:\"name\"`\n" +
	"\tProfile struct {\n" +
	"\t\tBio []byte `intercall:\"bio\"`\n" +
	"\t} `intercall:\"profile\"`\n" +
	"}\n" +
	"\n" +
	"// @intercall type code\n" +
	"type Codes []uint8\n" +
	"\n" +
	"const _intercallSemantic = %s\n"

// genBody renders the canonical interface body of the generated
// fixture: the user_id record with a complete nested documentation
// tree, the code list type, and the find_user procedure.
func genBody(t *testing.T) []byte {
	t.Helper()
	f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
    profile record {
        bio bytes;
    };
};
type code list uint8;
procedure find_user {
    id user_id;
} record {
    ok uint8;
};
`))
	if err != nil {
		t.Fatalf("parsing body: %v", err)
	}
	userID := f.Decls[0].(*syntax.TypeDecl)
	userID.Doc = "the user type"
	userRec := userID.Type.(*syntax.RecordType)
	userRec.Fields[0].Doc = "the user identifier"
	userRec.Fields[1].Doc = "nested profile"
	userRec.Fields[1].Type.(*syntax.RecordType).Fields[0].Doc = "the bio"
	if err := syntax.Validate(f); err != nil {
		t.Fatalf("validating body: %v", err)
	}
	return syntax.Format(f)
}

// markedSource renders the marked import-binding fixture with the
// canonical encoding of body as the semantic constant. chunked splits
// the encoding into two literals whose first chunk has exactly 4096
// bytes.
func markedSource(t *testing.T, body []byte, chunked bool) []byte {
	t.Helper()
	enc := base64.RawURLEncoding.EncodeToString(body)
	lit := strconv.Quote(enc)
	if chunked {
		if len(enc) <= 4096 {
			t.Fatalf("chunked fixture must exceed 4096 encoded bytes, got %d", len(enc))
		}
		lit = strconv.Quote(enc[:4096]) + " +\n\t" + strconv.Quote(enc[4096:])
	}
	return []byte(fmt.Sprintf(markedTemplate, lit))
}

// recoverFixture parses one marked fixture and recovers its semantic
// metadata.
func recoverFixture(t *testing.T, src []byte) (*Document, *ast.File, *Semantic) {
	t.Helper()
	doc, err := ParseGoSource("imp.go", src)
	if err != nil {
		t.Fatalf("parsing document: %v", err)
	}
	if !doc.IntercallGenerated {
		t.Fatal("fixture is not intercall-generated")
	}
	af, err := parser.ParseFile(token.NewFileSet(), "imp.go", src, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parsing AST: %v", err)
	}
	sem, err := RecoverSemantic(af, doc)
	if err != nil {
		t.Fatalf("recovering semantic: %v", err)
	}
	return doc, af, sem
}

// typeSpecOf returns the type spec named name of one parsed file.
func typeSpecOf(t *testing.T, af *ast.File, name string) *ast.TypeSpec {
	t.Helper()
	for _, d := range af.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, s := range gd.Specs {
			if ts := s.(*ast.TypeSpec); ts.Name.Name == name {
				return ts
			}
		}
	}
	t.Fatalf("no type %q in fixture", name)
	return nil
}

// wantRecoveryErr fails unless RecoverSemantic rejects src with an
// error containing every substring.
func wantRecoveryErr(t *testing.T, src []byte, contains ...string) {
	t.Helper()
	doc, err := ParseGoSource("imp.go", src)
	if err != nil {
		t.Fatalf("parsing document: %v", err)
	}
	af, err := parser.ParseFile(token.NewFileSet(), "imp.go", src, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parsing AST: %v", err)
	}
	_, err = RecoverSemantic(af, doc)
	if err == nil {
		t.Fatal("recovery succeeded, want an error")
	}
	for _, s := range contains {
		if !strings.Contains(err.Error(), s) {
			t.Errorf("error = %q, want it to contain %q", err.Error(), s)
		}
	}
}

// TestSemanticMetadata covers the consumer side of the machine
// metadata: the exactly-one canonical constant, canonical reparse and
// structural match, nested-doc recovery without directive rescanning,
// the trust boundary, and the mapping integration over generated
// import bindings in dependency and explicit packages.
func TestSemanticMetadata(t *testing.T) {
	body := genBody(t)

	t.Run("Recovery", func(t *testing.T) {
		_, af, sem := recoverFixture(t, markedSource(t, body, false))

		if len(sem.AST.Decls) != 3 {
			t.Fatalf("semantic declarations = %d, want 3", len(sem.AST.Decls))
		}

		// The semantic declaration of the exact wire name carries the
		// complete nested documentation tree.
		td, err := sem.TypeDecl("user_id")
		if err != nil {
			t.Fatalf("TypeDecl: %v", err)
		}
		if td.Doc != "the user type" {
			t.Errorf("type doc = %q", td.Doc)
		}
		rec := td.Type.(*syntax.RecordType)
		if rec.Fields[0].Doc != "the user identifier" {
			t.Errorf("field doc = %q", rec.Fields[0].Doc)
		}
		if rec.Fields[1].Doc != "nested profile" {
			t.Errorf("field doc = %q", rec.Fields[1].Doc)
		}
		if rec.Fields[1].Type.(*syntax.RecordType).Fields[0].Doc != "the bio" {
			t.Errorf("nested field doc = %q", rec.Fields[1].Type.(*syntax.RecordType).Fields[0].Doc)
		}
		td, err = sem.TypeDecl("code")
		if err != nil {
			t.Fatalf("TypeDecl(code): %v", err)
		}
		if got := typeKeyOf(td.Type); got != "list uint8" {
			t.Errorf("code underlying = %q", got)
		}
		if _, err := sem.TypeDecl("missing"); err == nil {
			t.Error("TypeDecl(missing) succeeded, want an error")
		}

		// The generated Go types project back to the documentation-free
		// semantic structure.
		for _, tc := range []struct {
			goName, wire, key string
		}{
			{"UserID", "user_id", "record{name string;profile record{bio bytes}}"},
			{"Codes", "code", "list uint8"},
		} {
			spec := typeSpecOf(t, af, tc.goName)
			projected, err := sem.ProjectType(spec.Type, tc.goName)
			if err != nil {
				t.Fatalf("ProjectType(%s): %v", tc.goName, err)
			}
			if got := typeKeyOf(projected); got != tc.key {
				t.Errorf("projected %s = %q, want %q", tc.goName, got, tc.key)
			}
			td, err := sem.TypeDecl(tc.wire)
			if err != nil {
				t.Fatalf("TypeDecl(%s): %v", tc.wire, err)
			}
			if !sameType(td.Type, projected) {
				t.Errorf("projected %s does not match its semantic declaration", tc.goName)
			}
		}
	})

	t.Run("MultiChunkConstant", func(t *testing.T) {
		// A long documentation slot pushes the canonical body past the
		// chunk size; the constant carries two quoted chunks whose first
		// chunk is exactly 4096 bytes.
		f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
    profile record {
        bio bytes;
    };
};
`))
		if err != nil {
			t.Fatalf("parsing body: %v", err)
		}
		rec := f.Decls[0].(*syntax.TypeDecl).Type.(*syntax.RecordType)
		rec.Fields[0].Doc = strings.Repeat("a", 5000)
		if err := syntax.Validate(f); err != nil {
			t.Fatalf("validating body: %v", err)
		}
		long := syntax.Format(f)
		if len(long) <= 4096 {
			t.Fatalf("body must exceed 4096 bytes, got %d", len(long))
		}
		_, af, sem := recoverFixture(t, markedSource(t, long, true))
		td, err := sem.TypeDecl("user_id")
		if err != nil {
			t.Fatalf("TypeDecl: %v", err)
		}
		doc := td.Type.(*syntax.RecordType).Fields[0].Doc
		if doc != strings.Repeat("a", 5000) {
			t.Errorf("recovered doc length = %d", len(doc))
		}
		spec := typeSpecOf(t, af, "UserID")
		projected, err := sem.ProjectType(spec.Type, "UserID")
		if err != nil {
			t.Fatalf("ProjectType: %v", err)
		}
		if !sameType(td.Type, projected) {
			t.Error("projected structure conflicts with the semantic declaration")
		}
	})

	t.Run("EmptyInterface", func(t *testing.T) {
		_, _, sem := recoverFixture(t, markedSource(t, nil, false))
		if len(sem.AST.Decls) != 0 {
			t.Errorf("empty interface has %d declarations", len(sem.AST.Decls))
		}
		if _, err := sem.TypeDecl("user_id"); err == nil {
			t.Error("TypeDecl on an empty interface succeeded")
		}
	})

	t.Run("NoncanonicalBase64", func(t *testing.T) {
		// The unpadded alphabet is required: a padded encoding is
		// rejected before any decoding.
		enc := base64.RawURLEncoding.EncodeToString(body) + "="
		src := []byte(fmt.Sprintf(markedTemplate, strconv.Quote(enc)))
		wantRecoveryErr(t, src, "base64url")
	})

	t.Run("InvalidBase64", func(t *testing.T) {
		src := []byte(fmt.Sprintf(markedTemplate, `"!!!"`))
		wantRecoveryErr(t, src, "not valid base64url")
	})

	t.Run("InvalidUTF8", func(t *testing.T) {
		enc := base64.RawURLEncoding.EncodeToString([]byte{0xff, 0xfe})
		src := []byte(fmt.Sprintf(markedTemplate, strconv.Quote(enc)))
		wantRecoveryErr(t, src, "not valid UTF-8")
	})

	t.Run("ParseFailure", func(t *testing.T) {
		enc := base64.RawURLEncoding.EncodeToString([]byte("this is not an interface"))
		src := []byte(fmt.Sprintf(markedTemplate, strconv.Quote(enc)))
		wantRecoveryErr(t, src, "decoded _intercallSemantic")
	})

	t.Run("ValidationFailure", func(t *testing.T) {
		// A forward reference passes parsing but fails protocol
		// validation.
		enc := base64.RawURLEncoding.EncodeToString([]byte("procedure p {\n    t x;\n};\n"))
		src := []byte(fmt.Sprintf(markedTemplate, strconv.Quote(enc)))
		wantRecoveryErr(t, src, "decoded _intercallSemantic")
	})

	t.Run("NoncanonicalBody", func(t *testing.T) {
		// The decoded bytes parse and validate but are not the canonical
		// reformatting.
		noncanonical := bytes.Replace(body, []byte("\n"), []byte("\n\n"), 1)
		enc := base64.RawURLEncoding.EncodeToString(noncanonical)
		src := []byte(fmt.Sprintf(markedTemplate, strconv.Quote(enc)))
		wantRecoveryErr(t, src, "not canonical")
	})

	t.Run("MissingConstant", func(t *testing.T) {
		src := []byte(strings.Replace(string(markedSource(t, body, false)), "\nconst _intercallSemantic = ", "\nconst other = ", 1))
		wantRecoveryErr(t, src, "no _intercallSemantic constant")
	})

	t.Run("DuplicateConstant", func(t *testing.T) {
		base := string(markedSource(t, body, false))
		constLine := "const _intercallSemantic = " + strconv.Quote(base64.RawURLEncoding.EncodeToString(body))
		src := []byte(strings.Replace(base, constLine, constLine+"\n"+constLine, 1))
		wantRecoveryErr(t, src, "duplicate _intercallSemantic constant")
	})

	t.Run("SharedSpecConstant", func(t *testing.T) {
		src := []byte(strings.Replace(string(markedSource(t, body, false)),
			"const _intercallSemantic = "+strconv.Quote(base64.RawURLEncoding.EncodeToString(body)),
			`const _intercallSemantic, other = "a", "b"`, 1))
		wantRecoveryErr(t, src, "must be declared alone")
	})

	t.Run("VarNotConstant", func(t *testing.T) {
		src := []byte(strings.Replace(string(markedSource(t, body, false)), "const _intercallSemantic", "var _intercallSemantic", 1))
		wantRecoveryErr(t, src, "no _intercallSemantic constant")
	})

	t.Run("NonLiteralValue", func(t *testing.T) {
		src := []byte(strings.Replace(string(markedSource(t, body, false)),
			"const _intercallSemantic = "+strconv.Quote(base64.RawURLEncoding.EncodeToString(body)),
			"const _intercallSemantic = other", 1))
		wantRecoveryErr(t, src, "must be a concatenation of string literals")
	})

	t.Run("ProjectionConflicts", func(t *testing.T) {
		// Each variant changes the generated Go type and therefore
		// conflicts with the semantic declaration or the projection
		// rules.
		variants := []struct{ name, decl, want string }{
			{"WrongTag", "Name string `intercall:\"nam\"`", ""},
			{"ChangedFieldType", "Name []byte `intercall:\"name\"`", ""},
			{"RemovedField", "Profile struct {\n\t\tBio []byte `intercall:\"bio\"`\n\t} `intercall:\"profile\"`", ""},
			{"MissingTag", "Name string", "has no intercall tag"},
			{"EmbeddedField", "string", "embedded and multi-name fields"},
			{"QualifiedType", "Name other.Type `intercall:\"name\"`", "qualified type"},
			{"NoMachineLineRef", "Name OtherType `intercall:\"name\"`", "has no @intercall type machine line"},
			{"Array", "Name [3]byte `intercall:\"name\"`", "array types"},
		}
		for _, v := range variants {
			t.Run(v.name, func(t *testing.T) {
				userID := "type UserID struct {\n\t" + v.decl + "\n}\n"
				src := []byte("// Code generated by intercall-go; DO NOT EDIT.\n" +
					"\n" +
					"package imp\n" +
					"\n" +
					"// @intercall type user_id\n" +
					userID +
					"\n" +
					"const _intercallSemantic = " + strconv.Quote(base64.RawURLEncoding.EncodeToString(body)) + "\n")
				_, af, sem := recoverFixture(t, src)
				spec := typeSpecOf(t, af, "UserID")
				projected, err := sem.ProjectType(spec.Type, "UserID")
				td, tderr := sem.TypeDecl("user_id")
				if tderr != nil {
					t.Fatalf("TypeDecl: %v", tderr)
				}
				if v.want != "" {
					if err == nil || !strings.Contains(err.Error(), v.want) {
						t.Errorf("ProjectType error = %v, want it to contain %q", err, v.want)
					}
					return
				}
				if err != nil {
					t.Fatalf("ProjectType: %v", err)
				}
				if sameType(td.Type, projected) {
					t.Error("projected structure unexpectedly matches the semantic declaration")
				}
			})
		}
	})

	t.Run("NestedDocsNeverRescanned", func(t *testing.T) {
		// Decoded documentation is assigned directly to AST slots: text
		// that looks like InterCall directives survives verbatim.
		f, err := syntax.Parse("body.intercall", []byte(`type user_id record {
    name string;
};
`))
		if err != nil {
			t.Fatalf("parsing body: %v", err)
		}
		td := f.Decls[0].(*syntax.TypeDecl)
		td.Doc = "@intercall type fake\n@param x y\nprose"
		rec := td.Type.(*syntax.RecordType)
		rec.Fields[0].Doc = "@intercall type also_fake"
		if err := syntax.Validate(f); err != nil {
			t.Fatalf("validating body: %v", err)
		}
		docBody := syntax.Format(f)
		_, _, sem := recoverFixture(t, markedSource(t, docBody, false))
		recovered, err := sem.TypeDecl("user_id")
		if err != nil {
			t.Fatalf("TypeDecl: %v", err)
		}
		if recovered.Doc != "@intercall type fake\n@param x y\nprose" {
			t.Errorf("type doc = %q", recovered.Doc)
		}
		if recovered.Type.(*syntax.RecordType).Fields[0].Doc != "@intercall type also_fake" {
			t.Errorf("field doc = %q", recovered.Type.(*syntax.RecordType).Fields[0].Doc)
		}
	})
	t.Run("TrustBoundary", func(t *testing.T) {
		// An unmarked handwritten file is ordinary Go: its malformed
		// _intercallSemantic constant is never machine metadata, and
		// the tagged type maps from its Go source like any handwritten
		// type.
		tm, err := mapOne(t, "example.com/synth", `package synth

import "context"

// @intercall type
type User struct {
	Name string
}

const _intercallSemantic = "!!! not base64url !!!"

// @intercall procedure use
func Use(ctx context.Context, u User) error { return nil }
`)
		if err != nil {
			t.Fatalf("mapping: %v", err)
		}
		mp := providerByName(t, tm, "Use")
		wantValue(t, mp.Params[0].Value, "user", false)
		if len(tm.Types) != 1 || tm.Types[0].Generated {
			t.Errorf("types = %+v, want one handwritten user type", tm.Types)
		}
	})
}

// genFixtureModule is the integration module of the generated-binding
// tests: a provider package referencing the generated import binding,
// and the output package.
var genFixtureModule = map[string]string{
	"go.mod": "module example.com/gen\n\ngo 1.26.5\n",
	"prov/prov.go": `// Package prov selects procedures over generated types.
package prov

import (
	"context"

	"example.com/gen/imp"
)

// @intercall procedure find_user
func FindUser(ctx context.Context, u imp.UserID) error { return nil }

// @intercall procedure codes
func Codes(ctx context.Context, c imp.Codes) error { return nil }
`,
	"out/out.go": `// Package out is the output target.
package out

// Helper is an ordinary function.
func Helper() {}
`,
}

// TestSemanticMetadataIntegration runs the discovery-to-mapping
// pipeline over a module whose dependency package is a generated import
// binding: the reachable generated types are recovered from the trusted
// machine metadata, their machine lines and field tags are validated,
// and their complete nested documentation trees come from the semantic
// source.
func TestSemanticMetadataIntegration(t *testing.T) {
	dir := writeFixture(t, genFixtureModule)
	impSrc := markedSource(t, genBody(t), false)
	if err := writeFileAt(t, dir, "imp/imp.go", impSrc); err != nil {
		t.Fatalf("writing generated fixture: %v", err)
	}

	load := func(t *testing.T, patterns ...string) *TypeMap {
		t.Helper()
		res, err := discover(t, dir, patterns, []string{
			"example.com/gen/prov.FindUser",
			"example.com/gen/prov.Codes",
		}, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		tm, err := MapValues(res.Providers, "example.com/gen/out")
		if err != nil {
			t.Fatalf("MapValues: %v", err)
		}
		return tm
	}

	check := func(t *testing.T, tm *TypeMap) {
		t.Helper()
		mp := providerByName(t, tm, "FindUser")
		wantValue(t, mp.Params[0].Value, "user_id", false)
		mp = providerByName(t, tm, "Codes")
		wantValue(t, mp.Params[0].Value, "code", false)

		// The recovered types are in topological order and carry the
		// semantic documentation tree.
		if got := typeWires(tm); !reflect.DeepEqual(got, []string{"code", "user_id"}) {
			t.Errorf("types = %v, want [code user_id]", got)
		}
		var userID *NamedType
		for _, rec := range tm.Types {
			if rec.WireName == "user_id" {
				userID = rec
			}
			if !rec.Generated {
				t.Errorf("type %s: Generated = false, want true", rec.WireName)
			}
		}
		if userID == nil {
			t.Fatal("user_id not recovered")
		}
		if userID.Doc != "the user type" {
			t.Errorf("type doc = %q", userID.Doc)
		}
		rec := userID.Type.(*syntax.RecordType)
		if rec.Fields[0].Doc != "the user identifier" || rec.Fields[1].Doc != "nested profile" {
			t.Errorf("field docs = %q, %q", rec.Fields[0].Doc, rec.Fields[1].Doc)
		}
		if rec.Fields[1].Type.(*syntax.RecordType).Fields[0].Doc != "the bio" {
			t.Errorf("nested field doc = %q", rec.Fields[1].Type.(*syntax.RecordType).Fields[0].Doc)
		}
	}

	t.Run("DependencyPackage", func(t *testing.T) {
		// The generated binding is a dependency loaded only for type
		// checking; its file wrapper carries the trust boundary.
		check(t, load(t, "./prov"))
	})

	t.Run("ExplicitPackage", func(t *testing.T) {
		// The generated binding is itself an explicit package with
		// pre-parsed documents.
		check(t, load(t, "./prov", "./imp"))
	})

	t.Run("StructuralConflict", func(t *testing.T) {
		// A stale generated file whose tag no longer matches the
		// semantic declaration is rejected.
		stale := strings.Replace(string(impSrc), `intercall:"name"`, `intercall:"nam"`, 1)
		if err := writeFileAt(t, dir, "imp/imp.go", []byte(stale)); err != nil {
			t.Fatalf("writing stale fixture: %v", err)
		}
		res, err := discover(t, dir, []string{"./prov"}, []string{"example.com/gen/prov.FindUser"}, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		_, err = MapValues(res.Providers, "example.com/gen/out")
		wantErr(t, err, `generated type "UserID"`, "conflicts with its semantic declaration")
	})

	t.Run("MissingMachineLine", func(t *testing.T) {
		src := strings.Replace(string(impSrc), "\n// @intercall type user_id\n", "\n", 1)
		if err := writeFileAt(t, dir, "imp/imp.go", []byte(src)); err != nil {
			t.Fatalf("writing fixture: %v", err)
		}
		res, err := discover(t, dir, []string{"./prov"}, []string{"example.com/gen/prov.FindUser"}, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		_, err = MapValues(res.Providers, "example.com/gen/out")
		wantErr(t, err, `reachable type "UserID"`, "must have exactly one @intercall type directive")
	})

	t.Run("MachineLineWithoutWireName", func(t *testing.T) {
		src := strings.Replace(string(impSrc), "// @intercall type user_id", "// @intercall type", 1)
		if err := writeFileAt(t, dir, "imp/imp.go", []byte(src)); err != nil {
			t.Fatalf("writing fixture: %v", err)
		}
		res, err := discover(t, dir, []string{"./prov"}, []string{"example.com/gen/prov.FindUser"}, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		_, err = MapValues(res.Providers, "example.com/gen/out")
		wantErr(t, err, "malformed machine line", "expected the exact wire name")
	})

	t.Run("MalformedConstant", func(t *testing.T) {
		src := strings.Replace(string(impSrc), strconv.Quote(base64.RawURLEncoding.EncodeToString(genBody(t))), `"!!!not base64url!!!"`, 1)
		if err := writeFileAt(t, dir, "imp/imp.go", []byte(src)); err != nil {
			t.Fatalf("writing fixture: %v", err)
		}
		res, err := discover(t, dir, []string{"./prov"}, []string{"example.com/gen/prov.FindUser"}, nil, "out")
		if err != nil {
			t.Fatalf("discover: %v", err)
		}
		_, err = MapValues(res.Providers, "example.com/gen/out")
		wantErr(t, err, "not valid base64url")
	})
}

// writeFileAt writes one fixture file below dir, creating directories.
func writeFileAt(t *testing.T, dir, name string, content []byte) error {
	t.Helper()
	path := filepath.Join(dir, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}
